from pathlib import Path
import json

p = Path('abc/src/index.js')
s = p.read_text()

P1 = r'''<style id="abc-health-p1-css">
.abc-health-settings{margin-top:12px}.abc-health-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.abc-health-thresholds{display:grid;grid-template-columns:repeat(2,minmax(0,220px));gap:10px;margin-top:12px}.abc-health-total{font-size:12px;font-weight:850;margin:10px 0}.abc-form-note{padding:10px 12px;border:1px solid var(--line);border-radius:8px;background:var(--surface2);font-size:11px;color:var(--muted);margin:10px 0}.abc-formula{font-size:11px;line-height:1.55;color:var(--muted);margin-top:12px}.record-actions{display:flex;gap:6px;align-items:center;flex-wrap:wrap}.abc-score-chip{display:inline-flex;align-items:center;gap:5px;padding:4px 7px;border-radius:999px;border:1px solid var(--line);font-size:10px;font-weight:850;color:var(--muted)}
@media(max-width:800px){.abc-health-grid{grid-template-columns:1fr 1fr}.abc-health-thresholds{grid-template-columns:1fr 1fr}}@media(max-width:520px){.abc-health-grid,.abc-health-thresholds{grid-template-columns:1fr}}
</style><script id="abc-health-p1-script">
(function(){
'use strict';
const ABC_HEALTH_DEFAULTS={adoption:25,value:25,relationship:20,technical:15,supportRisk:10,successPlan:5};
const ABC_HEALTH_THRESHOLDS={healthy:80,watch:65};
const abcClamp=v=>Math.max(0,Math.min(100,Math.round(Number(v)||0)));
function abcEnsureHealthSettings(state){
 state.settings=state.settings||{};
 state.settings.healthWeights=Object.assign({},ABC_HEALTH_DEFAULTS,state.settings.healthWeights||{});
 state.settings.healthThresholds=Object.assign({},ABC_HEALTH_THRESHOLDS,state.settings.healthThresholds||{});
 state.settings.healthModelVersion=2;
}
function abcMeetingRecencyScore(a){
 const meetings=(a.meetings||[]).filter(m=>m.date).sort((x,y)=>String(y.date).localeCompare(String(x.date)));
 if(!meetings.length)return 35;
 const days=Math.max(0,Math.ceil((Date.now()-new Date(meetings[0].date+'T12:00:00').getTime())/86400000));
 if(days<=30)return 100;if(days<=60)return 85;if(days<=90)return 70;if(days<=120)return 55;return 40;
}
function abcRelationshipScore(a){
 const quality=abcClamp(a.stakeholderStrength??65),recency=abcMeetingRecencyScore(a),exec=(a.contacts||[]).some(c=>c.level==='C-Level')?100:40;
 return abcClamp(quality*.60+recency*.25+exec*.15);
}
function abcSupportRiskScore(a){
 const base=abcClamp(a.supportSla??95),sev=String(a.supportSeverity||'None').toLowerCase();
 const severityPenalty=sev.includes('sev 1')?25:sev.includes('sev 2')?15:sev.includes('sev 3')?7:0;
 let riskPenalty=0;
 for(const r of (a.risks||[]).filter(r=>String(r.status||'Open').toLowerCase()!=='closed')){
   const z=String(r.severity||'').toLowerCase();riskPenalty=Math.max(riskPenalty,z.includes('critical')?25:z.includes('high')?15:z.includes('medium')?8:z.includes('low')?3:5);
 }
 return abcClamp(base-Math.max(severityPenalty,riskPenalty));
}
function abcSuccessPlanScore(a){const plans=a.successPlans||[];return plans.length?abcClamp(plans.reduce((sum,x)=>sum+abcClamp(x.progress),0)/plans.length):50}
function abcHealthSignals(a){return{adoption:abcClamp(a.adoption),value:abcClamp(a.valueEvidence),relationship:abcRelationshipScore(a),technical:abcClamp(a.technicalCoverage),supportRisk:abcSupportRiskScore(a),successPlan:abcSuccessPlanScore(a)}}
function abcScoreAccount(a){
 const w=data.settings.healthWeights,sig=abcHealthSignals(a),total=Object.values(w).reduce((x,y)=>x+Number(y||0),0)||100;
 return abcClamp(Object.keys(ABC_HEALTH_DEFAULTS).reduce((sum,k)=>sum+sig[k]*Number(w[k]||0),0)/total);
}
function abcApplyHealth(a){
 a.health=abcScoreAccount(a);const t=data.settings.healthThresholds;
 a.status=a.health>=Number(t.healthy)?'Healthy':a.health>=Number(t.watch)?'Watch':'At Risk';return a.health;
}
function abcRecalcAll(){abcEnsureHealthSettings(data);(data.accounts||[]).forEach(abcApplyHealth)}
function abcFindRecord(key,prop){const [aid,rid]=String(key).split('|'),a=data.accounts.find(x=>String(x.id)===String(aid));return{a,r:a?.[prop]?.find(x=>String(x.id)===String(rid))}}
function abcWeightField(label,key,help){return `<div class="field"><label>${label} weight %</label><input class="input abc-health-weight" data-health-key="${key}" type="number" min="0" max="100" step="1" value="${data.settings.healthWeights[key]}"><div class="small-muted" style="margin-top:4px">${help}</div></div>`}
function abcHealthSettingsCard(){
 const w=data.settings.healthWeights,t=data.settings.healthThresholds,total=Object.values(w).reduce((x,y)=>x+Number(y||0),0);
 return `<div class="card abc-health-settings"><div class="section-head" style="margin:0 0 10px"><div><h2>Customer health model</h2><p>Transparent weighted scorecard based on standard Customer Success health dimensions, tuned for Abnormal's enterprise cybersecurity motion.</p></div><span class="abc-score-chip">Calculated, not manual</span></div><div class="abc-health-grid">
 ${abcWeightField('Adoption','adoption','Depth/breadth of platform use and feature engagement.')}
 ${abcWeightField('Value realization','value','Evidence of ROI, outcomes and Business Review proof.')}
 ${abcWeightField('Relationship & engagement','relationship','Sponsor/champion quality, executive coverage and meeting recency.')}
 ${abcWeightField('Technical / deployment','technical','Technical coverage, deployment readiness and solution enablement.')}
 ${abcWeightField('Support / risk','supportRisk','Support confidence reduced by the strongest active severity/risk penalty.')}
 ${abcWeightField('Success-plan execution','successPlan','Average progress against agreed success-plan objectives.')}
 </div><div class="abc-health-total">Weight total: <span id="abc-health-total">${total}</span>% <span class="small-muted">(must equal 100%)</span></div>
 <div class="abc-health-thresholds"><div class="field"><label>Healthy starts at</label><input id="abc-healthy-threshold" class="input" type="number" min="1" max="100" value="${t.healthy}"></div><div class="field"><label>Watch starts at</label><input id="abc-watch-threshold" class="input" type="number" min="0" max="99" value="${t.watch}"></div></div>
 <div id="abc-health-settings-error" class="small-muted" style="min-height:18px;margin-top:8px;color:var(--bad)"></div>
 <div class="hero-actions"><button class="btn primary" id="abc-save-health-model">Save health model</button><button class="btn" id="abc-reset-health-model">Reset recommended weights</button></div>
 <div class="abc-formula"><strong>Formula:</strong> weighted average of the six measures above. Relationship & engagement = 60% relationship-quality assessment + 25% meeting recency + 15% executive coverage. Support / risk = support confidence minus the strongest active severity or risk penalty. Commercial readiness and renewal timing stay separate so Health does not become a circular renewal forecast.</div></div>`;
}
function abcHealthRows(a){const s=abcHealthSignals(a),w=data.settings.healthWeights;return healthRow(`Adoption · ${w.adoption}%`,s.adoption)+healthRow(`Value realization · ${w.value}%`,s.value)+healthRow(`Relationship & engagement · ${w.relationship}%`,s.relationship)+healthRow(`Technical / deployment · ${w.technical}%`,s.technical)+healthRow(`Support / risk · ${w.supportRisk}%`,s.supportRisk)+healthRow(`Success-plan execution · ${w.successPlan}%`,s.successPlan)}
function abcEditContact(a,c){const x=c||{name:'',title:'',email:'',role:'Program Champion',level:'VP'};modal(`<h3>${c?'Edit':'Add'} stakeholder</h3><div class="formgrid">${f('Name','c-name',x.name)}${f('Title','c-title',x.title)}${f('Email','c-email',x.email)}${f('Role','c-role',x.role)}${f('Level','c-level',x.level)}</div><div class="modal-actions"><button class="btn" data-close>Cancel</button><button class="btn primary" id="save-contact">${c?'Save stakeholder':'Add stakeholder'}</button></div>`,()=>{document.querySelector('#save-contact').onclick=()=>{const z={id:c?.id||uid('ct'),name:v('c-name'),title:v('c-title'),email:v('c-email'),role:v('c-role'),level:v('c-level')};if(c)Object.assign(c,z);else a.contacts.push(z);save(data);closeModal();render();notify(c?'Stakeholder updated':'Stakeholder added')}})}
function abcEditMeeting(a,m){const x=m||{date:new Date().toISOString().slice(0,10),type:'Executive Business Review',title:'Customer operating review',attendees:'',notes:''};modal(`<h3>${m?'Edit':'Log'} meeting</h3><div class="formgrid">${f('Date','m-date',x.date,'date')}${f('Meeting type','m-type',x.type)}${f('Title','m-title',x.title)}${f('Attendees','m-attendees',x.attendees)}</div><div class="field" style="margin-top:10px"><label>Notes</label><textarea class="textarea" id="m-notes">${esc(x.notes||'')}</textarea></div><div class="modal-actions"><button class="btn" data-close>Cancel</button><button class="btn primary" id="save-meeting">${m?'Save meeting':'Log meeting'}</button></div>`,()=>{document.querySelector('#save-meeting').onclick=()=>{const z={id:m?.id||uid('mtg'),date:v('m-date'),type:v('m-type'),title:v('m-title'),attendees:v('m-attendees'),notes:v('m-notes')};if(m)Object.assign(m,z);else a.meetings.push(z);save(data);closeModal();accountTab='meetings';render();notify(m?'Meeting updated':'Meeting logged')}})}
function abcEditNote(a,n){const x=n||{date:new Date().toISOString().slice(0,10),text:''};modal(`<h3>${n?'Edit':'Add'} account note</h3>${f('Date','n-date',x.date,'date')}<div class="field" style="margin-top:10px"><label>Note</label><textarea class="textarea" id="n-text" placeholder="Decision, commitment, customer feedback, risk, or follow-up context">${esc(x.text||'')}</textarea><div id="note-error" class="small-muted" style="min-height:16px;margin-top:6px;color:var(--bad)"></div></div><div class="modal-actions"><button class="btn" data-close>Cancel</button><button class="btn primary" id="save-note">${n?'Save note':'Add note'}</button></div>`,()=>{document.querySelector('#save-note').onclick=()=>{const text=v('n-text').trim(),date=v('n-date');if(!text){document.getElementById('note-error').textContent='Enter a note before saving.';return}if(n)Object.assign(n,{date,text});else a.notes.unshift({id:uid('note'),date,text});save(data);closeModal();accountTab='notes';render();notify('Note saved')}})}
function abcEditSuccess(a,sp){const x=sp||{objective:'',progress:50,owner:'CSM + Customer',proof:''};modal(`<h3>${sp?'Edit':'Add'} success-plan objective</h3>${f('Objective','s-objective',x.objective)}${f('Progress %','s-progress',x.progress,'number')}${f('Owner','s-owner',x.owner)}${f('Proof definition','s-proof',x.proof)}<div class="modal-actions"><button class="btn" data-close>Cancel</button><button class="btn primary" id="save-success">${sp?'Save objective':'Add objective'}</button></div>`,()=>{document.querySelector('#save-success').onclick=()=>{const z={id:sp?.id||uid('sp'),objective:v('s-objective'),progress:abcClamp(v('s-progress')),owner:v('s-owner'),proof:v('s-proof')};if(sp)Object.assign(sp,z);else a.successPlans.push(z);save(data);closeModal();accountTab='success';render();notify(sp?'Success objective updated':'Success objective added')}})}
function abcEditRisk(a,r){const x=r||{title:'',severity:'Medium',owner:'CSM',status:'Open'};modal(`<h3>${r?'Edit':'Add'} customer risk</h3><div class="formgrid">${f('Risk / issue','r-title',x.title)}${f('Severity','r-severity',x.severity)}${f('Owner','r-owner',x.owner)}${f('Status','r-status',x.status)}</div><div class="modal-actions"><button class="btn" data-close>Cancel</button><button class="btn primary" id="save-risk">${r?'Save risk':'Add risk'}</button></div>`,()=>{document.querySelector('#save-risk').onclick=()=>{const z={id:r?.id||uid('risk'),title:v('r-title'),severity:v('r-severity'),owner:v('r-owner'),status:v('r-status')};if(r)Object.assign(r,z);else(a.risks||(a.risks=[])).push(z);save(data);closeModal();accountTab='summary';render();notify(r?'Risk updated':'Risk added')}})}
function abcTechnicalForm(a){modal(`<h3>Edit Technical & Services context</h3><div class="formgrid">${f('Service owner','t-owner',a.serviceOwner||'Technical Success')}${f('Technical coverage %','t-coverage',a.technicalCoverage,'number')}${f('Support confidence %','t-support',a.supportSla,'number')}${f('Current severity','t-severity',a.supportSeverity||'None')}${f('Services utilization %','t-services',a.servicesUtilization,'number')}${f('Integrations (comma separated)','t-integrations',(a.integrations||[]).join(', '))}${f('Active modules (comma separated)','t-modules',(a.activeModules||[]).join(', '))}</div><div class="modal-actions"><button class="btn" data-close>Cancel</button><button class="btn primary" id="save-technical">Save technical context</button></div>`,()=>{document.querySelector('#save-technical').onclick=()=>{Object.assign(a,{serviceOwner:v('t-owner'),technicalCoverage:abcClamp(v('t-coverage')),supportSla:abcClamp(v('t-support')),supportSeverity:v('t-severity'),servicesUtilization:abcClamp(v('t-services')),integrations:v('t-integrations').split(',').map(x=>x.trim()).filter(Boolean),activeModules:v('t-modules').split(',').map(x=>x.trim()).filter(Boolean)});save(data);closeModal();accountTab='technical';render();notify('Technical context saved')}})}
function abcCommercialForm(a){modal(`<h3>Edit Commercial & Value context</h3><div class="formgrid">${f('ARR','cm-arr',a.arr,'number')}${f('Renewal date','cm-renewal',a.renewalDate,'date')}${f('Value evidence %','cm-value',a.valueEvidence,'number')}${f('Relationship quality %','cm-relationship',a.stakeholderStrength,'number')}${f('Commercial readiness %','cm-readiness',a.commercialReadiness,'number')}${f('Account Executive','cm-ae',a.accountExec||'')}</div><div class="abc-form-note">Value evidence and relationship quality feed Health. Commercial readiness and renewal timing remain separate readiness signals.</div><div class="modal-actions"><button class="btn" data-close>Cancel</button><button class="btn primary" id="save-commercial">Save commercial context</button></div>`,()=>{document.querySelector('#save-commercial').onclick=()=>{Object.assign(a,{arr:Number(v('cm-arr'))||0,renewalDate:v('cm-renewal'),valueEvidence:abcClamp(v('cm-value')),stakeholderStrength:abcClamp(v('cm-relationship')),commercialReadiness:abcClamp(v('cm-readiness')),accountExec:v('cm-ae')});save(data);closeModal();accountTab='commercial';render();notify('Commercial context saved')}})}

document.addEventListener('DOMContentLoaded',()=>{
 if(typeof data==='undefined'||typeof render!=='function')return;
 abcEnsureHealthSettings(data);
 const originalSettingsView=settingsView,originalAccountTabContent=accountTabContent,originalBind=bind,originalRender=render;
 healthLabel=function(v){const t=data.settings.healthThresholds;return Number(v)>=Number(t.healthy)?'Healthy':Number(v)>=Number(t.watch)?'Watch':'At Risk'};
 healthClass=function(v){const t=data.settings.healthThresholds;return Number(v)>=Number(t.healthy)?'good':Number(v)>=Number(t.watch)?'warn':'bad'};
 settingsView=function(){return originalSettingsView()+abcHealthSettingsCard()};
 accountForm=function(a){
  const x=a||{name:'',industry:'',region:'TOLA',owner:'',arr:0,adoption:75,startDate:'2026-01-01',endDate:'2027-01-01',renewalDate:'2027-01-01',lifecycle:'Adoption',primaryOutcome:'',summary:''};
  modal(`<h3>${a?'Edit account':'Add account'}</h3><div class="formgrid">${f('Account name','f-name',x.name)}${f('Industry','f-industry',x.industry)}${f('Region','f-region',x.region)}${f('Owner','f-owner',x.owner)}${f('ARR','f-arr',x.arr,'number')}${f('Adoption %','f-adoption',x.adoption??75,'number')}${f('Start date','f-start',x.startDate,'date')}${f('End date','f-end',x.endDate,'date')}${f('Renewal date','f-renewal',x.renewalDate,'date')}${f('Lifecycle','f-life',x.lifecycle)}${f('Primary outcome','f-outcome',x.primaryOutcome)}</div><div class="field" style="margin-top:10px"><label>Summary</label><textarea class="textarea" id="f-summary">${esc(x.summary||'')}</textarea></div><div class="abc-form-note"><strong>Health is calculated.</strong> Change the underlying signals in the account workspace or adjust the model weights in Settings.</div><div class="modal-actions"><button class="btn" data-close>Cancel</button><button class="btn primary" id="save-account">${a?'Save changes':'Add account'}</button></div>`,()=>{document.querySelector('#save-account').onclick=()=>{const g=id=>document.getElementById(id).value,base=a?{...a}:{id:uid('acct'),contacts:[],meetings:[],notes:[],risks:[],successPlans:[],integrations:[],activeModules:[],supportSla:95,adoption:75,valueEvidence:70,stakeholderStrength:65,commercialReadiness:65,servicesUtilization:70,technicalCoverage:80,supportSeverity:'None',serviceOwner:'Technical Success',accountExec:''};Object.assign(base,{name:g('f-name'),industry:g('f-industry'),region:g('f-region'),owner:g('f-owner'),arr:Number(g('f-arr'))||0,adoption:abcClamp(g('f-adoption')),startDate:g('f-start'),endDate:g('f-end'),renewalDate:g('f-renewal'),lifecycle:g('f-life'),primaryOutcome:g('f-outcome'),summary:g('f-summary')});abcApplyHealth(base);if(a){const i=data.accounts.findIndex(z=>String(z.id)===String(a.id));data.accounts[i]=base}else data.accounts.unshift(base);save(data);closeModal();selected=base.id;route='account';render()}})
 };
 addContact=(a)=>abcEditContact(a,null);addMeeting=(a)=>abcEditMeeting(a,null);addNote=(a)=>abcEditNote(a,null);addSuccess=(a)=>abcEditSuccess(a,null);
 accountTabContent=function(a){
  if(accountTab==='summary')return `<div class="split"><div class="stack"><div class="card"><div class="section-head" style="margin:0 0 10px"><div><h2>Account context</h2><p>The customer story in one place.</p></div></div><p>${esc(a.summary)}</p><div class="callout"><strong>Primary outcome:</strong> ${esc(a.primaryOutcome)}</div></div><div class="card"><div class="section-head" style="margin:0 0 10px"><div><h2>Calculated health</h2><p>Weighted signals from the configured Customer Success scorecard.</p></div><span class="health ${healthClass(a.health)}">${a.health}/100 · ${healthLabel(a.health)}</span></div>${abcHealthRows(a)}</div></div><div class="stack"><div class="card"><h2 style="margin-top:0">Contract & dates</h2>${detail('Start date',fmtDate(a.startDate))}${detail('End date',fmtDate(a.endDate))}${detail('Renewal date',fmtDate(a.renewalDate))}${detail('Lifecycle',a.lifecycle)}${detail('Account Executive',a.accountExec)}</div><div class="card"><div class="section-head" style="margin:0 0 10px"><div><h2>Open risks</h2><p>Active customer and escalation context.</p></div><button class="btn primary" data-add-risk="${a.id}">Add risk</button></div>${(a.risks||[]).length?(a.risks||[]).map(r=>`<div class="record"><div class="recordtop"><div><h4>${esc(r.title)}</h4><p>${esc(r.severity)} · ${esc(r.status)} · Owner ${esc(r.owner)}</p></div><div class="record-actions"><button class="mini" data-edit-risk="${a.id}|${r.id}">Edit</button><button class="mini" data-del-risk="${a.id}|${r.id}">Remove</button></div></div></div>`).join(''):'<div class="small-muted">No stored open risks.</div>'}</div></div></div>`;
  if(accountTab==='stakeholders')return listSection('Stakeholders','Executive sponsor, champion, technical owner and user-added contacts.',`<button class="btn primary" data-add-contact="${a.id}">Add stakeholder</button>`,(a.contacts||[]).map(c=>`<div class="record"><div class="recordtop"><div><h4>${esc(c.name)}</h4><p>${esc(c.title)} · ${esc(c.level)}</p><div class="small">${esc(c.role)} · ${esc(c.email)}</div></div><div class="record-actions"><button class="mini" data-edit-contact="${a.id}|${c.id}">Edit</button><button class="mini" data-del-contact="${a.id}|${c.id}">Remove</button></div></div></div>`).join(''));
  if(accountTab==='success')return listSection('Success plan','Objectives, progress, owners, and proof definitions.',`<button class="btn primary" data-add-success="${a.id}">Add objective</button>`,(a.successPlans||[]).map(sp=>`<div class="record"><div class="recordtop"><div><h4>${esc(sp.objective)}</h4><p>${esc(sp.owner)} · ${sp.progress}% complete</p><div class="bar"><span style="width:${sp.progress}%"></span></div><div class="small" style="margin-top:7px">Proof: ${esc(sp.proof)}</div></div><div class="record-actions"><button class="mini" data-edit-success="${a.id}|${sp.id}">Edit</button><button class="mini" data-del-success="${a.id}|${sp.id}">Remove</button></div></div></div>`).join(''));
  if(accountTab==='technical')return `<div class="section-head"><div><h2>Technical & Services</h2><p>Deployment, support and service context that feeds technical and risk health signals.</p></div><button class="btn primary" data-edit-technical="${a.id}">Edit technical context</button></div><div class="grid two"><div class="card"><h2 style="margin-top:0">Technical lifecycle</h2>${detail('Service owner',a.serviceOwner)}${detail('Technical coverage',a.technicalCoverage+'%')}${detail('Support confidence',a.supportSla+'%')}${detail('Current severity',a.supportSeverity)}${detail('Integrations',(a.integrations||[]).join(', '))}${detail('Active modules',(a.activeModules||[]).join(', '))}</div><div class="card"><h2 style="margin-top:0">Operating picture</h2>${healthRow('Services utilization',a.servicesUtilization)}${healthRow('Technical coverage',a.technicalCoverage)}${healthRow('Support / risk',abcSupportRiskScore(a))}</div></div>`;
  if(accountTab==='meetings')return listSection('Meetings & EBRs','Meeting history plus a deterministic readiness brief assembled from current records.',`<button class="btn blue" data-brief="${a.id}">Generate meeting brief</button><button class="btn primary" data-add-meeting="${a.id}">Log meeting</button>`,(a.meetings||[]).map(m=>`<div class="record"><div class="recordtop"><div><h4>${esc(m.type)} · ${fmtDate(m.date)}</h4><p>${esc(m.title)}</p><div class="small">Attendees: ${esc(m.attendees)}</div><div class="small">${esc(m.notes)}</div></div><div class="record-actions"><button class="mini" data-edit-meeting="${a.id}|${m.id}">Edit</button><button class="mini" data-del-meeting="${a.id}|${m.id}">Remove</button></div></div></div>`).join(''));
  if(accountTab==='notes')return listSection('Account notes','Timestamped decisions, commitments, observations, and follow-up context.',`<button class="btn primary" data-add-note="${a.id}">Add note</button>`,(a.notes||[]).map(n=>`<div class="record"><div class="recordtop"><div><h4>${fmtDate(n.date)}</h4><p>${esc(n.text)}</p></div><div class="record-actions"><button class="mini" data-edit-note="${a.id}|${n.id}">Edit</button><button class="mini" data-del-note="${a.id}|${n.id}">Remove</button></div></div></div>`).join(''));
  if(accountTab==='commercial')return `<div class="section-head"><div><h2>Commercial & Value</h2><p>Renewal timing, value evidence, relationship quality and commercial readiness kept distinct from calculated Health.</p></div><button class="btn primary" data-edit-commercial="${a.id}">Edit commercial context</button></div><div class="grid two"><div class="card"><h2 style="margin-top:0">Renewal & commercial readiness</h2>${detail('Days remaining',daysTo(a.renewalDate))}${detail('ARR',fmtMoney(a.arr))}${detail('Calculated Health',a.health+'/100')}${detail('Value evidence',a.valueEvidence+'%')}${detail('Relationship quality',a.stakeholderStrength+'%')}${detail('Commercial readiness',a.commercialReadiness+'%')}</div><div class="card"><h2 style="margin-top:0">Readiness thresholds</h2>${healthRow('Value evidence',a.valueEvidence)}${healthRow('Relationship & engagement',abcRelationshipScore(a))}${healthRow('Commercial readiness',a.commercialReadiness)}<div class="callout" style="margin-top:12px">Commercial readiness is a separate CSM/AE assessment, not a hidden input to Health.</div></div></div>`;
  return originalAccountTabContent(a)
 };
 bind=function(){
  originalBind();
  document.querySelectorAll('.abc-health-weight').forEach(x=>x.oninput=()=>{const total=[...document.querySelectorAll('.abc-health-weight')].reduce((s,z)=>s+Number(z.value||0),0);const el=document.getElementById('abc-health-total');if(el)el.textContent=total});
  document.querySelector('#abc-save-health-model')?.addEventListener('click',()=>{const next={};document.querySelectorAll('.abc-health-weight').forEach(x=>next[x.dataset.healthKey]=Number(x.value||0));const total=Object.values(next).reduce((x,y)=>x+y,0),healthy=Number(document.getElementById('abc-healthy-threshold').value),watch=Number(document.getElementById('abc-watch-threshold').value),err=document.getElementById('abc-health-settings-error');if(total!==100){err.textContent=`Weights must total 100%. Current total: ${total}%.`;return}if(!(healthy>watch&&healthy<=100&&watch>=0)){err.textContent='Healthy threshold must be greater than Watch threshold.';return}data.settings.healthWeights=next;data.settings.healthThresholds={healthy,watch};abcRecalcAll();save(data);render();notify('Health model saved and portfolio recalculated');if(typeof gtag==='function')gtag('event','health_model_saved',{demo_name:'abnormal_enterprise_customer_success'})});
  document.querySelector('#abc-reset-health-model')?.addEventListener('click',()=>{data.settings.healthWeights={...ABC_HEALTH_DEFAULTS};data.settings.healthThresholds={...ABC_HEALTH_THRESHOLDS};abcRecalcAll();save(data);render();notify('Recommended health model restored')});
  document.querySelectorAll('[data-edit-technical]').forEach(x=>x.onclick=()=>abcTechnicalForm(data.accounts.find(a=>String(a.id)===String(x.dataset.editTechnical))));
  document.querySelectorAll('[data-edit-commercial]').forEach(x=>x.onclick=()=>abcCommercialForm(data.accounts.find(a=>String(a.id)===String(x.dataset.editCommercial))));
  document.querySelectorAll('[data-add-risk]').forEach(x=>x.onclick=()=>abcEditRisk(data.accounts.find(a=>String(a.id)===String(x.dataset.addRisk)),null));
  document.querySelectorAll('[data-edit-risk]').forEach(x=>x.onclick=()=>{const q=abcFindRecord(x.dataset.editRisk,'risks');if(q.a&&q.r)abcEditRisk(q.a,q.r)});
  document.querySelectorAll('[data-del-risk]').forEach(x=>x.onclick=()=>delRec(x.dataset.delRisk,'risks'));
  document.querySelectorAll('[data-edit-contact]').forEach(x=>x.onclick=()=>{const q=abcFindRecord(x.dataset.editContact,'contacts');if(q.a&&q.r)abcEditContact(q.a,q.r)});
  document.querySelectorAll('[data-edit-meeting]').forEach(x=>x.onclick=()=>{const q=abcFindRecord(x.dataset.editMeeting,'meetings');if(q.a&&q.r)abcEditMeeting(q.a,q.r)});
  document.querySelectorAll('[data-edit-note]').forEach(x=>x.onclick=()=>{const q=abcFindRecord(x.dataset.editNote,'notes');if(q.a&&q.r)abcEditNote(q.a,q.r)});
  document.querySelectorAll('[data-edit-success]').forEach(x=>x.onclick=()=>{const q=abcFindRecord(x.dataset.editSuccess,'successPlans');if(q.a&&q.r)abcEditSuccess(q.a,q.r)});
 };
 trackPageView=function(){const view=route==='account'?('account/'+accountTab):route;if(view===lastAnalyticsView)return;lastAnalyticsView=view;const root=location.hostname.toLowerCase().startsWith('an.')?'/an/':'/abc/';if(typeof gtag==='function')gtag('event','page_view',{page_title:'Abnormal CS '+view,page_location:location.href,page_path:root+view,demo_name:'abnormal_enterprise_customer_success'})};
 render=function(){abcEnsureHealthSettings(data);abcRecalcAll();save(data);originalRender()};
 render();
});
})();
</script>'''

const_line = 'const ABNORMAL_HEALTH_P1_SCRIPT = ' + json.dumps(P1) + ';\n\n'
marker = 'const ABNORMAL_MODEL_SCRIPT = '
if 'const ABNORMAL_HEALTH_P1_SCRIPT =' not in s:
    if marker not in s:
        raise SystemExit('model marker not found')
    s = s.replace(marker, const_line + marker, 1)

old = '`${ABNORMAL_GATE_CSS}${ABNORMAL_APP_CSS}${ABNORMAL_MODEL_SCRIPT}</head>`'
new = '`${ABNORMAL_GATE_CSS}${ABNORMAL_APP_CSS}${ABNORMAL_MODEL_SCRIPT}${ABNORMAL_HEALTH_P1_SCRIPT}</head>`'
if old in s:
    s = s.replace(old, new, 1)
elif '${ABNORMAL_HEALTH_P1_SCRIPT}</head>' not in s:
    raise SystemExit('head injection marker not found')

p.write_text(s)
print('patched health model + P1 runtime')
