export const GA_MEASUREMENT_ID = "G-DCY144YM9P";

export const CRM_PORTFOLIO = Object.freeze([
  {
    id: "n7crm",
    name: "Neuron7 Customer Value OS",
    shortName: "N7",
    hostname: "n7crm.clintware.com",
    url: "https://n7crm.clintware.com/",
    pathPrefix: "/n7crm/",
    coverage: "Portfolio + all 21 customer workspace modules",
    platform: "Cloudflare Worker",
    analyticsMode: "ga4",
    color: "#7dd3fc",
  },
  {
    id: "n7case",
    name: "Neuron7 Case + ROI",
    shortName: "N7R",
    hostname: "n7.clintware.com",
    url: "https://n7.clintware.com/",
    pathPrefix: "/n7case/",
    coverage: "Case-study overview, ROI console, and scoped operator surface",
    platform: "Cloudflare Worker",
    analyticsMode: "worker-observability",
    color: "#67e8f9",
  },
  {
    id: "n7demo",
    name: "Neuron7 Demo CRM",
    shortName: "N7D",
    hostname: "n7demo.clintware.com",
    url: "https://n7demo.clintware.com/",
    pathPrefix: "/n7demo/",
    coverage: "Guest + account CRM, AI, Live Assist, Jira, Confluence, and KB",
    platform: "Cloudflare Worker",
    analyticsMode: "control-plane",
    color: "#a5b4fc",
  },
  {
    id: "abnormal",
    name: "Abnormal",
    shortName: "AN",
    hostname: "an.clintware.com",
    url: "https://an.clintware.com/",
    pathPrefix: "/an/",
    coverage: "Primary routes + every account tab",
    platform: "Cloudflare Worker",
    analyticsMode: "ga4",
    color: "#ff4f8b",
  },
  {
    id: "zscaler",
    name: "Zscaler",
    shortName: "ZS",
    hostname: "zsc.clintware.com",
    url: "https://zsc.clintware.com/",
    pathPrefix: "/zsc/",
    coverage: "Primary routes + every account tab",
    platform: "Cloudflare Worker",
    analyticsMode: "ga4",
    color: "#45c4ff",
  },
  {
    id: "dtex",
    name: "DTEX",
    shortName: "DX",
    hostname: "summertime-crmdemo.clintware.com",
    url: "https://summertime-crmdemo.clintware.com/",
    pathPrefix: "/dtex/",
    coverage: "All 9 workspace views",
    platform: "Cloudflare Pages",
    analyticsMode: "ga4",
    color: "#34d6a4",
  },
  {
    id: "nvidia",
    name: "NVIDIA",
    shortName: "NV",
    hostname: "nv.clintware.com",
    url: "https://nv.clintware.com/",
    pathPrefix: "/nv/",
    coverage: "All 6 workspaces",
    platform: "ChatGPT Sites",
    analyticsMode: "ga4",
    color: "#8de047",
  },
  {
    id: "proofpoint",
    name: "Proofpoint",
    shortName: "PP",
    hostname: "pp.clintware.com",
    url: "https://pp.clintware.com/",
    pathPrefix: "/pp/",
    coverage: "All 4 workspaces",
    platform: "ChatGPT Sites",
    analyticsMode: "ga4",
    color: "#f2a93b",
  },
  {
    id: "civilgrid",
    name: "CivilGrid",
    shortName: "CG",
    hostname: "cg-csm.clintware.com",
    url: "https://cg-csm.clintware.com/",
    pathPrefix: "/cg/",
    coverage: "Every view + all 6 account tabs",
    platform: "ChatGPT Sites",
    analyticsMode: "ga4",
    color: "#a78bfa",
  },
  {
    id: "renewnudge",
    name: "RenewNudge",
    shortName: "RN",
    hostname: "renewnudge.clintware.com",
    url: "https://renewnudge.clintware.com/",
    pathPrefix: "/renewnudge/",
    coverage: "Every public, auth, app, and account route",
    platform: "Lovable",
    analyticsMode: "ga4",
    color: "#ff6b6b",
  },
]);

export function crmForPage(pathname, hostname = "") {
  const normalizedPath = pathname.startsWith("/") ? pathname : `/${pathname}`;
  const normalizedHost = hostname.toLowerCase();
  return CRM_PORTFOLIO.find(
    (crm) =>
      normalizedPath === crm.pathPrefix.slice(0, -1) ||
      normalizedPath.startsWith(crm.pathPrefix) ||
      normalizedHost === crm.hostname,
  );
}
