export const gmailClientJs = String.raw`
(function(){
  'use strict';
  var SCOPES='https://www.googleapis.com/auth/gmail.readonly https://www.googleapis.com/auth/gmail.compose';
  var tokenClient=null;
  var accessToken='';
  var tokenExpires=0;
  var gmailProfile=null;
  var evidence=[];
  var $=function(id){return document.getElementById(id)};
  function esc(v){return String(v==null?'':v).replace(/[&<>\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]})}
  function status(msg,kind){var e=$('ltpGmailStatus');if(!e)return;e.textContent=msg;e.style.color=kind==='ok'?'#70e2a8':kind==='bad'?'#e68378':'#98aabc'}
  function ga(name,extra){try{if(typeof gtag==='function')gtag('event',name,Object.assign({product:'landtheplane',feature:'gmail_oauth_mvp'},extra||{}))}catch(e){}}
  function headersOf(payload){var out={};((payload&&payload.headers)||[]).forEach(function(h){out[String(h.name||'').toLowerCase()]=h.value||''});return out}
  function classify(text){var s=String(text||'').toLowerCase();if(/not moving forward|unfortunately|other candidates|position (has been|is) filled|decided not to (move|proceed)|will not be moving|regret to inform/.test(s))return 'closed';if(/on hold|need to pause|put .* on hold|pause (the|this|our) (role|search|process)|hiring pause/.test(s))return 'paused';if(/interview|hiring manager|panel|next step|schedule .*call|schedule .*conversation|meet with|availability/.test(s))return 'interview';if(/thank(s| you) for applying|application received|we received your application|received your application|application confirmation/.test(s))return 'applied';if(/introduction|intro to|recruiter|search firm|talent partner/.test(s))return 'network';return 'other'}
  function displaySender(from){var m=String(from||'').match(/^\s*\"?([^\"<]+?)\"?\s*</);if(m&&m[1])return m[1].trim();var e=String(from||'').match(/@([^>\s]+)/);return e?e[1].replace(/^mail\.|^jobs\.|^careers\./,''):String(from||'').slice(0,60)}
  async function gmailFetch(path,opts){if(!accessToken||Date.now()>tokenExpires)throw new Error('Gmail session expired. Reconnect Gmail.');opts=opts||{};opts.headers=Object.assign({},opts.headers||{},{Authorization:'Bearer '+accessToken});var r=await fetch('https://gmail.googleapis.com/gmail/v1/users/me'+path,opts);var data=await r.json().catch(function(){return {}});if(!r.ok)throw new Error((data.error&&data.error.message)||('Gmail API '+r.status));return data}
  async function loadConfig(){var configured='';try{var r=await fetch('/api/google-config',{cache:'no-store'});var j=await r.json();configured=j.clientId||''}catch(e){}var saved=localStorage.getItem('ltp_google_client_id')||'';if(configured){$('ltpGmailMode').textContent='Production client configured · browser-direct Gmail access';$('ltpClientField').classList.add('hidden');return configured}$('ltpGmailMode').textContent='Tester mode · supply your own Google OAuth client ID';$('ltpClientField').classList.remove('hidden');$('ltpGoogleClientId').value=saved;return saved}
  function waitForGIS(){return new Promise(function(resolve,reject){var n=0;(function poll(){if(window.google&&google.accounts&&google.accounts.oauth2)return resolve();if(n++>80)return reject(new Error('Google OAuth library did not load.'));setTimeout(poll,100)})()})}
  async function connect(){try{status('Opening Google consent…');var clientId=await loadConfig();if(!clientId){clientId=$('ltpGoogleClientId').value.trim();if(!clientId)throw new Error('Enter a Google OAuth client ID for tester mode.');localStorage.setItem('ltp_google_client_id',clientId)}await waitForGIS();tokenClient=google.accounts.oauth2.initTokenClient({client_id:clientId,scope:SCOPES,callback:async function(resp){if(resp.error){status(resp.error_description||resp.error,'bad');return}accessToken=resp.access_token||'';tokenExpires=Date.now()+Math.max(60,Number(resp.expires_in||3600)-60)*1000;try{gmailProfile=await gmailFetch('/profile');$('ltpDraftTo').value=$('ltpDraftTo').value||gmailProfile.emailAddress||'';$('ltpScanGmail').disabled=false;$('ltpCreateDraft').disabled=false;$('ltpDisconnectGmail').disabled=false;$('ltpConnectGmail').textContent='Reconnect Gmail';status('Connected: '+(gmailProfile.emailAddress||'Google account')+' · token kept in browser memory','ok');ga('ltp_gmail_connected')}catch(e){status(e.message,'bad')}}});tokenClient.requestAccessToken({prompt:'consent'})}catch(e){status(e.message,'bad')}}
  function disconnect(){try{if(accessToken&&window.google&&google.accounts&&google.accounts.oauth2)google.accounts.oauth2.revoke(accessToken,function(){})}catch(e){}accessToken='';tokenExpires=0;gmailProfile=null;evidence=[];$('ltpScanGmail').disabled=true;$('ltpCreateDraft').disabled=true;$('ltpDisconnectGmail').disabled=true;$('ltpImportEvidence').disabled=true;status('Disconnected.','');renderEvidence();ga('ltp_gmail_disconnected')}
  async function scan(){try{$('ltpScanGmail').disabled=true;$('ltpEvidenceSummary').textContent='Scanning Gmail metadata and snippets in this browser…';var days=parseInt($('ltpScanDays').value,10)||90;var max=parseInt($('ltpMaxMessages').value,10)||80;var q='newer_than:'+days+'d {"thank you for applying" "thanks for applying" "application received" "we received your application" interview recruiter "hiring manager" "next step" unfortunately "not moving forward" "on hold" pause}';var list=await gmailFetch('/messages?maxResults='+max+'&q='+encodeURIComponent(q));var ids=(list.messages||[]).slice(0,max);var rows=[];for(var i=0;i<ids.length;i+=8){var batch=ids.slice(i,i+8);var chunk=await Promise.all(batch.map(function(x){return gmailFetch('/messages/'+encodeURIComponent(x.id)+'?format=metadata&metadataHeaders=Subject&metadataHeaders=From&metadataHeaders=Date')}));rows=rows.concat(chunk)}evidence=rows.map(function(m){var h=headersOf(m.payload);var text=(h.subject||'')+' '+(m.snippet||'');return {id:m.id,subject:h.subject||'(no subject)',from:h.from||'',date:h.date||'',snippet:m.snippet||'',status:classify(text),source:'Gmail',observed_at:new Date().toISOString(),verification_state:'verified'}}).filter(function(x){return x.status!=='other'});renderEvidence();$('ltpImportEvidence').disabled=!evidence.length;$('ltpEvidenceSummary').textContent='Scanned '+ids.length+' candidate messages; '+evidence.length+' matched the evidence classifier. Raw content remains in this browser session.';ga('ltp_gmail_scan',{messages_scanned:ids.length,evidence_items:evidence.length,days:days})}catch(e){$('ltpEvidenceSummary').textContent='Scan failed: '+e.message}finally{$('ltpScanGmail').disabled=false}}
  function renderEvidence(){var counts={applied:0,interview:0,closed:0,paused:0,network:0};evidence.forEach(function(x){counts[x.status]=(counts[x.status]||0)+1});$('ltpAppliedCount').textContent=counts.applied||0;$('ltpInterviewCount').textContent=counts.interview||0;$('ltpClosedCount').textContent=counts.closed||0;var el=$('ltpEvidenceList');if(!evidence.length){el.innerHTML='<div>No Gmail evidence scanned yet.</div>';return}el.innerHTML=evidence.slice(0,40).map(function(x){return '<div><strong style="color:#dff7ff">'+esc(x.status.toUpperCase())+'</strong> · '+esc(x.subject)+'<br><span class="subtle">'+esc(displaySender(x.from))+' · '+esc(x.date)+'</span></div>'}).join('')}
  function importEvidence(){if(!evidence.length)return;var counts={};evidence.forEach(function(x){counts[x.status]=(counts[x.status]||0)+1});var summary=['Gmail evidence audit: '+evidence.length+' verified message signals in the selected window.','Application receipts: '+(counts.applied||0)+' · interview/next-step signals: '+(counts.interview||0)+' · paused: '+(counts.paused||0)+' · closed/rejection signals: '+(counts.closed||0)+'.','Gmail evidence is source-verified but still requires company-role deduplication before being treated as a cumulative funnel count.'];var s=$('summaryNotes');if(s)s.value=[s.value.trim(),summary.join('\n')].filter(Boolean).join('\n');var rows=evidence.filter(function(x){return x.status==='interview'||x.status==='paused'||x.status==='closed'}).slice(0,20).map(function(x){return [displaySender(x.from),'Gmail evidence',x.status,'Reconcile against company-role process','verified',x.subject.replace(/\|/g,'/')].join(' | ')});var o=$('opportunities');if(o&&rows.length)o.value=[o.value.trim(),rows.join('\n')].filter(Boolean).join('\n');var h=$('headline');if(h&&!h.value.trim())h.value='Gmail evidence reconciled · ASTRO brief ready for review';location.hash='#briefs';ga('ltp_gmail_import',{evidence_items:evidence.length})}
  window.LandThePlaneGmail={gmailFetch:gmailFetch,getProfile:function(){return gmailProfile},hasAccess:function(){return Boolean(accessToken&&Date.now()<tokenExpires)}};
  async function init(){await loadConfig();$('ltpConnectGmail').addEventListener('click',connect);$('ltpDisconnectGmail').addEventListener('click',disconnect);$('ltpScanGmail').addEventListener('click',scan);$('ltpImportEvidence').addEventListener('click',importEvidence);$('ltpGoogleClientId').addEventListener('change',function(){localStorage.setItem('ltp_google_client_id',this.value.trim())});ga('ltp_gmail_mvp_view')}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
`;
