export const genesysDataBlock=String.raw`
const CUSTOMER={id:"northstar-retail-synthetic",name:"Northstar Retail Group (Synthetic)",nameStatus:"Golden example account · synthetic",industry:"Retail",stage:"Value realization",scope:"Cloud CX platform; digital; workforce engagement; AI-assisted service",systems:"CRM; identity; telephony; digital channels; analytics",goal:"Improve customer experience and agent effectiveness while reducing avoidable service friction.",metrics:"Synthetic targets: +8 CSAT points; -12% AHT; 85% priority-feature adoption; 3 approved value stories",timeline:"Synthetic 2-quarter success plan",currentState:"Synthetic account. Adoption is broad, but value evidence and executive alignment vary by workstream.",dependency:"Normalize KPI definitions and confirm executive owners before the next business review."};
const SEED=[
["handoff","synthetic_sample",{title:"Customer business priorities",value:"Improve customer experience and agent effectiveness while reducing avoidable service friction.",validation:"Synthetic sample",note:"Translate the executive objective into measurable CX and operational outcomes."}],
["handoff","synthetic_sample",{title:"Cross-functional operating map",value:"Customer Success + Sales + Onboarding + Professional Services + Renewals + Product + Support + Engineering",validation:"Synthetic sample",note:"Keep one accountable owner and one next decision per dependency."}],
["kpi","synthetic_sample",{name:"Customer satisfaction",hypothesis:"Higher-quality journeys and agent support should improve customer satisfaction when adoption is sustained.",baseline:"Synthetic baseline 72",target:"80+",metricDefinition:"Customer-approved CSAT definition",sourceSystem:"Synthetic CX analytics",owner:"Customer Success + customer CX leader",cadence:"Monthly",calculation:"Customer-approved method",currentValue:"77",realizedValue:"Not yet approved",approval:"Synthetic sample"}],
["kpi","synthetic_sample",{name:"Average handle time",hypothesis:"Better routing, workflow, and agent assistance can reduce avoidable handle time without sacrificing quality.",baseline:"Synthetic baseline 610 seconds",target:"<540 seconds",metricDefinition:"Customer-approved AHT definition",sourceSystem:"Synthetic contact-center analytics",owner:"Customer Success + operations leader",cadence:"Monthly",calculation:"Customer-approved method",currentValue:"565 seconds",realizedValue:"Not yet approved",approval:"Synthetic sample"}],
["kpi","synthetic_sample",{name:"Priority feature adoption",hypothesis:"Sustained usage of agreed capabilities is required before value claims are credible.",baseline:"Synthetic baseline 54%",target:"85%+",metricDefinition:"Active target users or workflows using agreed priority capabilities",sourceSystem:"Synthetic adoption ledger",owner:"Customer Success + platform owner",cadence:"Weekly",calculation:"Active / target cohort",currentValue:"78%",realizedValue:"Not applicable",approval:"Synthetic sample"}],
["risk","synthetic_sample",{title:"Executive KPI definitions are not fully normalized",impact:"Business reviews could mix activity and outcome signals and weaken the value narrative.",owner:"Customer Success + customer CX leader",mitigation:"Agree metric definitions, data sources, baselines, owners, and approval criteria before the EBR.",escalationStatus:"Open",nextDecision:"Approve the KPI measurement contract."}],
["risk","synthetic_sample",{title:"Two business units trail on priority-feature adoption",impact:"Uneven adoption may reduce realized value and create renewal or expansion risk.",owner:"Customer Success + adoption champions",mitigation:"Segment usage by cohort, identify friction, run targeted enablement, and remeasure.",escalationStatus:"Open",nextDecision:"Select intervention owners and checkpoint date."}],
["stakeholder","synthetic_sample",{name:"Jordan Lee (Synthetic)",role:"Chief Customer Officer",organization:"Northstar Retail Group (Synthetic)",email:"",phone:"",decisionRole:"Executive sponsor, customer outcomes, investment narrative",status:"Active",notes:"Owns executive outcome review."}],
["stakeholder","synthetic_sample",{name:"Maya Chen (Synthetic)",role:"VP, Contact Center Operations",organization:"Northstar Retail Group (Synthetic)",email:"",phone:"",decisionRole:"Operational adoption and KPI owner",status:"Active",notes:"Owns adoption and operational outcomes."}],
["stakeholder","synthetic_sample",{name:"Rafael Ortiz (Synthetic)",role:"Director, CX Technology",organization:"Northstar Retail Group (Synthetic)",email:"",phone:"",decisionRole:"Technical platform and integration owner",status:"Active",notes:"Coordinates technical dependencies."}],
["action","synthetic_sample",{title:"Approve KPI measurement contract before executive review",owner:"Customer Success + customer CX leader",due:"Week 10",status:"In Progress",audience:"Customer / Internal"}],
["action","synthetic_sample",{title:"Run targeted adoption intervention for two trailing business units",owner:"Customer Success + adoption champions",due:"Week 10",status:"Planned",audience:"Customer / Internal"}],
["action","synthetic_sample",{title:"Validate two retention/expansion hypotheses against approved value evidence",owner:"Customer Success + Sales",due:"Week 11",status:"Planned",audience:"Internal"}],
["meeting","synthetic_sample",{title:"Executive business review",type:"EBR",date:"Week 12",attendees:"Chief Customer Officer; Contact Center Operations; CX Technology; Sales; Customer Success",objective:"Review outcomes, adoption, open risk, evidence quality, and next-quarter decisions.",notes:"Synthetic candidate-demo meeting."}],
["call_prep","internal_proposal",{title:"Executive business review",meetingDate:"Week 12",meetingType:"EBR",objective:"Connect adoption and platform progress to customer-approved outcomes, resolve open risk, and leave with explicit decisions on retention and expansion priorities.",attendees:"Chief Customer Officer; Contact Center Operations; CX Technology; Sales; Customer Success",opening:"Start with the customer's business outcomes and decisions required, then use adoption and platform data only as evidence toward those outcomes.",currentState:"Synthetic CSAT is 77 against an 80+ target. AHT is 565 seconds against a <540 target. Priority-feature adoption is 78% against an 85% target. Two business units trail the portfolio.",evidenceReady:"Synthetic CX analytics; adoption cohort view; KPI measurement contract; open risk list; expansion hypothesis scorecard.",questions:"Which outcomes are ready to approve as realized value? Which adoption gap matters most to the executive objective? Which risk needs cross-functional escalation? Which expansion hypothesis has enough evidence to advance?",decisions:"Approve KPI contract; assign adoption intervention owners; resolve escalation path; approve or defer expansion hypotheses.",escalationCriteria:"Do not claim realized value without an agreed baseline, metric definition, source, method, owner, and customer approval.",followUp:"Publish decisions, owners, due dates, evidence gaps, and the next executive checkpoint.",technologyNotes:"Keep platform activity, adoption, operational outcomes, and business value as separate evidence layers.",assistantNotes:"Use only public Genesys role context plus synthetic account state. Never imply access to private Genesys customer data, internal roadmap commitments, or real customer outcomes."}],
["assistant_profile","template",{title:"Genesys Customer Success Director operating playbook",playbook:"CUSTOMER SUCCESS DIRECTOR BASELINE\n- Begin with customer business objectives and the executive decision that matters.\n- Convert objectives into measurable success plans with owners, milestones, evidence sources, and review cadence.\n- Separate platform activity from adoption and adoption from realized value.\n- Surface risk early and pair each risk with an owner, mitigation, escalation rule, and next decision.\n- Orchestrate Sales, Onboarding, Professional Services, Renewals, Product, Support, and Engineering around customer outcomes.\n- Use executive business reviews to drive decisions, not recite activity.\n- Tie retention and expansion to verified customer value rather than unsupported optimism.\n- Earn advocacy and referenceability only after evidence is credible and customer-approved.\n- Balance high-touch strategic work with reusable portfolio playbooks.",participants:"",updatedFrom:"Public Genesys Customer Success Director role context + synthetic operating model"}],
["raci","template",{title:"Enterprise Customer Success RACI",rows:[],roles:["Executive Sponsor","CX Operations","CX Technology","Customer Success","Sales","Onboarding / PS","Renewals","Product / Support / Engineering"],note:"Template. Assign real names and decision rights during discovery."}],
["jira_config","internal_record",{siteUrl:"",deploymentBoardId:"",issueBoardId:"",projectKey:"",deploymentIssueType:"",issueType:"",connection:"Not connected",mode:"Optional governed work-system bridge"}]
];
const KB_SEED=[
{id:"kb-gns-value",slug:"adoption-to-value",title:"From Adoption to Customer Value",summary:"A compact model for separating activity, adoption, operational outcomes, and customer-approved value.",category:"Customer Success",tags:["adoption","value","retention","expansion"],status:"published",source:"internal_best_practice",authorLabel:"Candidate operating model",body:"ACTIVITY IS NOT ADOPTION\nLogin counts, launches, and configuration changes do not prove sustained use.\n\nADOPTION IS NOT VALUE\nTrack repeat usage and workflow penetration separately from business outcomes.\n\nVALUE NEEDS A MEASUREMENT CONTRACT\nFor every outcome record the baseline, metric definition, source, method, owner, and customer approval.\n\nRISK NEEDS AN OWNER\nEvery meaningful risk needs a mitigation, escalation rule, next decision, and checkpoint.\n\nEXPANSION SHOULD FOLLOW PROOF\nAdvance expansion when the customer has verified value, readiness, sponsorship, and an evidence path."}
];
`;
