#!/usr/bin/env python3
"""Quillgeist Lite retro DOS boot splash.

Standard-library only. It displays the deterministic Clintware neon/ASCII eclipse
boot artwork generated by terminal_repair.py. Failure is non-fatal so qq always boots.
"""

from __future__ import annotations

import importlib.util
import os
import pathlib
import sys
import time

VERSION = "2026.09.24.6"

def load_generator(repair_path: pathlib.Path):
    spec = importlib.util.spec_from_file_location("qq_terminal_repair", repair_path)
    if not spec or not spec.loader:
        return None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module

def main() -> int:
    if os.name != "nt":
        return 0

    local = pathlib.Path(os.environ.get("LOCALAPPDATA", ""))
    if not local:
        return 0

    home = local / "Clintware" / "QuillgeistLite"
    repair = home / "terminal_repair.py"
    image_path = home / "clintware-boot-70s-dos.png"

    try:
        if (not image_path.exists() or image_path.stat().st_size < 20000) and repair.exists():
            module = load_generator(repair)
            if module and hasattr(module, "generate_boot_image"):
                module.generate_boot_image(image_path)
    except Exception:
        pass

    try:
        import tkinter as tk

        root = tk.Tk()
        root.configure(bg="black")
        root.overrideredirect(True)
        root.attributes("-topmost", True)

        sw = root.winfo_screenwidth()
        sh = root.winfo_screenheight()
        ww = min(1280, max(760, int(sw * 0.72)))
        wh = min(900, max(520, int(sh * 0.78)))
        x = max(0, (sw - ww) // 2)
        y = max(0, (sh - wh) // 2)
        root.geometry(f"{ww}x{wh}+{x}+{y}")

        frame = tk.Frame(root, bg="black")
        frame.pack(fill="both", expand=True)

        photo = None
        if image_path.exists():
            try:
                photo = tk.PhotoImage(file=str(image_path))
            except Exception:
                photo = None

        if photo is not None:
            # Integer subsampling keeps the pixel/ASCII rendering sharp instead
            # of smoothing it into a conventional image.
            factor = max(1, max(photo.width() // max(1, ww - 40), photo.height() // max(1, wh - 40)))
            shown = photo.subsample(factor, factor) if factor > 1 else photo
            label = tk.Label(frame, image=shown, bg="black", borderwidth=0, highlightthickness=0)
            label.image = shown
            label.pack(expand=True)
        else:
            label = tk.Label(
                frame,
                text="CLINTWARE™\n\nQUILLGEIST LITE\nEST. 2026",
                fg="#EAF7FF",
                bg="black",
                font=("Cascadia Mono", 30, "bold"),
                justify="center",
            )
            label.pack(expand=True)

        root.after(1450, root.destroy)
        root.bind("<Escape>", lambda _e: root.destroy())
        root.bind("<Button-1>", lambda _e: root.destroy())
        root.mainloop()
    except Exception:
        # Splash is cosmetic; qq's runner must never depend on GUI support.
        time.sleep(0.15)

    return 0

if __name__ == "__main__":
    raise SystemExit(main())
