const H={"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-robots-tag":"noindex, nofollow"};
const j=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const ts=()=>new Date().toISOString();
const CUSTOMER={id:"healthcare-device-manufacturer",name:"Healthcare Device Manufacturer",nameStatus:"Name not provided",industry:"Healthcare device manufacturing",stage:"Implementation",week:1,provenance:"customer_provided",facts:{users:"500+ field technicians",product:"Neuron7 Intelligent Search",committedTimeline:"6–8 weeks from start to go-live",roiTarget:"Improve cycle time for resolution by 50% by end of Year 1",kickoff:"Week 1; kickoff and discovery calls completed",sap:"SAP connector not ready; Engineering initial estimate up to 8–10 weeks",sapRequirement:"Must-have for go-live because product manuals are maintained in SAP",sso:"Single sign-on included for N7 and SFDC/SAP"}};
const SEED=[
["handoff","customer_provided",{title:"Contracted scope",value:"Neuron7 Intelligent Search licenses for search across multiple internal data-source platforms",validation:"Partially validated",note:"Salesforce connector is ready; SAP connector is not ready."}],
["handoff","customer_provided",{title:"Promised implementation timeline",value:"6–8 weeks from start to go-live",validation:"At risk",note:"SAP is required for go-live and its connector estimate is up to 8–10 weeks."}],
["handoff","customer_provided",{title:"Business case / expected ROI",value:"Improve cycle time for resolution by 50% by end of Year 1",validation:"Target provided; baseline not provided",note:"No monetary value claimed."}],
["integration","customer_provided",{name:"Salesforce Service Cloud",purpose:"Call-center agents; KB articles, technical bulletins and job aids; work-order tracking",connectorStatus:"Ready",technicalValidation:"Active SFDC connector ready to go"}],
["integration","customer_provided",{name:"Salesforce Field Service",purpose:"Field technicians and parts ordering",connectorStatus:"Existing system",technicalValidation:"Connector detail not separately provided"}],
["integration","customer_provided",{name:"SAP",purpose:"Back-office and product manuals",connectorStatus:"Not ready",technicalValidation:"Engineering estimate up to 8–10 weeks"}],
["integration","customer_provided",{name:"Single sign-on",purpose:"Authentication between N7 and SFDC/SAP",connectorStatus:"Included",technicalValidation:"Implementation detail not provided"}],
["milestone","customer_provided",{title:"Kickoff and discovery",owner:"Not provided",due:"Week 1",status:"Completed",dependencies:"None provided"}],
["risk","customer_provided",{title:"SAP connector timeline conflicts with committed go-live window",impact:"Full go-live is at risk because SAP manuals are required.",owner:"Role not yet assigned",mitigation:"To be decided",escalationStatus:"Open",nextDecision:"Not provided"}],
["kpi","customer_provided",{name:"Resolution cycle time",hypothesis:"Faster access to the right content should reduce resolution cycle time and phone calls.",baseline:"",target:"50% improvement by end of Year 1",metricDefinition:"",sourceSystem:"",owner:"",cadence:"",calculation:"",currentValue:"",realizedValue:"",approval:"Not yet defined"}],
["proposed_plan","internal_proposal",{title:"Integrated delivery plan",summary:"Protect the SAP critical path while moving independent Salesforce, baseline, training, validation and readiness work in parallel.",planningBoundary:"12-week internal planning view",source:"Neuron7_Case_Study_Clinton_Kosh.pdf"}],
["document","customer_provided",{name:"CS-Case Study[86][16].pdf",classification:"Authoritative case source",binaryStatus:"Needs local re-upload",approvedForBriefs:"Yes"}],
["document","internal_record",{name:"Neuron7_Case_Study_Clinton_Kosh.pdf",classification:"User-authored internal plan / design source",binaryStatus:"Needs local re-upload",approvedForBriefs:"Yes"}]
];
export class N7CRM{
 constructor(ctx){this.ctx=ctx;this.sql=ctx.storage.sql;this.sql.exec("CREATE TABLE IF NOT EXISTS customers(id TEXT PRIMARY KEY,data TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)");this.sql.exec("CREATE TABLE IF NOT EXISTS records(id TEXT PRIMARY KEY,customer_id TEXT NOT NULL,type TEXT NOT NULL,provenance TEXT NOT NULL,data TEXT NOT NULL,archived INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)");this.ctx.blockConcurrencyWhile(()=>this.seed())}
 async seed(){if([...this.sql.exec("SELECT id FROM customers WHERE id=?",CUSTOMER.id)].length)return;const t=ts();this.sql.exec("INSERT INTO customers VALUES(?,?,?,?)",CUSTOMER.id,JSON.stringify(CUSTOMER),t,t);for(const [type,p,data] of SEED){this.sql.exec("INSERT INTO records VALUES(?,?,?,?,?,0,?,?)",crypto.randomUUID(),CUSTOMER.id,type,p,JSON.stringify(data),t,t)}}
 row(r){return{id:r.id,customerId:r.customer_id,type:r.type,provenance:r.provenance,data:JSON.parse(r.data),createdAt:r.created_at,updatedAt:r.updated_at}}
 async fetch(req){const u=new URL(req.url),p=u.pathname,m=req.method;
  if(m==="GET"&&p==="/state"){const customers=[...this.sql.exec("SELECT * FROM customers ORDER BY created_at")].map(r=>JSON.parse(r.data));const id=u.searchParams.get("customer")||CUSTOMER.id;const c=customers.find(x=>x.id===id)||customers[0];if(!c)return j({error:"No customer"},404);const records=[...this.sql.exec("SELECT * FROM records WHERE customer_id=? AND archived=0 ORDER BY created_at",c.id)].map(r=>this.row(r));return j({customer:c,customers,records})}
  if(m==="POST"&&p==="/customers"){const b=await req.json(),id=crypto.randomUUID(),t=ts(),c={id,name:String(b.name||"New Customer"),nameStatus:b.name?"User-entered":"Name not provided",industry:String(b.industry||""),stage:"Onboarding",week:null,provenance:"internal_record",facts:{}};this.sql.exec("INSERT INTO customers VALUES(?,?,?,?)",id,JSON.stringify(c),t,t);return j({customer:c},201)}
  if(m==="POST"&&p==="/records"){const b=await req.json(),id=crypto.randomUUID(),t=ts(),pv=String(b.provenance||"internal_record");this.sql.exec("INSERT INTO records VALUES(?,?,?,?,?,0,?,?)",id,String(b.customerId),String(b.type),pv,JSON.stringify(b.data||{}),t,t);return j({id},201)}
  const mm=p.match(/^\/records\/([^/]+)$/);if(mm&&m==="PATCH"){const b=await req.json(),rows=[...this.sql.exec("SELECT * FROM records WHERE id=?",mm[1])];if(!rows.length)return j({error:"Not found"},404);const old=this.row(rows[0]);this.sql.exec("UPDATE records SET data=?,provenance=?,updated_at=? WHERE id=?",JSON.stringify({...old.data,...(b.data||{})}),b.provenance||old.provenance,ts(),mm[1]);return j({ok:true})}if(mm&&m==="DELETE"){this.sql.exec("UPDATE records SET archived=1,updated_at=? WHERE id=?",ts(),mm[1]);return j({ok:true})}
  if(m==="POST"&&p==="/import"){const b=await req.json(),ids=[];for(const f of (b.facts||[])){const id=crypto.randomUUID(),t=ts(),d={...(f.data||{}),importSource:b.sourceName||"Uploaded source",sourceSnippet:f.sourceSnippet||""};this.sql.exec("INSERT INTO records VALUES(?,?,?,?,?,0,?,?)",id,String(b.customerId),String(f.type||"note"),"customer_provided",JSON.stringify(d),t,t);ids.push(id)}return j({inserted:ids},201)}
  return j({error:"Not found"},404)
 }
}
export default{async fetch(req,env){const u=new URL(req.url);if(u.pathname==="/health")return j({ok:true,service:"clintware-n7demo-crm",canonicalUrl:"https://n7demo.clintware.com",storage:"Durable Objects SQLite",lovable:false});if(u.pathname.startsWith("/api/")){const id=env.CRM.idFromName("n7demo-main"),stub=env.CRM.get(id),x=new URL(req.url);x.pathname=x.pathname.replace(/^\/api/,"")||"/";return stub.fetch(new Request(x,req))}const r=await env.ASSETS.fetch(req),h=new Headers(r.headers);h.set("x-robots-tag","noindex, nofollow");h.set("x-content-type-options","nosniff");h.set("referrer-policy","strict-origin-when-cross-origin");h.set("permissions-policy","camera=(), microphone=(), geolocation=()");return new Response(r.body,{status:r.status,statusText:r.statusText,headers:h})}}
