const GA4_ID="G-DCY144YM9P";
const AUTH_ORIGIN="https://auth.clintware.com";
const AUTH_CONFIG_URL=AUTH_ORIGIN+"/client-config/n7demo-crm";
const APP_ID="n7demo-crm";
const REQUIRED_CONTEXT="n7demo-crm:read";
const OWNER_EMAILS=new Set(["clint.kosh@gmail.com"]);
const COMPANY_DOMAIN="neuron7.ai";
const WORKSPACE_ID="n7demo-neuron7";
const TX_COOKIE="__Host-n7demo-auth-tx";
const SESSION_COOKIE="__Host-n7demo-session";
const te=new TextEncoder();
const H={"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-robots-tag":"noindex, nofollow"};
const j=(x,s=200,extra={})=>new Response(JSON.stringify(x),{status:s,headers:{...H,...extra}});
const ts=()=>new Date().toISOString();
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function cookie(req,name){for(const p of (req.headers.get("cookie")||"").split(";")){const i=p.indexOf("=");if(i>0&&p.slice(0,i).trim()===name)return decodeURIComponent(p.slice(i+1).trim())}return""}
function setCookie(name,value,maxAge){return name+"="+encodeURIComponent(value)+"; Path=/; Secure; HttpOnly; SameSite=Lax; Max-Age="+maxAge}
function clearCookie(name){return name+"=; Path=/; Secure; HttpOnly; SameSite=Lax; Max-Age=0"}
function rand(n=32){const a=new Uint8Array(n);crypto.getRandomValues(a);let b="";for(const x of a)b+=String.fromCharCode(x);return btoa(b).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
async function pkce(v){const d=await crypto.subtle.digest("SHA-256",te.encode(v));let b="";for(const x of new Uint8Array(d))b+=String.fromCharCode(x);return btoa(b).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function secureHeaders(h=new Headers()){h.set("x-robots-tag","noindex, nofollow, noarchive");h.set("x-content-type-options","nosniff");h.set("referrer-policy","no-referrer");h.set("cache-control","no-store");h.set("permissions-policy","camera=(), microphone=(), geolocation=()");h.set("content-security-policy","default-src 'self'; style-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com; img-src 'self' data: blob: https://www.google-analytics.com; connect-src 'self' https://www.google-analytics.com https://region1.google-analytics.com; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self' https://auth.clintware.com");return h}
function html(body,status=200,extra={}){return new Response(body,{status,headers:secureHeaders(new Headers({"content-type":"text/html; charset=utf-8",...extra}))})}
async function authConfig(){const r=await fetch(AUTH_CONFIG_URL,{headers:{accept:"application/json"}});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||"clintware_identity_unavailable");return x}
function userAllowed(u){if(!u?.sub||u.email_verified!==true||u.application!==APP_ID)return false;const ctx=Array.isArray(u.application_context)?u.application_context:[];if(!ctx.includes(REQUIRED_CONTEXT))return false;const email=String(u.email||"").toLowerCase();const domain=email.includes("@")?email.split("@").pop():"";return domain===COMPANY_DOMAIN||OWNER_EMAILS.has(email)}
function loginPage(){return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>N7 Demo CRM</title><script async src="https://www.googletagmanager.com/gtag/js?id=G-DCY144YM9P"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','G-DCY144YM9P',{anonymize_ip:true});</script><style>body{margin:0;background:#07101d;color:#eef6ff;font:16px/1.5 system-ui}.wrap{max-width:760px;margin:10vh auto;padding:24px}.card{background:#0d1928;border:1px solid #20364f;border-radius:16px;padding:30px}a{display:inline-block;margin-top:14px;padding:11px 16px;border-radius:9px;background:linear-gradient(135deg,#3f7cff,#43d8e6);color:#06111b;font-weight:800;text-decoration:none}.muted{color:#8fa5bd}</style></head><body><div class="wrap"><div class="card"><div class="muted">CLINTWARE IDENTITY</div><h1>N7 Demo CRM</h1><p>Persistent Customer Implementation + ROI workspace. Sign in through Clintware Identity to load your team account.</p><a href="/auth/login">Sign in</a></div></div></body></html>`}
async function startLogin(){const cfg=await authConfig(),state=rand(24),verifier=rand(48),challenge=await pkce(verifier),u=new URL(cfg.authorization_endpoint);u.searchParams.set("response_type","code");u.searchParams.set("client_id",cfg.client_id);u.searchParams.set("redirect_uri",cfg.redirect_uri);u.searchParams.set("scope",(cfg.scopes||["identity","email","profile"]).join(" "));u.searchParams.set("state",state);u.searchParams.set("code_challenge",challenge);u.searchParams.set("code_challenge_method","S256");u.searchParams.set("resource",cfg.resource);const h=secureHeaders(new Headers({location:u.toString(),"set-cookie":setCookie(TX_COOKIE,state+"."+verifier,600)}));return new Response(null,{status:302,headers:h})}
async function refreshTokens(session){if(!session.refreshToken)return null;const cfg=await authConfig();const r=await fetch(cfg.token_endpoint,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded",accept:"application/json"},body:new URLSearchParams({grant_type:"refresh_token",client_id:cfg.client_id,refresh_token:session.refreshToken})});const t=await r.json().catch(()=>({}));if(!r.ok||!t.access_token)return null;return {accessToken:t.access_token,refreshToken:t.refresh_token||session.refreshToken,expiresAt:Date.now()+Number(t.expires_in||900)*1000}}
async function userInfo(accessToken){const cfg=await authConfig();const r=await fetch(cfg.userinfo_endpoint,{headers:{authorization:"Bearer "+accessToken,accept:"application/json"}});if(!r.ok)return null;return r.json()}
const CUSTOMER={id:"healthcare-device-manufacturer",name:"Healthcare Device Manufacturer",nameStatus:"Name not provided",industry:"Healthcare device manufacturing",stage:"Implementation",week:1,provenance:"customer_provided",facts:{users:"500+ field technicians",product:"Neuron7 Intelligent Search",committedTimeline:"6–8 weeks from start to go-live",roiTarget:"Improve cycle time for resolution by 50% by end of Year 1",kickoff:"Week 1; kickoff and discovery calls completed",sap:"SAP connector not ready; Engineering initial estimate up to 8–10 weeks",sapRequirement:"Must-have for go-live because product manuals are maintained in SAP",sso:"Single sign-on included for N7 and SFDC/SAP"}};
const SEED=[
["handoff","customer_provided",{title:"Contracted scope",value:"Neuron7 Intelligent Search licenses for search across multiple internal data-source platforms",validation:"Partially validated",note:"Salesforce connector is ready; SAP connector is not ready."}],
["handoff","customer_provided",{title:"Promised implementation timeline",value:"6–8 weeks from start to go-live",validation:"At risk",note:"SAP is required for go-live and its connector estimate is up to 8–10 weeks."}],
["handoff","customer_provided",{title:"Business case / expected ROI",value:"Improve cycle time for resolution by 50% by end of Year 1",validation:"Target provided; baseline not provided",note:"No monetary value claimed."}],
["integration","customer_provided",{name:"Salesforce Service Cloud",purpose:"Call-center agents; KB articles, technical bulletins and job aids; work-order tracking",connectorStatus:"Ready",technicalValidation:"Active SFDC connector ready to go"}],
["integration","customer_provided",{name:"Salesforce Field Service",purpose:"Field technicians and parts ordering",connectorStatus:"Existing system",technicalValidation:"Connector detail not separately provided"}],
["integration","customer_provided",{name:"SAP",purpose:"Back-office and product manuals",connectorStatus:"Not ready",technicalValidation:"Engineering estimate up to 8–10 weeks"}],
["integration","customer_provided",{name:"Single sign-on",purpose:"Authentication between N7 and SFDC/SAP",connectorStatus:"Included",technicalValidation:"Implementation detail not provided"}],
["milestone","customer_provided",{title:"Kickoff and discovery",owner:"Not provided",due:"Week 1",status:"Completed",dependencies:"None provided"}],
["risk","customer_provided",{title:"SAP connector timeline conflicts with committed go-live window",impact:"Full go-live is at risk because SAP manuals are required.",owner:"Role not yet assigned",mitigation:"To be decided",escalationStatus:"Open",nextDecision:"Not provided"}],
["kpi","customer_provided",{name:"Resolution cycle time",hypothesis:"Faster access to the right content should reduce resolution cycle time and phone calls.",baseline:"",target:"50% improvement by end of Year 1",metricDefinition:"",sourceSystem:"",owner:"",cadence:"",calculation:"",currentValue:"",realizedValue:"",approval:"Not yet defined"}],
["proposed_plan","internal_proposal",{title:"Integrated delivery plan",summary:"Protect the SAP critical path while moving independent Salesforce, baseline, training, validation and readiness work in parallel.",planningBoundary:"12-week internal planning view",source:"Neuron7_Case_Study_Clinton_Kosh.pdf"}],
["document","customer_provided",{name:"CS-Case Study[86][16].pdf",classification:"Authoritative case source",binaryStatus:"Needs local re-upload",approvedForBriefs:"Yes"}],
["document","internal_record",{name:"Neuron7_Case_Study_Clinton_Kosh.pdf",classification:"User-authored internal plan / design source",binaryStatus:"Needs local re-upload",approvedForBriefs:"Yes"}],
["raci","template",{title:"Implementation RACI",rows:[],roles:["Customer","Customer Success / Implementation","Engineering","Product","Support","Sales"],note:"Template only. Assign responsibilities explicitly; no customer names are assumed."}],
["deployment_card","customer_provided",{title:"Kickoff & discovery",column:"Done",stageOrder:1,sprint:"Week 1",jiraKey:"",jiraUrl:"",source:"Official case"}],
["deployment_card","customer_provided",{title:"Salesforce connector",column:"Ready",stageOrder:2,sprint:"Weeks 1–2",jiraKey:"",jiraUrl:"",source:"Official case"}],
["deployment_card","customer_provided",{title:"SAP connector",column:"Blocked",stageOrder:3,sprint:"Weeks 1–10",jiraKey:"",jiraUrl:"",source:"Official case"}],
["deployment_card","internal_proposal",{title:"Go-live readiness",column:"Planned",stageOrder:4,sprint:"Weeks 8–12",jiraKey:"",jiraUrl:"",source:"Internal proposed plan"}],
["sprint","internal_proposal",{name:"Sprint 1",weeks:"Weeks 1–2",goal:"Discovery, technical validation, Salesforce path, SAP dependency framing",planned:4,completed:1}],
["sprint","internal_proposal",{name:"Sprint 2",weeks:"Weeks 3–4",goal:"Parallel content, measurement baseline, configuration and enablement preparation",planned:4,completed:0}],
["sprint","internal_proposal",{name:"Sprint 3",weeks:"Weeks 5–6",goal:"Validation, training preparation, UAT readiness and risk retirement",planned:4,completed:0}],
["sprint","internal_proposal",{name:"Sprint 4",weeks:"Weeks 7–8",goal:"UAT / readiness against the original commercial window",planned:4,completed:0}],
["sprint","internal_proposal",{name:"Sprint 5",weeks:"Weeks 9–10",goal:"SAP connector acceptance path and go-live decision",planned:3,completed:0}],
["sprint","internal_proposal",{name:"Sprint 6",weeks:"Weeks 11–12",goal:"Contingency stabilization / hypercare only if required",planned:2,completed:0}],
["jira_config","internal_record",{siteUrl:"",deploymentBoardId:"",issueBoardId:"",projectKey:"",connection:"Not connected",mode:"Clintware Control Plane adapter"}]
];

const KB_SEED=[
{
 id:"kb-ramping-implementation-manager",
 slug:"ramping-a-new-implementation-manager",
 title:"Ramping a New Implementation Manager",
 summary:"A practical 30/60/90-day path that turns one person's ramp into a reusable path for the next implementation manager.",
 category:"Team Enablement",
 tags:["onboarding","implementation","ramp","enablement"],
 status:"published",
 source:"internal_best_practice",
 authorLabel:"Implementation Team",
 body:"PURPOSE\nRamp new Implementation Managers quickly without relying on tribal knowledge. Every person who ramps should leave the path clearer for the next person.\n\nFIRST 30 DAYS — LEARN THE SYSTEM\n• Get product, CRM, Jira, support, documentation, identity, and reporting access.\n• Read several completed implementations from handoff through go-live and renewal follow-through.\n• Shadow a sales-to-CS handoff, kickoff, weekly implementation review, escalation, and executive review.\n• Map the implementation lifecycle: promise → validation → milestones → dependencies → go-live → adoption → ROI.\n• Learn where customer facts live and how internal proposals are kept separate from customer commitments.\n• Practice creating an engineering-ready issue packet before involving Engineering.\n\nDAYS 31–60 — CO-OWN THE WORK\n• Co-run kickoff and weekly implementation reviews.\n• Maintain milestones, RACI, risks, decisions, customer actions, and internal actions in the CRM.\n• Track deployment work in Jira without duplicating Jira inside the CRM.\n• Establish the customer's measurement baseline before making ROI claims.\n• Generate the pre-meeting brief and verify that every status statement is supported by current records.\n• Complete one retrospective and contribute at least one reusable lesson to this KB.\n\nDAYS 61–90 — OWN AND IMPROVE\n• Own an implementation from meeting preparation through follow-up.\n• Escalate early when a required dependency threatens the committed timeline.\n• Keep stakeholders aligned around the next decision, owner, and date.\n• Measure adoption and realized value using agreed definitions and source systems.\n• Identify one repeatable friction point and improve the process, template, automation, or KB entry for the next manager.\n\nREQUIRED ARTIFACTS BEFORE INDEPENDENT OWNERSHIP\n• Approved handoff and validated implementation scope.\n• Customer RACI with known roles only.\n• Deployment board and milestone path.\n• Risk / decision log.\n• ROI measurement contract with baseline method.\n• Engineering escalation packet example.\n• Meeting brief example.\n• Post-go-live adoption / value review example.\n\nOPERATING PRINCIPLE\nDo the work, document the path, then reduce the effort required for the next person. The team should get easier to join every time someone joins it."
},
{
 id:"kb-guidelines",
 slug:"implementation-kb-guidelines",
 title:"Implementation Best Practice KB: Contribution & Automation Guidelines",
 summary:"How the team captures reusable implementation knowledge without turning the KB into unreviewed notes or AI-generated noise.",
 category:"KB Operations",
 tags:["knowledge-base","automation","governance","confluence"],
 status:"published",
 source:"internal_best_practice",
 authorLabel:"Implementation Team",
 body:"WHAT BELONGS HERE\nAdd knowledge that can help another implementation manager make a better decision, avoid repeat work, or move a customer forward faster. Prefer reusable patterns over account-specific history.\n\nA GOOD KB POINT HAS\n• The situation or trigger.\n• What was observed.\n• The action that worked or failed.\n• The reason it matters.\n• When the guidance should and should not be applied.\n• A link to supporting evidence, Jira, or a customer record when appropriate.\n\nWHAT DOES NOT BELONG HERE\n• Unverified customer claims presented as fact.\n• Customer secrets or unnecessary PII.\n• Raw meeting notes with no reusable lesson.\n• AI suggestions that have not been reviewed by a person.\n• A workaround that has not been validated.\n\nAUTOMATION RULE\nThe CRM includes an Add guideline point action. That appends a reviewed point to this page with an audit trail. The next automation layer can propose candidate KB points from closed issues, retrospectives, rollout decisions, and repeated implementation patterns. Proposed points must remain suggestions until a person approves them. Automation may reduce capture effort; it does not get authority to silently rewrite team guidance.\n\nCONFLUENCE MODEL\nThis CRM keeps the operational KB available to the team regardless of which customer is selected. Confluence can be connected through the Clintware control plane as the external publication/mirror layer. The browser never receives Atlassian credentials. Until a Confluence connection is authorized, the local persistent KB remains fully usable and the UI must say Not connected rather than pretending sync occurred."
}
];
export class N7CRM{
 constructor(ctx){this.ctx=ctx;this.sql=ctx.storage.sql;this.sql.exec("CREATE TABLE IF NOT EXISTS workspaces(id TEXT PRIMARY KEY,name TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)");this.sql.exec("CREATE TABLE IF NOT EXISTS customers(id TEXT PRIMARY KEY,data TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)");this.sql.exec("CREATE TABLE IF NOT EXISTS records(id TEXT PRIMARY KEY,customer_id TEXT NOT NULL,type TEXT NOT NULL,provenance TEXT NOT NULL,data TEXT NOT NULL,archived INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)");const cc=[...this.sql.exec("PRAGMA table_info(customers)")].map(x=>x.name);if(!cc.includes("workspace_id"))this.sql.exec("ALTER TABLE customers ADD COLUMN workspace_id TEXT");const rc=[...this.sql.exec("PRAGMA table_info(records)")].map(x=>x.name);if(!rc.includes("workspace_id"))this.sql.exec("ALTER TABLE records ADD COLUMN workspace_id TEXT");this.sql.exec("UPDATE customers SET workspace_id=? WHERE workspace_id IS NULL OR workspace_id=''",WORKSPACE_ID);this.sql.exec("UPDATE records SET workspace_id=? WHERE workspace_id IS NULL OR workspace_id=''",WORKSPACE_ID);this.sql.exec("CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY,user_json TEXT NOT NULL,access_token TEXT NOT NULL,refresh_token TEXT,expires_at INTEGER NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)");this.sql.exec("CREATE TABLE IF NOT EXISTS audit(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,actor_sub TEXT NOT NULL,event TEXT NOT NULL,payload TEXT NOT NULL,created_at TEXT NOT NULL)");this.sql.exec("CREATE TABLE IF NOT EXISTS kb_articles(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,slug TEXT NOT NULL,title TEXT NOT NULL,summary TEXT NOT NULL,body TEXT NOT NULL,category TEXT NOT NULL,tags TEXT NOT NULL,status TEXT NOT NULL,source TEXT NOT NULL,author_label TEXT NOT NULL,views INTEGER NOT NULL DEFAULT 0,useful INTEGER NOT NULL DEFAULT 0,confluence_page_id TEXT NOT NULL DEFAULT '',confluence_url TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL)");this.sql.exec("CREATE UNIQUE INDEX IF NOT EXISTS idx_kb_workspace_slug ON kb_articles(workspace_id,slug)");this.sql.exec("CREATE TABLE IF NOT EXISTS kb_config(workspace_id TEXT PRIMARY KEY,data TEXT NOT NULL,updated_at TEXT NOT NULL)");this.ctx.blockConcurrencyWhile(()=>this.seed())}
 async seed(){const t=ts();
  if(![...this.sql.exec("SELECT id FROM workspaces WHERE id=?",WORKSPACE_ID)].length)this.sql.exec("INSERT INTO workspaces(id,name,created_at,updated_at) VALUES(?,?,?,?)",WORKSPACE_ID,"N7 Demo CRM Team",t,t);
  const kbCfg={mode:"Clintware Control Plane",connection:"Not connected",siteUrl:"",spaceKey:"",parentPageId:"",homePageUrl:"",localSourceOfTruth:true,lastSyncAt:"",lastSyncStatus:"Never synced"};
  this.sql.exec("INSERT OR IGNORE INTO kb_config(workspace_id,data,updated_at) VALUES(?,?,?)",WORKSPACE_ID,JSON.stringify(kbCfg),t);
  for(const a of KB_SEED)this.sql.exec("INSERT OR IGNORE INTO kb_articles(id,workspace_id,slug,title,summary,body,category,tags,status,source,author_label,views,useful,confluence_page_id,confluence_url,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,0,0,'','',?,?)",a.id,WORKSPACE_ID,a.slug,a.title,a.summary,a.body,a.category,JSON.stringify(a.tags),a.status,a.source,a.authorLabel,t,t);
  if(![...this.sql.exec("SELECT id FROM customers WHERE id=?",CUSTOMER.id)].length){
    this.sql.exec("INSERT INTO customers(id,workspace_id,data,created_at,updated_at) VALUES(?,?,?,?,?)",CUSTOMER.id,WORKSPACE_ID,JSON.stringify(CUSTOMER),t,t);
    for(const [type,p,data] of SEED)this.sql.exec("INSERT INTO records(id,workspace_id,customer_id,type,provenance,data,archived,created_at,updated_at) VALUES(?,?,?,?,?,?,0,?,?)",crypto.randomUUID(),WORKSPACE_ID,CUSTOMER.id,type,p,JSON.stringify(data),t,t);
  }
 }

 row(r){return{id:r.id,customerId:r.customer_id,type:r.type,provenance:r.provenance,data:JSON.parse(r.data),createdAt:r.created_at,updatedAt:r.updated_at}}
 kbRow(r){return{id:r.id,slug:r.slug,title:r.title,summary:r.summary,body:r.body,category:r.category,tags:JSON.parse(r.tags||"[]"),status:r.status,source:r.source,authorLabel:r.author_label,views:Number(r.views||0),useful:Number(r.useful||0),confluencePageId:r.confluence_page_id||"",confluenceUrl:r.confluence_url||"",createdAt:r.created_at,updatedAt:r.updated_at}}
 audit(workspace,actor,event,payload={}){this.sql.exec("INSERT INTO audit VALUES(?,?,?,?,?,?)",crypto.randomUUID(),workspace,actor||"system",event,JSON.stringify(payload),ts())}
 async fetch(req){const u=new URL(req.url),p=u.pathname,m=req.method;
  if(m==="POST"&&p==="/session"){const b=await req.json(),t=ts();this.sql.exec("INSERT OR REPLACE INTO sessions VALUES(?,?,?,?,?,?,?)",b.id,JSON.stringify(b.user),b.accessToken,b.refreshToken||"",Number(b.expiresAt||Date.now()+900000),t,t);return j({ok:true})}
  if(m==="GET"&&p.startsWith("/session/")){const id=p.slice(9),r=[...this.sql.exec("SELECT * FROM sessions WHERE id=?",id)][0];if(!r)return j({error:"not_found"},404);return j({id:r.id,user:JSON.parse(r.user_json),accessToken:r.access_token,refreshToken:r.refresh_token,expiresAt:r.expires_at})}
  if(m==="PATCH"&&p.startsWith("/session/")){const id=p.slice(9),b=await req.json();this.sql.exec("UPDATE sessions SET access_token=?,refresh_token=?,expires_at=?,updated_at=? WHERE id=?",b.accessToken,b.refreshToken||"",Number(b.expiresAt),ts(),id);return j({ok:true})}
  if(m==="DELETE"&&p.startsWith("/session/")){this.sql.exec("DELETE FROM sessions WHERE id=?",p.slice(9));return j({ok:true})}
  const workspace=req.headers.get("x-workspace-id")||"";const actor=req.headers.get("x-actor-sub")||"";
  if(!workspace)return j({error:"workspace_required"},401);
  if(m==="GET"&&p==="/state"){const customers=[...this.sql.exec("SELECT * FROM customers WHERE workspace_id=? ORDER BY created_at",workspace)].map(r=>JSON.parse(r.data));const id=u.searchParams.get("customer")||CUSTOMER.id;const c=customers.find(x=>x.id===id)||customers[0];if(!c)return j({error:"No customer"},404);const records=[...this.sql.exec("SELECT * FROM records WHERE workspace_id=? AND customer_id=? AND archived=0 ORDER BY created_at",workspace,c.id)].map(r=>this.row(r));return j({customer:c,customers,records,workspace:{id:workspace,name:"N7 Demo CRM Team"}})}
  if(m==="GET"&&p==="/kb"){const articles=[...this.sql.exec("SELECT * FROM kb_articles WHERE workspace_id=? AND status!='archived' ORDER BY updated_at DESC",workspace)].map(r=>this.kbRow(r));const cfgRow=[...this.sql.exec("SELECT data FROM kb_config WHERE workspace_id=?",workspace)][0];const config=cfgRow?JSON.parse(cfgRow.data):{};const latest=articles.slice().sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))).slice(0,8);const trending=articles.slice().sort((a,b)=>(b.useful*8+b.views*2)-(a.useful*8+a.views*2)||String(b.updatedAt).localeCompare(String(a.updatedAt))).slice(0,8);return j({articles,latest,trending,config,usageSignalAvailable:articles.some(a=>a.views||a.useful)})}
  if(m==="POST"&&p==="/kb/articles"){const b=await req.json(),id=crypto.randomUUID(),t=ts(),slug=String(b.slug||b.title||"article").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")+"-"+id.slice(0,8);this.sql.exec("INSERT INTO kb_articles(id,workspace_id,slug,title,summary,body,category,tags,status,source,author_label,views,useful,confluence_page_id,confluence_url,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,0,0,?,?,?,?)",id,workspace,slug,String(b.title||"Untitled article"),String(b.summary||""),String(b.body||""),String(b.category||"Implementation"),JSON.stringify(Array.isArray(b.tags)?b.tags:[]),String(b.status||"published"),"internal_best_practice",String(b.authorLabel||"Implementation Team"),String(b.confluencePageId||""),String(b.confluenceUrl||""),t,t);this.audit(workspace,actor,"kb.article.created",{id,slug});return j({id,slug},201)}
  const ka=p.match(/^\/kb\/articles\/([^/]+)$/);if(ka&&m==="GET"){const r=[...this.sql.exec("SELECT * FROM kb_articles WHERE id=? AND workspace_id=?",ka[1],workspace)][0];if(!r)return j({error:"Not found"},404);this.sql.exec("UPDATE kb_articles SET views=views+1 WHERE id=? AND workspace_id=?",ka[1],workspace);const article=this.kbRow({...r,views:Number(r.views||0)+1});this.audit(workspace,actor,"kb.article.viewed",{id:ka[1]});return j({article})}
  if(ka&&m==="PATCH"){const b=await req.json(),r=[...this.sql.exec("SELECT * FROM kb_articles WHERE id=? AND workspace_id=?",ka[1],workspace)][0];if(!r)return j({error:"Not found"},404);const old=this.kbRow(r);const n={...old,...b,tags:Array.isArray(b.tags)?b.tags:old.tags};this.sql.exec("UPDATE kb_articles SET title=?,summary=?,body=?,category=?,tags=?,status=?,author_label=?,confluence_page_id=?,confluence_url=?,updated_at=? WHERE id=? AND workspace_id=?",String(n.title),String(n.summary),String(n.body),String(n.category),JSON.stringify(n.tags),String(n.status),String(n.authorLabel),String(n.confluencePageId||""),String(n.confluenceUrl||""),ts(),ka[1],workspace);this.audit(workspace,actor,"kb.article.updated",{id:ka[1]});return j({ok:true})}
  if(ka&&m==="DELETE"){this.sql.exec("UPDATE kb_articles SET status='archived',updated_at=? WHERE id=? AND workspace_id=?",ts(),ka[1],workspace);this.audit(workspace,actor,"kb.article.archived",{id:ka[1]});return j({ok:true})}
  const useful=p.match(/^\/kb\/articles\/([^/]+)\/useful$/);if(useful&&m==="POST"){this.sql.exec("UPDATE kb_articles SET useful=useful+1,updated_at=? WHERE id=? AND workspace_id=?",ts(),useful[1],workspace);this.audit(workspace,actor,"kb.article.useful",{id:useful[1]});return j({ok:true})}
  if(m==="POST"&&p==="/kb/guidelines/append"){const b=await req.json(),point=String(b.point||"").trim();if(!point)return j({error:"guideline_point_required"},400);const r=[...this.sql.exec("SELECT * FROM kb_articles WHERE id='kb-guidelines' AND workspace_id=?",workspace)][0];if(!r)return j({error:"guidelines_article_missing"},404);const next=String(r.body||"")+"\n\nTEAM-ADDED GUIDELINE · "+new Date().toISOString().slice(0,10)+"\n• "+point;this.sql.exec("UPDATE kb_articles SET body=?,updated_at=? WHERE id='kb-guidelines' AND workspace_id=?",next,ts(),workspace);this.audit(workspace,actor,"kb.guideline.appended",{point:point.slice(0,500)});return j({ok:true,articleId:"kb-guidelines"})}
  if(m==="PATCH"&&p==="/kb/config"){const b=await req.json(),r=[...this.sql.exec("SELECT data FROM kb_config WHERE workspace_id=?",workspace)][0],old=r?JSON.parse(r.data):{};const next={...old,...b,mode:"Clintware Control Plane"};this.sql.exec("INSERT OR REPLACE INTO kb_config(workspace_id,data,updated_at) VALUES(?,?,?)",workspace,JSON.stringify(next),ts());this.audit(workspace,actor,"kb.confluence.config_updated",{siteUrl:next.siteUrl||"",spaceKey:next.spaceKey||"",hasParentPage:Boolean(next.parentPageId)});return j({config:next})}

  if(m==="POST"&&p==="/customers"){const b=await req.json(),id=crypto.randomUUID(),t=ts(),c={id,name:String(b.name||"New Customer"),nameStatus:b.name?"User-entered":"Name not provided",industry:String(b.industry||""),stage:"Onboarding",week:null,provenance:"internal_record",facts:{}};this.sql.exec("INSERT INTO customers(id,workspace_id,data,created_at,updated_at) VALUES(?,?,?,?,?)",id,workspace,JSON.stringify(c),t,t);const raci={title:"Implementation RACI",rows:[],roles:["Customer","Customer Success / Implementation","Engineering","Product","Support","Sales"],note:"Template only. Assign responsibilities explicitly."};this.sql.exec("INSERT INTO records(id,workspace_id,customer_id,type,provenance,data,archived,created_at,updated_at) VALUES(?,?,?,?,?,?,0,?,?)",crypto.randomUUID(),workspace,id,"raci","template",JSON.stringify(raci),t,t);this.audit(workspace,actor,"customer.created",{customerId:id});return j({customer:c},201)}
  if(m==="POST"&&p==="/records"){const b=await req.json(),id=crypto.randomUUID(),t=ts(),pv=String(b.provenance||"internal_record");this.sql.exec("INSERT INTO records(id,workspace_id,customer_id,type,provenance,data,archived,created_at,updated_at) VALUES(?,?,?,?,?,?,0,?,?)",id,workspace,String(b.customerId),String(b.type),pv,JSON.stringify(b.data||{}),t,t);this.audit(workspace,actor,"record.created",{id,type:b.type,customerId:b.customerId});return j({id},201)}
  const mm=p.match(/^\/records\/([^/]+)$/);if(mm&&m==="PATCH"){const b=await req.json(),rows=[...this.sql.exec("SELECT * FROM records WHERE id=? AND workspace_id=?",mm[1],workspace)];if(!rows.length)return j({error:"Not found"},404);const old=this.row(rows[0]);this.sql.exec("UPDATE records SET data=?,provenance=?,updated_at=? WHERE id=? AND workspace_id=?",JSON.stringify({...old.data,...(b.data||{})}),b.provenance||old.provenance,ts(),mm[1],workspace);this.audit(workspace,actor,"record.updated",{id:mm[1],type:old.type});return j({ok:true})}
  if(mm&&m==="DELETE"){this.sql.exec("UPDATE records SET archived=1,updated_at=? WHERE id=? AND workspace_id=?",ts(),mm[1],workspace);this.audit(workspace,actor,"record.archived",{id:mm[1]});return j({ok:true})}
  if(m==="POST"&&p==="/import"){const b=await req.json(),ids=[];for(const f of(b.facts||[])){const id=crypto.randomUUID(),t=ts(),d={...(f.data||{}),importSource:b.sourceName||"Uploaded source",sourceSnippet:f.sourceSnippet||""};this.sql.exec("INSERT INTO records(id,workspace_id,customer_id,type,provenance,data,archived,created_at,updated_at) VALUES(?,?,?,?,?,?,0,?,?)",id,workspace,String(b.customerId),String(f.type||"note"),"customer_provided",JSON.stringify(d),t,t);ids.push(id)}this.audit(workspace,actor,"import.committed",{customerId:b.customerId,count:ids.length,source:b.sourceName});return j({inserted:ids},201)}
  if(m==="GET"&&p==="/export"){const customers=[...this.sql.exec("SELECT * FROM customers WHERE workspace_id=?",workspace)].map(r=>JSON.parse(r.data));const records=[...this.sql.exec("SELECT * FROM records WHERE workspace_id=?",workspace)].map(r=>this.row(r));const audit=[...this.sql.exec("SELECT event,payload,created_at FROM audit WHERE workspace_id=? ORDER BY created_at DESC LIMIT 5000",workspace)].map(r=>({event:r.event,payload:JSON.parse(r.payload),createdAt:r.created_at}));const kb=[...this.sql.exec("SELECT * FROM kb_articles WHERE workspace_id=?",workspace)].map(r=>this.kbRow(r));const kbCfg=[...this.sql.exec("SELECT data FROM kb_config WHERE workspace_id=?",workspace)][0];return j({format:"n7demo-crm-backup-v2",exportedAt:ts(),workspace,customers,records,kb,kbConfig:kbCfg?JSON.parse(kbCfg.data):{},audit})}
  if(m==="GET"&&p==="/backup"){const customers=[...this.sql.exec("SELECT * FROM customers WHERE workspace_id=?",WORKSPACE_ID)].map(r=>JSON.parse(r.data));const records=[...this.sql.exec("SELECT * FROM records WHERE workspace_id=?",WORKSPACE_ID)].map(r=>this.row(r));return j({format:"n7demo-crm-backup-v1",exportedAt:ts(),workspace:WORKSPACE_ID,customers,records})}
  return j({error:"Not found"},404)
 }
}
function doStub(env){return env.CRM.get(env.CRM.idFromName("n7demo-main"))}
async function currentSession(req,env){const sid=cookie(req,SESSION_COOKIE);if(!sid)return null;const stub=doStub(env);let r=await stub.fetch("https://internal/session/"+encodeURIComponent(sid));if(!r.ok)return null;let s=await r.json();let user=null;if(Number(s.expiresAt||0)>Date.now()+30000)user=await userInfo(s.accessToken).catch(()=>null);if(!user){const nt=await refreshTokens(s).catch(()=>null);if(!nt)return null;await stub.fetch("https://internal/session/"+encodeURIComponent(sid),{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(nt)});user=await userInfo(nt.accessToken).catch(()=>null);if(!user)return null;s={...s,...nt}}if(!userAllowed(user))return null;return {sid,user,workspaceId:WORKSPACE_ID}}
async function finishLogin(req,env){const u=new URL(req.url),code=u.searchParams.get("code")||"",state=u.searchParams.get("state")||"",tx=cookie(req,TX_COOKIE),dot=tx.indexOf("."),expected=dot>0?tx.slice(0,dot):"",verifier=dot>0?tx.slice(dot+1):"";if(!code||!state||state!==expected||!verifier)return html("<h1>Login could not be completed</h1>",400,{"set-cookie":clearCookie(TX_COOKIE)});const cfg=await authConfig();const tr=await fetch(cfg.token_endpoint,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded",accept:"application/json"},body:new URLSearchParams({grant_type:"authorization_code",client_id:cfg.client_id,code,redirect_uri:cfg.redirect_uri,code_verifier:verifier})});const tok=await tr.json().catch(()=>({}));if(!tr.ok||!tok.access_token)return html("<h1>Clintware Identity did not issue a usable token.</h1>",502);const user=await userInfo(tok.access_token);if(!userAllowed(user))return html("<h1>Access is not authorized for this CRM.</h1>",403);const sid=rand(32),expiresAt=Date.now()+Number(tok.expires_in||900)*1000;await doStub(env).fetch("https://internal/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:sid,user,accessToken:tok.access_token,refreshToken:tok.refresh_token||"",expiresAt})});const h=secureHeaders(new Headers({location:"/","set-cookie":setCookie(SESSION_COOKIE,sid,30*24*60*60)}));h.append("set-cookie",clearCookie(TX_COOKIE));return new Response(null,{status:302,headers:h})}

async function cpJira(env,operation,args={}){const r=await env.CONTROL_PLANE.fetch("https://internal/api/v1/jira/bridge",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({product:APP_ID,operation,args,request_id:crypto.randomUUID()})});const x=await r.json().catch(()=>({error:"invalid_control_plane_response"}));return {status:r.status,data:x}}
async function cpEvent(env,action,metadata={}){try{await env.CONTROL_PLANE.fetch("https://internal/api/v1/events",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({product:APP_ID,environment:"production",feature:"n7demo_crm",action,success:true,metadata,request_id:crypto.randomUUID()})})}catch{}}
export default{
 async fetch(req,env){const u=new URL(req.url);if(u.pathname==="/health")return j({ok:true,service:"clintware-n7demo-crm",canonicalUrl:"https://n7demo.clintware.com",storage:"Durable Objects SQLite + audit history + account export",identity:AUTH_ORIGIN,oauthApp:APP_ID,jira:"native bridge via Clintware control plane",confluence:"KB ready; control-plane publication adapter awaits Atlassian authorization/config",kb:"workspace-global persistent Implementation Best Practice KB",lovable:false});
  if(req.method==="GET"&&u.pathname==="/auth/login")return startLogin();
  if(req.method==="GET"&&u.pathname==="/auth/callback")return finishLogin(req,env);
  if(req.method==="POST"&&u.pathname==="/auth/logout"){const s=await currentSession(req,env).catch(()=>null);if(s)await doStub(env).fetch("https://internal/session/"+encodeURIComponent(s.sid),{method:"DELETE"});return new Response(null,{status:303,headers:secureHeaders(new Headers({location:"/","set-cookie":clearCookie(SESSION_COOKIE)}))})}
  const session=await currentSession(req,env).catch(()=>null);
  if(u.pathname==="/api/control-plane/status"){if(!session)return j({error:"authentication_required"},401);const r=await env.CONTROL_PLANE.fetch("https://internal/health");return j({reachable:r.ok,status:r.status,product:APP_ID,jiraBridge:true,confluenceAdapter:"configuration-ready"})}
  if(u.pathname==="/api/integrations/jira/status"){if(!session)return j({error:"authentication_required"},401);const x=await cpJira(env,"status");return j(x.data,x.status)}
  if(u.pathname==="/api/integrations/jira/sites"){if(!session)return j({error:"authentication_required"},401);const x=await cpJira(env,"sites");return j(x.data,x.status)}
  if(u.pathname==="/api/integrations/jira/search"&&req.method==="POST"){if(!session)return j({error:"authentication_required"},401);const b=await req.json();const x=await cpJira(env,"search",b);await cpEvent(env,"jira.search",{ok:x.status<400});return j(x.data,x.status)}
  if(u.pathname==="/api/integrations/jira/create"&&req.method==="POST"){if(!session)return j({error:"authentication_required"},401);const b=await req.json();const x=await cpJira(env,"create",b);await cpEvent(env,"jira.create",{ok:x.status<400,project_key:b.project_key||""});return j(x.data,x.status)}
  if(u.pathname.startsWith("/api/")){if(!session)return j({error:"authentication_required"},401);const stub=doStub(env),x=new URL(req.url);x.pathname=x.pathname.replace(/^\/api/,"")||"/";const h=new Headers(req.headers);h.set("x-workspace-id",session.workspaceId);h.set("x-actor-sub",session.user.sub);return stub.fetch(new Request(x,{method:req.method,headers:h,body:["GET","HEAD"].includes(req.method)?undefined:req.body,redirect:req.redirect}))}
  if(u.pathname==="/"&&!session)return html(loginPage());
  if(u.pathname==="/me")return session?j({user:session.user,workspaceId:session.workspaceId}):j({error:"authentication_required"},401);
  const r=await env.ASSETS.fetch(req),h=secureHeaders(new Headers(r.headers));return new Response(r.body,{status:r.status,statusText:r.statusText,headers:h})
 }
};