export const nmaDataBlock=String.raw`
const CUSTOMER={id:"northstar-bank-synthetic",name:"Northstar Bank (Synthetic)",nameStatus:"Golden example account · synthetic",industry:"Global financial services",stage:"Operationalize AI security",week:10,provenance:"synthetic_sample",isGoldenExample:true,protected:true,defaultSample:true,sourceFile:"Synthetic Noma Customer Solutions Architecture scenario",facts:{users:"CISO, AI platform, AppSec, GRC, developer productivity, cloud security, business-unit AI owners",product:"AI-SPM; AI Access Control; AI-DR; AI Red Team; MCP Security",committedTimeline:"Synthetic two-quarter AI security maturity plan",roiTarget:"Increase governed AI coverage, reduce unmanaged agent/MCP risk, prove control effectiveness, and create an executive evidence path for safe AI expansion",kickoff:"Executive objectives aligned; discovery active; priority AI workloads and governance gaps mapped",unvalidatedDependencies:"Final identity boundaries, production telemetry coverage, control owners, and two business-unit expansion priorities remain open",successMetrics:"Synthetic targets: 95% AI asset inventory coverage; 90% priority MCP governance coverage; 100% critical toxic combinations assigned; 85% high-risk runtime coverage; 90% critical red-team findings closed before production",currentSystems:"AWS; Azure; GitHub; Okta; Microsoft Entra ID; SIEM; EDR; internal AI gateway; RAG services; developer IDE agents; MCP servers; SaaS copilots"}};
const SEED=[
["handoff","synthetic_sample",{title:"Customer objective",value:"Operationalize an enterprise AI security and governance program that keeps agentic adoption moving while making risk, control ownership, and executive evidence explicit.",validation:"Synthetic golden example",note:"Candidate operating model derived from public role and platform context."}],
["handoff","synthetic_sample",{title:"AI environment",value:"Endpoint coding agents; homegrown RAG and agent workflows; SaaS copilots; cloud AI platforms; internal agent gateway; approved and unapproved MCP servers.",validation:"Synthetic golden example",note:"Designed to exercise GenAI, LLM app, RAG, agent, AI pipeline, identity, data, and MCP discovery."}],
["handoff","synthetic_sample",{title:"Security program priorities",value:"Discover the AI estate; govern MCP/tool access; test high-risk applications; protect runtime activity; produce GRC-ready evidence; preserve developer velocity.",validation:"Synthetic golden example",note:"Priorities are synthetic and do not describe a real Noma customer."}],
["integration","synthetic_sample",{name:"AWS + Azure AI estate",purpose:"Discover cloud-hosted models, agents, RAG applications, identities, data paths, and development workloads",connectorStatus:"Synthetic · active",technicalValidation:"Synthetic inventory feed mapped to accountable owners."}],
["integration","synthetic_sample",{name:"GitHub + AI development pipeline",purpose:"Map repositories, agentic coding surfaces, dependencies, skills, prompts, MCP configuration, and production promotion path",connectorStatus:"Synthetic · active",technicalValidation:"Synthetic pipeline ownership and critical-workload tags present."}],
["integration","synthetic_sample",{name:"Okta / Entra ID",purpose:"Map user and group identity to agent, MCP server, skill, and tool access policy",connectorStatus:"Synthetic · active",technicalValidation:"Synthetic privileged groups and service identities available for governance review."}],
["integration","synthetic_sample",{name:"SIEM / security operations",purpose:"Route high-confidence runtime findings, policy violations, and investigation context to the existing response workflow",connectorStatus:"Synthetic · in validation",technicalValidation:"Synthetic event-routing acceptance criteria defined."}],
["kpi","synthetic_sample",{name:"AI asset inventory coverage",hypothesis:"A trustworthy control program begins with a current inventory of AI applications, agents, models, RAG services, MCP servers, tools, identities, and owners.",baseline:"61% synthetic coverage",target:"95%+",metricDefinition:"Priority AI assets with validated owner and environment classification divided by expected priority AI estate",sourceSystem:"Synthetic AI asset ledger",owner:"AI Platform + Security Architecture",cadence:"Weekly",calculation:"Validated assets / expected priority assets",currentValue:"88%",realizedValue:"Inventory blind spots materially reduced in synthetic scenario",approval:"Synthetic sample"}],
["kpi","synthetic_sample",{name:"Priority MCP governance coverage",hypothesis:"MCP adoption can scale more safely when servers and tools have an explicit approved/review/blocked state, owner, permission boundary, and user-group policy.",baseline:"32% synthetic governed coverage",target:"90%+",metricDefinition:"Priority MCP servers with owner, review status, tool scope, and access policy divided by priority MCP server inventory",sourceSystem:"Synthetic MCP registry",owner:"AppSec + Developer Productivity",cadence:"Weekly",calculation:"Governed / priority MCP servers",currentValue:"76%",realizedValue:"Not yet approved",approval:"Synthetic sample"}],
["kpi","synthetic_sample",{name:"Critical toxic combinations assigned",hypothesis:"Critical cross-layer risk loses operational value if no accountable remediation owner or decision date exists.",baseline:"45% synthetic assignment",target:"100%",metricDefinition:"Critical AI risk combinations with accountable owner, disposition, and target date divided by critical combinations",sourceSystem:"Synthetic risk register",owner:"Security Architecture",cadence:"Weekly",calculation:"Assigned / critical",currentValue:"92%",realizedValue:"Not yet approved",approval:"Synthetic sample"}],
["kpi","synthetic_sample",{name:"High-risk runtime protection coverage",hypothesis:"Runtime controls should be prioritized around high-risk applications and agent actions rather than uniform deployment for its own sake.",baseline:"28% synthetic coverage",target:"85%+",metricDefinition:"High-risk production AI applications with agreed runtime policy and telemetry divided by high-risk production AI applications",sourceSystem:"Synthetic runtime coverage ledger",owner:"AI Security + SOC",cadence:"Weekly",calculation:"Protected / high-risk apps",currentValue:"71%",realizedValue:"Not yet approved",approval:"Synthetic sample"}],
["kpi","synthetic_sample",{name:"Critical pre-production findings closed",hypothesis:"Red-team findings create value when critical issues are resolved or explicitly accepted before production promotion.",baseline:"54% synthetic closure",target:"90%+",metricDefinition:"Critical test findings closed or formally risk-accepted before release divided by critical findings",sourceSystem:"Synthetic AI red-team ledger",owner:"AppSec + Application Owners",cadence:"Per release",calculation:"Closed or accepted / critical findings",currentValue:"83%",realizedValue:"Not yet approved",approval:"Synthetic sample"}],
["adoption","synthetic_sample",{name:"AI-SPM priority estate coverage",value:"88%",period:"Current synthetic period",source:"Synthetic AI asset ledger",owner:"AI Platform + Security Architecture"}],
["adoption","synthetic_sample",{name:"MCP governance coverage",value:"76%",period:"Current synthetic period",source:"Synthetic MCP registry",owner:"AppSec + Developer Productivity"}],
["adoption","synthetic_sample",{name:"High-risk AI-DR runtime coverage",value:"71%",period:"Current synthetic period",source:"Synthetic runtime ledger",owner:"AI Security + SOC"}],
["risk","synthetic_sample",{title:"Unapproved local MCP server exposes a deployment tool with excessive write scope",impact:"A compromised or manipulated agent could reach a high-consequence tool beyond the intended developer workflow.",owner:"AppSec + Developer Productivity",mitigation:"Move the server to review state, reduce tool scope, pin dependencies, map user groups, and block production use until policy acceptance criteria are met.",escalationStatus:"Open · high",nextDecision:"Approve narrowed tool scope or keep the server blocked."}],
["risk","synthetic_sample",{title:"Internal RAG assistant uses an overly broad service identity across two sensitive knowledge domains",impact:"Prompt injection or agent misuse could increase the data exposure blast radius.",owner:"AI Platform + Identity Engineering",mitigation:"Segment service identity, validate retrieval authorization, add runtime policy for sensitive actions, and retest the application.",escalationStatus:"Open · critical",nextDecision:"Approve segmented identity design and retest criteria."}],
["risk","synthetic_sample",{title:"Three business units are requesting AI expansion before governance owners are staffed",impact:"Adoption may outpace the team's ability to maintain inventory, access reviews, test gates, and runtime response.",owner:"CISO + AI Governance Council",mitigation:"Score expansion by value, workload risk, owner readiness, control coverage, and evidence path before onboarding.",escalationStatus:"Open",nextDecision:"Select two expansion candidates with named control owners."}],
["stakeholder","synthetic_sample",{name:"Jordan Lee (Synthetic)",role:"Chief Information Security Officer",organization:"Northstar Bank (Synthetic)",email:"",phone:"",decisionRole:"Executive sponsor; risk appetite; investment narrative; escalation authority",status:"Active",notes:"Owns executive AI security program outcomes and major risk decisions."}],
["stakeholder","synthetic_sample",{name:"Maya Chen (Synthetic)",role:"VP, AI Platform",organization:"Northstar Bank (Synthetic)",email:"",phone:"",decisionRole:"AI architecture, platform adoption, workload onboarding, technical standards",status:"Active",notes:"Primary technical counterpart for cloud AI, agent and RAG estate."}],
["stakeholder","synthetic_sample",{name:"Rafael Ortiz (Synthetic)",role:"Director, Application Security",organization:"Northstar Bank (Synthetic)",email:"",phone:"",decisionRole:"AI testing gates, code/pipeline security, MCP and tool review",status:"Active",notes:"Owns AppSec acceptance path and agentic development guardrails."}],
["stakeholder","synthetic_sample",{name:"Avery Morgan (Synthetic)",role:"Head of GRC",organization:"Northstar Bank (Synthetic)",email:"",phone:"",decisionRole:"Control evidence, compliance mapping, policy governance, audit readiness",status:"Active",notes:"Owns evidence sufficiency and control-review cadence."}],
["stakeholder","synthetic_sample",{name:"Sam Patel (Synthetic)",role:"VP, Developer Productivity",organization:"Northstar Bank (Synthetic)",email:"",phone:"",decisionRole:"Coding-agent and MCP adoption; developer experience; tool enablement",status:"Active",notes:"Balances AI developer velocity with governed tool access."}],
["action","synthetic_sample",{title:"Complete owner and policy review for top 12 MCP servers",owner:"AppSec + Developer Productivity",due:"Week 11",status:"In Progress",audience:"Customer / Internal"}],
["action","synthetic_sample",{title:"Retest RAG assistant after identity segmentation",owner:"AI Platform + AppSec",due:"Week 12",status:"Planned",audience:"Customer / Internal"}],
["action","synthetic_sample",{title:"Publish CISO evidence pack for governed AI expansion decision",owner:"Customer Solutions + GRC",due:"Week 12",status:"In Progress",audience:"Executive"}],
["action","synthetic_sample",{title:"Score three requested business-unit expansions by value, risk, readiness, and control-owner capacity",owner:"Customer Solutions + Sales + AI Governance Council",due:"Week 13",status:"Planned",audience:"Customer / Internal"}],
["issue","internal_record",{title:"Cross-functional escalation: runtime event routing acceptance",status:"In Progress",owner:"Customer Solutions + Support + Security Engineering",priority:"High",detail:"Synthetic event-routing test needs final alert context fields, ownership, and response SLA acceptance before broad production rollout."}],
["issue","internal_record",{title:"Product signal: customers need faster owner attribution for newly discovered MCP servers",status:"Open",owner:"Customer Solutions → Product / Research",priority:"Medium",detail:"Synthetic recurring signal: discovery is fast, but teams want clearer identity and ownership enrichment before governance review."}],
["meeting","synthetic_sample",{title:"Quarterly AI Security Executive Review",type:"CISO / GRC review",date:"Week 12",attendees:"CISO; VP AI Platform; AppSec; GRC; Developer Productivity; Sales; Customer Solutions",objective:"Review AI estate coverage, top risk, governance adoption, control effectiveness, value evidence, and the next expansion decisions.",notes:"Synthetic candidate-demo meeting."}],
["call_prep","internal_proposal",{title:"Quarterly AI Security Executive Review",meetingDate:"Week 12",meetingType:"CISO / GRC executive review",objective:"Lead with the customer's AI expansion objective, show what is governed versus still exposed, quantify progress with evidence, isolate decisions, and leave with explicit owners and dates.",attendees:"CISO; VP AI Platform; AppSec; GRC; Developer Productivity; Sales; Customer Solutions",opening:"Start with the business decision: where can AI adoption safely accelerate next quarter, and which remaining control gaps would make that irresponsible?",currentState:"Synthetic inventory coverage is 88%. Priority MCP governance is 76%. High-risk runtime coverage is 71%. Critical pre-production finding closure is 83%. One critical RAG identity risk and one high-scope MCP issue remain open.",evidenceReady:"Synthetic AI estate map; risk graph; MCP registry; identity/tool access review; AI red-team closure ledger; runtime coverage; action register; expansion scorecard.",questions:"Which remaining risk changes the expansion decision? Which controls have sufficient evidence? Which workloads need stronger runtime policy? Which two business units have both value and control-owner readiness? Which product friction should be escalated internally?",decisions:"Approve or reject narrowed MCP scope; approve RAG identity retest criteria; confirm runtime rollout acceptance; select two expansion candidates; assign executive owner for remaining evidence gaps.",escalationCriteria:"Escalate when customer impact is material, owner is unclear, a high-risk control is blocked, technical evidence conflicts, or a commercial decision is being made without validated customer value.",followUp:"Publish decisions, owners, due dates, evidence gaps, Sales expansion hypotheses, and Product/Research signal into the shared success plan.",technologyNotes:"Keep discovery, governance, testing, runtime protection, and business value distinct. A discovered asset is not governed; a policy is not proof of enforcement; a test finding is not resolved until closure or risk acceptance is evidenced.",assistantNotes:"Use only public Noma role/platform context plus this synthetic account state. Never imply access to private Noma customer data, internal roadmap commitments, or real customer outcomes."}],
["assistant_profile","template",{title:"AI Security Customer Solutions operating playbook",playbook:"CUSTOMER SOLUTIONS BASELINE\n- Begin with customer objectives, AI program maturity, risk posture, and the decision that matters.\n- Map GenAI applications, RAG, agents, AI development pipelines, MCP servers, tools, identities, data, environments, and owners before prescribing controls.\n- Separate discovery from governance, governance from testing, testing from runtime protection, and technical activity from realized business value.\n- For every material risk: record impact, evidence, owner, mitigation, escalation state, decision, and next checkpoint.\n- Coordinate technical resources around explicit acceptance criteria and customer outcomes.\n- Quantify progress with measurement contracts that define baseline, source, calculation, owner, cadence, and target.\n- Use executive reviews to drive decisions, not recite activity.\n- Partner with Sales on expansion only where customer value and operational readiness are explicit.\n- Close the loop with Product, Research, Engineering, Security, Support, and customer operationalization teams.\n- Never turn a synthetic target, correlation, or activity metric into a realized-value claim.",participants:"",updatedFrom:"Public Noma Senior Customer Solutions Architect role + platform context + synthetic operating model"}],
["raci","template",{title:"Enterprise AI security program RACI",rows:[],roles:["CISO","AI Platform","AppSec","GRC","Developer Productivity","Customer Solutions","Sales","Product / Research","Support / Engineering"],note:"Template. Assign real names and decision rights during discovery."}],
["jira_config","internal_record",{siteUrl:"",deploymentBoardId:"",issueBoardId:"",projectKey:"",deploymentIssueType:"",issueType:"",connection:"Not connected",mode:"Optional governed work-system bridge"}]
];
const KB_SEED=[
{id:"kb-nma-ai-program",slug:"ai-security-program-loop",title:"From AI Discovery to Governed Expansion",summary:"A practical customer operating model that separates visibility, governance, testing, runtime protection, value, and expansion.",category:"Customer Solutions",tags:["ai-security","governance","mcp","agents","value"],status:"published",source:"internal_best_practice",authorLabel:"Candidate operating model",body:"DISCOVERY CREATES THE MAP\nInventory AI applications, agents, models, RAG services, MCP servers, tools, identities, data paths, environments, and owners.\n\nGOVERNANCE CREATES DECISION RIGHTS\nRecord approved/review/blocked state, tool scope, user groups, owner, and policy evidence.\n\nTESTING CREATES PRE-PRODUCTION EVIDENCE\nDefine acceptance criteria, run adversarial tests, and close or explicitly accept critical findings before production.\n\nRUNTIME PROTECTION CREATES CONTINUOUS CONTROL\nPrioritize high-risk actions and workloads; connect policy events to existing security operations.\n\nVALUE NEEDS A MEASUREMENT CONTRACT\nFor each outcome record baseline, metric definition, source, calculation, owner, cadence, and target.\n\nEXPANSION FOLLOWS PROOF AND READINESS\nScore new teams and workloads by value, risk, readiness, owner capacity, and control coverage before scaling."}
];
`;
