import { CONFIG, escapeHtml } from "./lib.js";

const ANALYTICS_HEAD = `<script async src="https://www.googletagmanager.com/gtag/js?id=G-DCY144YM9P"></script>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6169557480632773" crossorigin="anonymous"></script>
<script>
window.dataLayer=window.dataLayer||[];
function gtag(){dataLayer.push(arguments)}
gtag('js',new Date());
gtag('config','G-DCY144YM9P',{anonymize_ip:true});
window.cwMetric=function(name,params){try{gtag('event',name,params||{})}catch(_e){}};
(function(){
  var ref='direct';
  try{if(document.referrer)ref=new URL(document.referrer).hostname||'direct'}catch(_e){}
  var q=new URLSearchParams(location.search);
  window.cwMetric('meet_landing',{
    page_path:location.pathname,
    referrer_domain:ref,
    utm_source:(q.get('utm_source')||'').slice(0,100),
    utm_medium:(q.get('utm_medium')||'').slice(0,100),
    utm_campaign:(q.get('utm_campaign')||'').slice(0,120),
    utm_content:(q.get('utm_content')||'').slice(0,120),
    utm_term:(q.get('utm_term')||'').slice(0,120)
  });
  document.addEventListener('click',function(e){
    var a=e.target.closest&&e.target.closest('a[href]');
    if(!a)return;
    try{
      var u=new URL(a.href,location.href);
      window.cwMetric(u.origin===location.origin?'meet_navigation_click':'meet_outbound_click',{
        link_domain:u.hostname,
        link_path:u.pathname,
        link_text:(a.textContent||'').trim().replace(/\\s+/g,' ').slice(0,80)
      });
    }catch(_e){}
  },true);
})();
</script>`;

const BASE_CSS = `
:root{color-scheme:light;--bg:#f5f7f6;--card:#fff;--ink:#17211f;--muted:#66736f;--line:#dfe6e3;--soft:#eef5f2;--brand:#176b62;--brand-dark:#0d5049;--brand-soft:#e7f4f1;--danger:#a33b3b;--shadow:0 24px 70px rgba(27,54,47,.12)}
*{box-sizing:border-box}
html{background:var(--bg)}
body{margin:0;min-height:100vh;background:linear-gradient(180deg,#f8faf9 0,#f1f5f3 100%);color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif;font-size:15px}
a{color:var(--brand)}
.top{height:66px;display:flex;align-items:center;justify-content:space-between;width:min(1120px,calc(100% - 34px));margin:auto}
.brand{font-size:15px;font-weight:800;letter-spacing:.02em;color:var(--ink);text-decoration:none}.brand b{color:var(--brand)}
.slogan{font-size:12px;font-weight:700;color:var(--muted);letter-spacing:.02em}
.shell{width:min(1080px,calc(100% - 28px));margin:0 auto;padding:20px 0 64px}
.hero{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:24px;align-items:end;margin:12px 0 22px}.hero h1{margin:7px 0 8px;font-size:clamp(30px,5vw,45px);line-height:1.06;letter-spacing:-.035em}.hero p{margin:0;color:var(--muted);max-width:700px;line-height:1.62}
.eyebrow{font-size:12px;font-weight:750;color:var(--brand);letter-spacing:.035em}
.host{display:flex;align-items:center;gap:12px;padding:10px 13px;border:1px solid var(--line);border-radius:14px;background:#fff}.avatar{display:grid;place-items:center;width:42px;height:42px;border-radius:50%;background:var(--brand);color:#fff;font-size:13px;font-weight:800}.host strong{display:block;font-size:14px}.host span{display:block;margin-top:2px;color:var(--muted);font-size:12px}
.grid{display:grid;grid-template-columns:minmax(0,1.15fr) minmax(340px,.85fr);border:1px solid var(--line);border-radius:22px;background:var(--card);box-shadow:var(--shadow);overflow:hidden}
.panel{background:#fff;min-width:0}.grid>.panel:first-child{border-right:1px solid var(--line)}.panel-head{padding:22px 24px 16px;display:flex;justify-content:space-between;gap:14px;align-items:center}.panel-head h2{margin:0;font-size:18px}.meta{font-size:12px;color:var(--muted)}
.calendar-body{padding:0 24px 26px}.days{display:grid;grid-template-columns:repeat(7,minmax(82px,1fr));gap:8px;margin-bottom:24px;overflow:auto;padding:4px 1px 8px}
.day{appearance:none;border:1px solid var(--line);border-radius:12px;background:#fff;color:var(--ink);padding:12px 9px;text-align:center;cursor:pointer;min-width:82px;transition:.15s ease}.day:hover{border-color:#94bdb5;background:#fbfdfc}.day.active{border-color:var(--brand);background:var(--brand-soft);box-shadow:0 0 0 1px var(--brand)}
.day .dow{display:block;color:var(--muted);font-size:11px;font-weight:700}.day .date{display:block;margin-top:5px;font-size:16px;font-weight:800}.day .count{display:block;margin-top:4px;color:var(--muted);font-size:10px}
.slot-title{display:flex;align-items:center;justify-content:space-between;margin:0 0 12px}.slot-title strong{font-size:15px}.slots{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}
.slot{appearance:none;border:1px solid #b7ccc6;border-radius:10px;background:#fff;color:var(--brand-dark);padding:12px 8px;font-size:14px;font-weight:750;cursor:pointer;transition:.14s ease}.slot:hover{border-color:var(--brand);background:var(--brand-soft)}.slot.selected{border-color:var(--brand);background:var(--brand);color:#fff}
.empty{padding:30px 14px;color:var(--muted);text-align:center;background:var(--soft);border-radius:12px}
.details{padding:24px;display:grid;gap:16px}.selection{padding:15px 16px;border:1px solid var(--line);border-radius:13px;background:var(--soft)}.selection .label{font-size:11px;font-weight:750;color:var(--muted)}.selection .value{margin-top:6px;font-size:15px;font-weight:750;line-height:1.45}.selection .sub{margin-top:4px;color:var(--muted);font-size:12px}
.form{display:grid;gap:12px}.field{display:grid;gap:6px}.field label{font-size:13px;font-weight:700}.optional{color:var(--muted);font-weight:500}.field input,.field select,.field textarea{width:100%;border:1px solid #cfdad6;border-radius:10px;background:#fff;color:var(--ink);padding:11px 12px;font:inherit;outline:none}.field input:focus,.field select:focus,.field textarea:focus{border-color:var(--brand);box-shadow:0 0 0 3px rgba(23,107,98,.12)}.field textarea{min-height:78px;resize:vertical}.two{display:grid;grid-template-columns:1fr 1fr;gap:10px}
.button{appearance:none;border:1px solid var(--brand);border-radius:10px;background:var(--brand);color:#fff;padding:12px 16px;font:750 14px/1.2 Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",Arial,sans-serif;cursor:pointer;text-align:center}.button:hover{background:var(--brand-dark)}.button:disabled{opacity:.45;cursor:not-allowed}.button.secondary{background:#fff;color:var(--brand);border-color:#a9c6c0}.button.secondary:hover{background:var(--brand-soft)}.button.danger{background:#fff;color:var(--danger);border-color:#ddb8b8}
.status{display:none;padding:11px 12px;border-radius:10px;color:var(--muted);font-size:13px;line-height:1.45}.status[data-state]{display:block;background:var(--soft)}.status[data-state=success]{color:#195d45;background:#e9f6ef}.status[data-state=error]{color:#8a2f2f;background:#fff0f0}
.fine{color:var(--muted);font-size:11px;line-height:1.55}.rail{display:flex;gap:8px;flex-wrap:wrap;margin-top:15px}.chip{padding:7px 10px;border:1px solid var(--line);border-radius:999px;color:var(--muted);font-size:11px;background:#fff}.chip b{color:var(--ink)}
.success-card{max-width:720px;margin:30px auto 0;padding:32px;border:1px solid var(--line);border-radius:20px;background:#fff;box-shadow:var(--shadow)}.success-card h2{font-size:28px;margin:8px 0 12px}.success-card p{color:var(--muted);line-height:1.65}.actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:20px}.actions a{text-decoration:none}.hidden{display:none!important}.loading{color:var(--muted);padding:24px;text-align:center}
.manage-card{max-width:760px;margin:24px auto;border:1px solid var(--line);border-radius:20px;background:#fff;box-shadow:var(--shadow);overflow:hidden}.manage-meta{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:18px 0}.kv{padding:13px;border:1px solid var(--line);border-radius:11px;background:var(--soft)}.kv small{display:block;color:var(--muted);font-size:11px;font-weight:700}.kv strong{display:block;margin-top:6px;font-size:14px;line-height:1.45}
.room{max-width:680px;margin:24px auto;text-align:center;padding:48px 28px;border:1px solid var(--line);border-radius:20px;background:#fff;box-shadow:var(--shadow)}.room .orb{width:72px;height:72px;margin:0 auto 18px;border-radius:50%;display:grid;place-items:center;background:var(--brand);color:#fff;font-size:20px;font-weight:800}.room p{max-width:560px;margin:0 auto;color:var(--muted);line-height:1.65}
@media(max-width:860px){.hero{grid-template-columns:1fr}.host{justify-self:start}.grid{grid-template-columns:1fr}.grid>.panel:first-child{border-right:0;border-bottom:1px solid var(--line)}.days{grid-template-columns:repeat(7,92px)}}
@media(max-width:560px){.top{height:58px;width:min(100% - 22px,1120px)}.slogan{display:none}.shell{width:min(100% - 16px,1080px);padding:10px 0 34px}.hero{margin-top:4px}.hero h1{font-size:30px}.panel-head,.calendar-body,.details{padding-left:16px;padding-right:16px}.slots{grid-template-columns:1fr 1fr}.two,.manage-meta{grid-template-columns:1fr}.actions{flex-direction:column}.actions .button{width:100%}}
`;

function topBar() {
  return `<header class="top"><a class="brand" href="https://www.clintware.com/">CLINT<b>WARE</b>™</a><span class="slogan">30 min · Google Meet</span></header>`;
}

export function bookingPage() {
  return `<!doctype html><html lang="en"><head>${ANALYTICS_HEAD}<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#f5f7f6"><meta name="robots" content="noindex,nofollow"><title>Meet with Clinton | Clintware™</title><style>${BASE_CSS}</style></head><body>${topBar()}<main class="shell"><section class="hero"><div><span class="eyebrow">Meet with Clinton</span><h1>Find a time that works.</h1><p>Choose a time in your timezone. Once you book, Google Calendar sends the invitation and Google Meet link automatically.</p><div class="rail"><span class="chip"><b>${CONFIG.durationMinutes} min</b></span><span class="chip"><b>Google Meet</b></span><span class="chip">Your local timezone</span><span class="chip">Easy reschedule or cancel</span></div></div><div class="host"><div class="avatar">CK</div><div><strong>Clinton Kosh</strong><span>Customer Success · AI systems · technical operations</span></div></div></section><section id="scheduler" class="grid"><div class="panel"><div class="panel-head"><h2>Choose a time</h2><span id="tz-label" class="meta">Detecting timezone…</span></div><div class="calendar-body"><div id="days" class="days"><div class="loading">Loading availability…</div></div><div class="slot-title"><strong id="slot-date">Select a day</strong><span id="slot-count" class="meta"></span></div><div id="slots" class="slots"></div></div></div><aside class="panel"><div class="panel-head"><h2>Your details</h2><span class="meta">Step 2 of 2</span></div><div class="details"><div class="selection"><span class="label">Selected time</span><div id="selected-time" class="value">Choose an available time</div><div id="host-time" class="sub"></div></div><form id="booking-form" class="form"><div class="two"><div class="field"><label for="name">Name</label><input id="name" autocomplete="name" required></div><div class="field"><label for="email">Email</label><input id="email" type="email" autocomplete="email" required></div></div><div class="field"><label for="company">Company <span class="optional">optional</span></label><input id="company" autocomplete="organization"></div><input id="purpose" type="hidden" value="Meeting"><div class="field"><label for="topic">Anything I should know? <span class="optional">optional</span></label><textarea id="topic" placeholder="Role, agenda, project, question, or anything useful before the call."></textarea></div><p id="status" class="status" role="status" aria-live="polite"></p><button id="submit" class="button" type="submit" disabled>Book meeting</button><div class="fine">Google Calendar will send the invitation and Google Meet link. You’ll also get a private link to reschedule or cancel. <a href="https://www.clintware.com/privacy/">Privacy</a>.</div></form></div></aside></section><section id="success" class="panel success-card hidden"></section></main><script>
(() => {
  const state={slots:[],groups:new Map(),selected:null,dateKey:null,tz:Intl.DateTimeFormat().resolvedOptions().timeZone||'America/Chicago'};
  const $=id=>document.getElementById(id); const days=$('days'),slots=$('slots'),form=$('booking-form'),status=$('status'),submit=$('submit');
  $('tz-label').textContent='Times shown in '+state.tz.replaceAll('_',' ');
  const dateFmt=new Intl.DateTimeFormat('en-US',{timeZone:state.tz,weekday:'short',month:'short',day:'numeric'});
  const dayFmt=new Intl.DateTimeFormat('en-US',{timeZone:state.tz,weekday:'short'});
  const numFmt=new Intl.DateTimeFormat('en-US',{timeZone:state.tz,month:'short',day:'numeric'});
  const longFmt=new Intl.DateTimeFormat('en-US',{timeZone:state.tz,weekday:'long',month:'long',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'});
  const hostFmt=new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'});
  function localDateKey(ms){const p=new Intl.DateTimeFormat('en-CA',{timeZone:state.tz,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(ms));const m=Object.fromEntries(p.map(x=>[x.type,x.value]));return m.year+'-'+m.month+'-'+m.day}
  function group(){state.groups=new Map();for(const slot of state.slots){const k=localDateKey(slot.startMs);if(!state.groups.has(k))state.groups.set(k,[]);state.groups.get(k).push(slot)}}
  function renderDays(){days.innerHTML='';const entries=[...state.groups.entries()].slice(0,14);if(!entries.length){days.innerHTML='<div class="empty">No open times are currently available.</div>';return}if(!state.dateKey)state.dateKey=entries[0][0];for(const [key,list] of entries){const d=new Date(list[0].startMs);const b=document.createElement('button');b.type='button';b.className='day'+(key===state.dateKey?' active':'');b.innerHTML='<span class="dow"></span><span class="date"></span><span class="count"></span>';b.querySelector('.dow').textContent=dayFmt.format(d);b.querySelector('.date').textContent=numFmt.format(d);b.querySelector('.count').textContent=list.length+' open';b.onclick=()=>{state.dateKey=key;state.selected=null;renderDays();renderSlots();renderSelection()};days.appendChild(b)}renderSlots()}
  function renderSlots(){slots.innerHTML='';const list=state.groups.get(state.dateKey)||[];$('slot-date').textContent=list.length?dateFmt.format(new Date(list[0].startMs)):'Select a day';$('slot-count').textContent=list.length?list.length+' available':'';for(const s of list){const b=document.createElement('button');b.type='button';b.className='slot'+(state.selected?.startMs===s.startMs?' selected':'');b.textContent=new Intl.DateTimeFormat('en-US',{timeZone:state.tz,hour:'numeric',minute:'2-digit'}).format(new Date(s.startMs));b.onclick=()=>{state.selected=s;window.cwMetric&&window.cwMetric('meet_slot_selected',{lead_time_hours:Math.max(0,Math.round((s.startMs-Date.now())/3600000))});renderSlots();renderSelection()};slots.appendChild(b)}}
  function renderSelection(){if(!state.selected){$('selected-time').textContent='Choose an available time';$('host-time').textContent='';submit.disabled=true;return}$('selected-time').textContent=longFmt.format(new Date(state.selected.startMs));$('host-time').textContent='Clinton: '+hostFmt.format(new Date(state.selected.startMs));submit.disabled=false}
  async function load(){try{const r=await fetch('/api/availability',{cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.error||'Availability unavailable');state.slots=data.slots||[];group();renderDays();renderSelection()}catch(e){days.innerHTML='<div class="empty">Availability could not be loaded. Email <a style="color:#b8f4ff" href="mailto:clint@clintware.com">clint@clintware.com</a>.</div>'}}
  form.addEventListener('submit',async e=>{e.preventDefault();if(!state.selected||!form.reportValidity())return;window.cwMetric&&window.cwMetric('meet_booking_submit',{purpose:$('purpose').value||'unknown'});submit.disabled=true;submit.textContent='Booking…';status.dataset.state='working';status.textContent='Reserving that time…';const payload={startMs:state.selected.startMs,timezone:state.tz,name:$('name').value,email:$('email').value,company:$('company').value,purpose:$('purpose').value,topic:$('topic').value};try{const r=await fetch('/api/book',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw new Error(data.error||'Booking failed');document.getElementById('scheduler').classList.add('hidden');const success=$('success');success.classList.remove('hidden');success.innerHTML='<span class="eyebrow">Confirmed</span><h2>You’re booked.</h2><p id="confirmed-time"></p><p id="delivery-note"></p><div class="actions"><a class="button" id="room-link" target="_blank" rel="noopener">Join Google Meet</a><a class="button secondary" id="google-link" target="_blank" rel="noopener">Open Google Calendar</a><a class="button secondary" id="manage-link">Reschedule or cancel</a></div>';success.querySelector('#confirmed-time').textContent=longFmt.format(new Date(data.booking.startMs));success.querySelector('#delivery-note').textContent=data.delivery&&data.delivery.google?'Google Calendar sent the invitation from clint@clintware.com. The Meet link is included in the event.':'The booking could not be verified with Google.';success.querySelector('#room-link').href=data.booking.meetUrl||data.booking.roomUrl;success.querySelector('#manage-link').href=data.booking.manageUrl;success.querySelector('#google-link').href=data.booking.googleEventUrl||data.booking.googleCalendarUrl;window.cwMetric&&window.cwMetric('meet_booking_success',{purpose:payload.purpose||'unknown'});window.scrollTo({top:0,behavior:'smooth'})}catch(err){window.cwMetric&&window.cwMetric('meet_booking_error',{error_code:String(err.message||'booking_failed').slice(0,80)});status.dataset.state='error';status.textContent=String(err.message||err);await load()}finally{submit.textContent='Book meeting';submit.disabled=!state.selected}});
  load();
})();
</script></body></html>`;
}

export function managePage(token) {
  const safeToken = JSON.stringify(String(token));
  return `<!doctype html><html lang="en"><head>${ANALYTICS_HEAD}<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#06080c"><meta name="robots" content="noindex,nofollow"><title>Manage booking | Clintware™</title><style>${BASE_CSS}</style></head><body>${topBar()}<main class="shell"><section class="panel manage-card"><div class="panel-head"><h2>Manage booking</h2><span class="meta">PRIVATE LINK</span></div><div id="manage" class="success-card"><div class="loading">Loading booking…</div></div></section></main><script>
(async()=>{const token=${safeToken},root=document.getElementById('manage'),tz=Intl.DateTimeFormat().resolvedOptions().timeZone||'America/Chicago';const fmt=new Intl.DateTimeFormat('en-US',{timeZone:tz,weekday:'long',month:'long',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'});let booking=null;async function getBooking(){const r=await fetch('/api/manage/'+encodeURIComponent(token),{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Booking not found');booking=d.booking;return d}function render(){root.innerHTML='<span class="eyebrow">Meet with Clinton</span><h2 id="title"></h2><div class="manage-meta"><div class="kv"><small>Status</small><strong id="status"></strong></div><div class="kv"><small>Your timezone</small><strong id="time"></strong></div><div class="kv"><small>Topic</small><strong id="topic"></strong></div><div class="kv"><small>Google Meet</small><strong><a id="room" style="color:#bdf7ff">Join Meet</a></strong></div></div><div id="manage-actions" class="actions"></div><div id="reschedule" class="hidden" style="margin-top:20px"><div class="field"><label for="newslot">Choose a new time</label><select id="newslot"></select></div><div class="actions"><button id="save" class="button">Save new time</button><button id="close" class="button secondary">Close</button></div></div><p id="msg" class="status" role="status"></p>';document.getElementById('title').textContent=booking.name;document.getElementById('status').textContent=booking.status;document.getElementById('time').textContent=fmt.format(new Date(booking.startMs));document.getElementById('topic').textContent=booking.topic;const room=document.getElementById('room');room.href=booking.roomUrl;const actions=document.getElementById('manage-actions');if(booking.status==='confirmed'){actions.innerHTML='<a class="button" id="join">Join Google Meet</a><button class="button secondary" id="reschedule-btn">Reschedule</button><button class="button danger" id="cancel-btn">Cancel booking</button>';document.getElementById('join').href=booking.roomUrl;document.getElementById('reschedule-btn').onclick=openReschedule;document.getElementById('cancel-btn').onclick=cancelBooking}else{actions.innerHTML='<a class="button secondary" href="/">Book another time</a>'}}
async function openReschedule(){const r=await fetch('/api/availability',{cache:'no-store'}),d=await r.json();const sel=document.getElementById('newslot');sel.innerHTML='';for(const s of d.slots||[]){if(s.startMs===booking.startMs)continue;const o=document.createElement('option');o.value=String(s.startMs);o.textContent=fmt.format(new Date(s.startMs));sel.appendChild(o)}document.getElementById('reschedule').classList.remove('hidden');document.getElementById('close').onclick=()=>document.getElementById('reschedule').classList.add('hidden');document.getElementById('save').onclick=saveReschedule}
async function saveReschedule(){const startMs=Number(document.getElementById('newslot').value),msg=document.getElementById('msg');msg.dataset.state='working';msg.textContent='Rescheduling…';const r=await fetch('/api/manage/'+encodeURIComponent(token)+'/reschedule',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({startMs,timezone:tz})});const d=await r.json();if(!r.ok){msg.dataset.state='error';msg.textContent=d.error||'Could not reschedule';return}booking=d.booking;window.cwMetric&&window.cwMetric('meet_reschedule_success');msg.dataset.state='success';msg.textContent='Booking updated.';render()}
async function cancelBooking(){if(!confirm('Cancel this meeting?'))return;const msg=document.getElementById('msg');msg.dataset.state='working';msg.textContent='Canceling…';const r=await fetch('/api/manage/'+encodeURIComponent(token)+'/cancel',{method:'POST'});const d=await r.json();if(!r.ok){msg.dataset.state='error';msg.textContent=d.error||'Could not cancel';return}booking=d.booking;window.cwMetric&&window.cwMetric('meet_cancel_success');render()}
try{await getBooking();window.cwMetric&&window.cwMetric('meet_manage_view',{status:booking.status||'unknown'});render()}catch(e){root.innerHTML='<span class="eyebrow">Booking</span><h2>That manage link is not valid.</h2><p>Use the link from your confirmation email or book a new time.</p><div class="actions"><a class="button secondary" href="/">Open scheduler</a></div>'}})();
</script></body></html>`;
}

export function roomPage(roomCode) {
  const target = `https://meet.jit.si/Clintware-${encodeURIComponent(roomCode)}`;
  return `<!doctype html><html lang="en"><head>${ANALYTICS_HEAD}<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#06080c"><meta name="robots" content="noindex,nofollow"><title>Clintware meeting room</title><style>${BASE_CSS}</style></head><body>${topBar()}<main class="shell"><section class="room"><div class="orb">CK</div><span class="eyebrow">Clintware Room</span><h1>Ready when you are.</h1><p>This booking has its own private room name. Opening the room launches the browser-based video session in a new tab.</p><div class="actions" style="justify-content:center"><a class="button" href="${escapeHtml(target)}" target="_blank" rel="noopener noreferrer">Launch video room</a><a class="button secondary" href="/">Back to scheduler</a></div></section></main></body></html>`;
}
