import type {
  AssumptionToggle,
  Challenge,
  CustomerWorkspace,
  Organization,
  SkillPack,
} from "./types";

export const ORG: Organization = {
  id: "org-n7",
  name: "Neuron Seven",
  productTitle: "N7 Customer Value OS",
  subtitle: "Neuron7 Case Operating Console",
};

export const OPERATING_THESIS =
  "The customer did not buy a connector. They bought a measurable business outcome.";

export const EXECUTIVE_FRAMING =
  "I would treat this as a live Week-1 customer recovery, not a slide exercise. We have a valid Year-1 outcome, 50% faster resolution, but a newly discovered hard go-live dependency: SAP manuals, with an 8-to-10-week connector estimate against a 6-to-8-week commitment. My plan does four things: make the SAP critical path explicit, parallelize every safe workstream, reset the customer once with evidence rather than optimism, and instrument adoption, quality, and ROI before launch so value is provable afterward.";

export const PLANNING_BOUNDARY_TEXT =
  "W10 is a planning boundary based on the current Engineering estimate, not a new customer commitment. The committed date gets reset only after Engineering validates architecture, assumptions, milestones, test scope, dependencies, and confidence.";

export const FINAL_POSITIONING =
  "I operate at the boundary between customer outcomes, technical implementation, and internal execution. My job is not simply to keep the customer happy. It is to turn what was sold into an implemented, adopted, measurable business outcome, and to convert what we learn into a stronger system for the next customer.";

export const DEFENSE_50_PERCENT =
  "The 50% outcome is measured against a customer-approved baseline using a stable cohort and an agreed start/stop timestamp definition. I would use median cycle time for the typical experience and a tail metric such as P75 to ensure we are not hiding difficult cases.";

export const CORE_PRINCIPLES: string[] = [
  "Surface the SAP constraint immediately, without blame.",
  "Preserve customer trust by resetting once, with evidence.",
  "Treat SAP as the explicit critical path.",
  "Parallelize every safe non-SAP workstream.",
  "Never pressure Engineering into an unsupported date.",
  "Never redefine 'go-live' for optics.",
  "Instrument adoption, quality and ROI before production.",
  "Convert a discovery failure into a reusable presales readiness control.",
];

export const GO_LIVE_GATES: { label: string; detail: string; met: boolean }[] = [
  {
    label: "SAP manuals available",
    detail: "Ingested, current, permissioned, validated by customer SME.",
    met: false,
  },
  {
    label: "Salesforce content available",
    detail: "KB articles, technical bulletins, job aids searchable and current.",
    met: false,
  },
  { label: "SSO / RBAC working", detail: "Identity inputs validated end to end.", met: false },
  {
    label: "Content current and permissioned",
    detail: "Freshness and entitlement checks pass per source.",
    met: false,
  },
  { label: "Full-scope UAT passed", detail: "SAP + Salesforce scope, not partial.", met: false },
  {
    label: "Quality / accuracy acceptance criteria passed",
    detail: "Agreed with customer before launch, measured on golden queries.",
    met: false,
  },
  { label: "No critical blockers", detail: "RAID has no open critical item.", met: false },
  {
    label: "Named owners sign readiness",
    detail: "Customer, Engineering, CS/Implementation, Security.",
    met: false,
  },
];

export const RECOVERY_OPTIONS = [
  {
    id: "A",
    title: "Accelerated",
    boundary: "W8",
    summary:
      "W8 only if Engineering validates safe parallelism and compression, and the customer accepts lower schedule buffer.",
    guardrail: "Never force Engineering to make W8 happen.",
    recommended: false,
  },
  {
    id: "B",
    title: "Rebaseline",
    boundary: "W10 planning boundary",
    summary:
      "W10 planning boundary based on the validated Engineering range. All parallel work continues and acceptance quality is protected.",
    guardrail: "Base planning model for this case.",
    recommended: true,
  },
  {
    id: "C",
    title: "Approved temporary / pilot",
    boundary: "Conditional",
    summary:
      "Only if Product, Security, Engineering and the customer approve a supported temporary content path; pilot or non-production cohort only if appropriate.",
    guardrail:
      "Never invent a workaround. Never call an unsupported partial solution production go-live.",
    recommended: false,
  },
];

export const DECISION_TRIGGERS = [
  {
    gate: "W2",
    question:
      "Has Engineering validated architecture, assumptions, milestones, dependencies and confidence?",
    ifNo: "Escalate internally before resetting the customer date.",
  },
  {
    gate: "W6",
    question: "Is feature-complete still consistent with W10 UAT?",
    ifNo: "Trigger a leadership priority / scope / sequencing decision.",
  },
  {
    gate: "W8",
    question: "Can integration and resilience testing still support W10 full UAT?",
    ifNo: "Trigger an executive decision before the customer is surprised.",
  },
  {
    gate: "W10",
    question: "Do acceptance gates pass?",
    ifNo: "Explicit date / scope / priority / risk-acceptance decision. No silent slip.",
  },
];

export const GOVERNANCE = [
  {
    owner: "Engineering",
    owns: "Build",
    items: [
      "Architecture",
      "Code",
      "Testing",
      "Technical estimate",
      "Technical milestone state",
      "Technical risk",
    ],
  },
  {
    owner: "CS / Implementation",
    owns: "Dependency",
    items: [
      "Integrated customer plan",
      "RAID",
      "Decision log",
      "Customer communication",
      "Dependency translation",
      "Escalation triggers",
      "UAT coordination",
      "Adoption plan",
      "ROI narrative",
    ],
  },
  {
    owner: "Customer",
    owns: "Inputs",
    items: [
      "Access",
      "SAP / SFDC SMEs",
      "SSO / identity inputs",
      "Data readiness",
      "Content validation",
      "Workflow acceptance",
    ],
  },
  {
    owner: "Leadership",
    owns: "Tradeoffs",
    items: [
      "Cross-team priority conflicts",
      "Exceptions",
      "Risk tradeoffs",
      "Business outcome review",
    ],
  },
];

export const CADENCE = [
  "Twice-weekly internal SAP critical-path sync",
  "Weekly customer implementation review",
  "Leadership by exception and decision, not raw task lists",
  "Post-launch weekly operating review",
  "Monthly trend review",
  "QBR executive value review",
];

export const READINESS_ROOT_CAUSE =
  "The system allowed a customer-committed date before integration readiness was validated.";

export const READINESS_RULE =
  "An unknown or custom connector blocks a customer-committed date until Solution/Engineering review or a documented exception approval.";

export const ROI_METHOD = [
  "Avoided support interactions = eligible issues resolved without call-center escalation.",
  "Support hours saved = avoided calls × average handling time.",
  "Labor value = saved hours × Finance-approved loaded labor rate.",
  "All monetary assumptions must be customer/Finance approved. Never invent dollar ROI as fact.",
];

export const TRIAGE_LAYERS = [
  {
    step: 1,
    title: "Validate the metric",
    prompts: [
      "Which definition of accuracy: SME correctness, top-result relevance, successful session, or user survey?",
      "Same baseline method, query population, product families and window as before?",
    ],
  },
  {
    step: 2,
    title: "Blast radius",
    prompts: [
      "SAP vs Salesforce content",
      "Product family, manual, region, role, query type, cohort, date, version",
    ],
  },
  {
    step: 3,
    title: "Reproduce with versioned golden query",
    prompts: [
      "Expected result vs returned result",
      "Source doc, timestamp, permissions, content version, model/config version if available",
    ],
  },
  {
    step: 4,
    title: "Source / data",
    prompts: [
      "Missing or stale manuals, duplicate versions, metadata, structure, parsing",
      "Incomplete ingestion, encoding/OCR if relevant, freshness",
    ],
  },
  {
    step: 5,
    title: "Connector / pipeline",
    prompts: [
      "Failures, partial sync, indexing lag, pagination, retries",
      "Ingestion errors, permission filters",
    ],
  },
  {
    step: 6,
    title: "Config / access",
    prompts: ["Ranking and configuration, RBAC, mappings", "Source weighting, entitlements"],
  },
  {
    step: 7,
    title: "User / query",
    prompts: [
      "Terminology shifts, new product lines, new users",
      "Query complexity, training gaps",
    ],
  },
  {
    step: 8,
    title: "Retrieval / model",
    prompts: [
      "Only after prior layers are ruled out and correct content is indexed, permissioned and exists but retrieval still fails",
    ],
  },
];

export const TRIAGE_KEY_DIAGNOSTIC =
  "If SAP degrades while Salesforce stays stable, prioritize SAP source → connector → ingestion → parsing → metadata → indexing before any general model hypothesis.";

export const RED_FLAG_PHRASES = [
  "Sales screwed up",
  "Engineering is late",
  "We'll definitely make 8 weeks",
  "We can just launch without SAP",
  "The AI is wrong",
  "The customer data is bad",
];

export const SKILL_PACKS: SkillPack[] = [
  {
    id: "sp-sfdc",
    name: "Salesforce Admin",
    scope: "Service Cloud content model, Field Service work orders, permissions and profiles.",
    strengths: ["Content model questions", "Entitlement/permission mapping", "Sandbox vs prod"],
    limits: "No access to the customer org. Answers are structural, not configuration truth.",
  },
  {
    id: "sp-net",
    name: "Network Administration",
    scope: "Firewalls, trust boundaries, egress rules, latency and connectivity checks.",
    strengths: ["Topology questions", "Boundary review", "Connectivity failure triage"],
    limits: "Cannot test the customer network. Suggests checks, does not perform them.",
  },
  {
    id: "sp-sap",
    name: "SAP Integration",
    scope: "Product manual sources, extraction patterns, versioning and metadata hygiene.",
    strengths: ["Ingestion design questions", "Content versioning", "Parsing/metadata risks"],
    limits: "No SAP connector exists in this case. Nothing here implies a supported capability.",
  },
  {
    id: "sp-sec",
    name: "Security",
    scope: "SSO, RBAC, entitlement filtering, data handling and approval paths.",
    strengths: ["Identity inputs", "Permission-aware search", "Approval gates"],
    limits: "Cannot approve exceptions. Security sign-off remains human.",
  },
  {
    id: "sp-cs",
    name: "Customer Success",
    scope: "Stakeholder mapping, adoption plan, ROI narrative, escalation framing.",
    strengths: ["Message framing", "Risk translation", "Cadence design"],
    limits: "Drafts only. No message is sent without human approval.",
  },
  {
    id: "sp-n7",
    name: "Neuron7 Product / Implementation",
    scope: "Case and demo knowledge only, as supplied in this exercise.",
    strengths: ["Case facts", "Implementation sequencing", "Acceptance gates"],
    limits: "Case-scoped. No official Neuron7 internal APIs, data, policies or capabilities.",
  },
];

export const CHALLENGES: Challenge[] = [
  {
    id: "ch-1",
    prompt: "Preserve 6–8 weeks. What do you do?",
    thirtySecond:
      "I preserve the earliest achievable date, not the original one. SAP manuals are a must-have for go-live and Engineering says 8–10 weeks, so I parallelize everything non-SAP, run a design spike to validate the estimate, and reset once with evidence.",
    deeper:
      "Because the case says SAP is required for go-live and Engineering estimates 8–10 weeks. Preserving the date by ignoring the hard dependency would repeat the root cause. I would preserve the earliest achievable date after Engineering validates the plan.",
    evidence: { label: "Critical Path", section: "critical-path" },
    redFlag: "\"We'll definitely make 8 weeks.\"",
  },
  {
    id: "ch-2",
    prompt: "The customer refuses to accept a slip.",
    thirtySecond:
      "I make the tradeoffs explicit and let them choose, rather than hiding the dependency or manufacturing a date.",
    deeper:
      "I would make the tradeoffs explicit. They can choose a validated later full-scope date, an approved limited pilot if technically supportable, or an executive risk decision. I would not hide the dependency or manufacture a date.",
    evidence: { label: "SAP Recovery Options", section: "critical-path" },
    redFlag: "Agreeing to the original date to keep the meeting pleasant.",
  },
  {
    id: "ch-3",
    prompt: "Engineering says W10 is really W13.",
    thirtySecond:
      "W10 was always a planning boundary, not a promise. The W6 and W8 triggers exist so we escalate early and force an explicit scope, date or priority decision.",
    deeper:
      "W10 is not a promise. It is a planning boundary. The W6 and W8 trigger points exist specifically so we do not discover a miss at W10. If evidence says W10 is no longer credible, I escalate early and force an explicit scope/date/priority decision.",
    evidence: { label: "Decision Triggers", section: "implementation" },
    redFlag: "\"Engineering is late.\"",
  },
  {
    id: "ch-4",
    prompt: "SAP ingestion passes but accuracy is poor.",
    thirtySecond:
      "Ingestion success is not content correctness. I check freshness, duplicate versions, parsing, metadata and permission filters on the SAP segment before touching retrieval.",
    deeper:
      "I reproduce with versioned golden queries, segment SAP vs Salesforce, and walk the source, connector, configuration and query layers. Retrieval and model behavior are examined only after the content layers are ruled out.",
    evidence: { label: "Accuracy Triage", section: "accuracy-triage" },
    redFlag: "\"The AI is wrong.\"",
  },
  {
    id: "ch-5",
    prompt: "Adoption is high but resolution time is flat.",
    thirtySecond:
      "Adoption is not ROI. I check whether the searched content actually covers the high-frequency failure modes, and whether the cycle-time definition captures the work we changed.",
    deeper:
      "I segment by product family and query type, verify the start/stop timestamp definition, and look for a coverage gap: usage on content that does not map to the issues driving cycle time. Then I fix content coverage or the metric contract, whichever is wrong.",
    evidence: { label: "KPI Contract", section: "kpi-contract" },
    redFlag: "Reporting usage charts as value realization.",
  },
  {
    id: "ch-6",
    prompt: "The baseline is unusable.",
    thirtySecond:
      "Then we agree a defensible construction method before launch, not after. A cohort-matched sampled baseline with documented exclusions beats an unfalsifiable claim.",
    deeper:
      "I would run a baseline workshop, agree the source system and timestamp definition, and if the historical data is not reliable, construct a forward baseline over an agreed window with Finance and the customer signing the method and its confidence note.",
    evidence: { label: "ROI Workshop", section: "roi-workshop" },
    redFlag: "\"The customer data is bad.\"",
  },
  {
    id: "ch-7",
    prompt: "Salesforce is fine but SAP degrades.",
    thirtySecond:
      "That asymmetry is the diagnostic. I prioritize SAP source, connector, ingestion, parsing, metadata and indexing before any general model hypothesis.",
    deeper: TRIAGE_KEY_DIAGNOSTIC,
    evidence: { label: "Accuracy Triage", section: "accuracy-triage" },
    redFlag: "Escalating to a model investigation first.",
  },
  {
    id: "ch-8",
    prompt: "The CFO challenges the ROI.",
    thirtySecond:
      "I measure first and monetize second. Avoided interactions and hours saved are ours to measure; the loaded labor rate is Finance's to approve.",
    deeper:
      "Avoided support interactions are eligible issues resolved without call-center escalation. Hours saved are avoided calls times average handling time. Labor value uses a Finance-approved loaded rate. Every monetary assumption is customer or Finance approved; I do not invent dollar ROI as fact.",
    evidence: { label: "ROI Workshop", section: "roi-workshop" },
    redFlag: "Quoting a dollar figure with no approved rate behind it.",
  },
  {
    id: "ch-9",
    prompt: "This process feels too heavy for a startup.",
    thirtySecond:
      "It is deliberately light: one critical path, one RAID and decision log, a few evidence gates, automation where it is safe.",
    deeper:
      "The controls are intentionally lightweight: one critical-path view, one RAID/decision log, a few evidence gates, and automation where possible. The goal is to reduce status chasing and surprise escalation, not add bureaucracy.",
    evidence: { label: "RACI / Governance", section: "raci" },
    redFlag: "Defending process for its own sake.",
  },
  {
    id: "ch-10",
    prompt: "Isolate model vs data exactly.",
    thirtySecond:
      "Reproduce with a versioned golden query. If the correct document is present, current, parsed and permissioned and retrieval still misses it, only then is it a retrieval problem.",
    deeper:
      "I don't assume the model. That is the point of the triage. I reproduce, segment, inspect source freshness and parsing, check ingestion, permissions, and configuration, then isolate retrieval/model behavior only after those are ruled out.",
    evidence: { label: "Accuracy Triage", section: "accuracy-triage" },
    redFlag: "\"The AI is wrong.\"",
  },
  {
    id: "ch-11",
    prompt: "Answer in 30 seconds: what is your plan?",
    thirtySecond: EXECUTIVE_FRAMING,
    deeper:
      "Make the SAP critical path explicit, parallelize every safe workstream, reset the customer once with evidence, and instrument adoption, quality and ROI before launch.",
    evidence: { label: "Executive Summary", section: "executive-summary" },
    redFlag: "Opening with the tooling instead of the judgment.",
  },
  {
    id: "ch-12",
    prompt: "Why a design spike instead of just starting the build?",
    thirtySecond:
      "The 8–10 weeks is initial feedback. The spike converts it into a defensible plan before it becomes a customer commitment.",
    deeper:
      "The 8–10 weeks is initial feedback. Before converting that into a customer commitment, I want architecture, assumptions, milestones, test scope, external dependencies, and confidence documented. The spike validates the estimate; it is not idle waiting.",
    evidence: { label: "Implementation", section: "implementation" },
    redFlag: "Treating the spike as waiting time.",
  },
  {
    id: "ch-13",
    prompt: "Why not go live on Salesforce first?",
    thirtySecond:
      "I will use Salesforce to de-risk configuration, UAT, adoption and telemetry, but that is not production go-live.",
    deeper:
      "I can use Salesforce to de-risk configuration, UAT, adoption, and telemetry, but I would not call that production go-live because the case explicitly makes SAP manuals a must-have for the technician workflow.",
    evidence: { label: "Readiness Gate", section: "readiness-gate" },
    redFlag: "\"We can just launch without SAP.\"",
  },
  {
    id: "ch-14",
    prompt: "How much of this did AI do?",
    thirtySecond:
      "I use AI the way I would on the job: to accelerate research, structure and production. The judgment is mine.",
    deeper:
      "Yes. I use AI the way I would on the job: to accelerate research, structure, QA, and repeatable production. The assumptions, tradeoffs, customer stance, and decisions are mine, and I can defend every line.",
    evidence: { label: "Architecture & Assumptions", section: "architecture" },
    redFlag: "Overclaiming autonomous capability.",
  },
];

export const ASSUMPTION_TOGGLES: AssumptionToggle[] = [
  {
    id: "as-sap-12",
    label: "SAP estimate becomes 12 weeks",
    description: "Engineering's validated range moves from 8–10 to 12 weeks.",
    planImpact:
      "Planning boundary moves from W10 to W12 with hypercare at W13–W14. Parallel workstreams are unchanged and finish early; UAT scope splits into Salesforce dry-run at W8 and full-scope UAT after SAP ingestion.",
    riskImpact:
      "Schedule risk rises to high. Adoption risk rises because trained technicians wait longer for the full workflow.",
    recommendedDecision:
      "Trigger the W2 escalation path before any customer date change; present Option B rebaselined, with Option C pilot only if Product, Security and Engineering support a temporary content path.",
    evidenceNeeded:
      "Revised Engineering architecture note, milestone schedule, confidence statement, and the dependency list that drove the increase.",
  },
  {
    id: "as-refuse",
    label: "Customer rejects any timeline change",
    description: "Sponsor holds the original 6–8 week commercial expectation.",
    planImpact:
      "Plan itself does not change; the decision does. Options become validated later full-scope date, approved limited pilot, or documented executive risk acceptance.",
    riskImpact: "Commercial and trust risk rise to high; quality risk rises if scope is forced.",
    recommendedDecision:
      "Executive-to-executive conversation with the tradeoff sheet. No date is reaffirmed without Engineering validation.",
    evidenceNeeded:
      "Tradeoff comparison, acceptance gate list, and the written record of what SAP availability does to the technician workflow.",
  },
  {
    id: "as-nobaseline",
    label: "No usable resolution-time baseline",
    description: "Historical cycle-time data is incomplete or inconsistently stamped.",
    planImpact:
      "Add a baseline construction workstream in W1–W3; forward baseline over an agreed window with documented method.",
    riskImpact: "Value-proof risk rises to high. The 50% claim is unfalsifiable until fixed.",
    recommendedDecision:
      "Agree baseline construction method with customer and Finance in writing before go-live; record it in the metric contract confidence note.",
    evidenceNeeded:
      "Sampled cycle-time extract, timestamp definition, cohort definition, exclusion list, customer sign-off.",
  },
  {
    id: "as-sso",
    label: "SSO is delayed",
    description: "Identity inputs slip beyond the planned window.",
    planImpact:
      "SSO/RBAC validation moves onto the critical path alongside SAP; UAT cannot complete without permission-aware results.",
    riskImpact: "Technical and schedule risk rise; security risk if a temporary access path is proposed.",
    recommendedDecision:
      "Escalate as a customer-owned dependency with a named owner and date; no unsupported access workaround.",
    evidenceNeeded: "Identity owner commitment, test plan for permission-filtered results.",
  },
  {
    id: "as-pilot20",
    label: "Only 20 pilot users available",
    description: "Cohort for early validation shrinks from the planned population.",
    planImpact:
      "Pilot still useful for UAT and content validation; adoption telemetry becomes directional only.",
    riskImpact:
      "Measurement risk rises: a 20-user cohort cannot support a defensible 50% cycle-time claim.",
    recommendedDecision:
      "Keep the pilot for quality validation, and hold the ROI claim until the cohort reaches the agreed statistical floor.",
    evidenceNeeded: "Cohort definition, sample-size note, revised confidence statement in the KPI contract.",
  },
  {
    id: "as-priority",
    label: "Engineering priority drops",
    description: "The SAP connector loses relative priority against other work.",
    planImpact: "Critical path extends by the deprioritized duration; parallel work completes and waits.",
    riskImpact: "Schedule risk critical; trust risk high if not surfaced immediately.",
    recommendedDecision:
      "Leadership priority decision, framed as customer outcome exposure rather than team conflict.",
    evidenceNeeded: "Current critical-path view, customer commitment record, revenue/renewal exposure note.",
  },
  {
    id: "as-onefamily",
    label: "Accuracy issue affects one product family",
    description: "Reported degradation is isolated to a single family.",
    planImpact:
      "Triage narrows to that family's source content, versions and metadata; no platform-wide rollback.",
    riskImpact: "Quality risk contained; reputational risk in that technician segment.",
    recommendedDecision:
      "Fix content or metadata for the family and re-run the golden query set for that segment before declaring resolution.",
    evidenceNeeded: "Segmented accuracy comparison, versioned golden queries, source freshness report.",
  },
  {
    id: "as-bothdegrade",
    label: "Salesforce also degrades",
    description: "Both sources show the same degradation pattern.",
    planImpact:
      "Fault domain shifts away from a single source: examine shared pipeline, configuration, ranking and entitlement layers.",
    riskImpact: "Quality risk high and platform-wide; escalation packet required.",
    recommendedDecision:
      "Raise an engineering escalation with a full repro packet before speculating about the model.",
    evidenceNeeded: "Cross-source golden query results, config change log, ingestion and indexing telemetry.",
  },
  {
    id: "as-flatroi",
    label: "Adoption high but ROI flat",
    description: "Usage grows while cycle time does not move.",
    planImpact:
      "Add a coverage analysis workstream: map high-frequency failure modes to available content.",
    riskImpact: "Value risk high; renewal narrative weakens without a credible explanation.",
    recommendedDecision:
      "Report honestly with the coverage hypothesis and a dated plan, rather than presenting usage as value.",
    evidenceNeeded:
      "Query-to-issue mapping, content coverage gap list, cycle-time segmentation by query type.",
  },
];

export const AUTOMATION_CONCEPTS = [
  {
    id: "au-dep",
    title: "Dependency sync",
    flow: "Jira / Engineering milestone state → CS dependency summary + risk trigger",
    human: "A milestone change never changes a customer commitment automatically.",
  },
  {
    id: "au-value",
    title: "Value pipeline",
    flow: "SFDC timestamps + usage + interaction data → weekly metrics + confidence notes",
    human: "ROI interpretation stays human; the pipeline produces measurements, not claims.",
  },
  {
    id: "au-quality",
    title: "Quality intake",
    flow: "Structured complaint + telemetry → repro packet + fault-domain checklist",
    human: "Root-cause conclusion is human.",
  },
  {
    id: "au-readiness",
    title: "Readiness gate",
    flow: "CRM opportunity / implementation fields → connector review + exception workflow",
    human: "Exception approval is human and documented.",
  },
];

export const HUMAN_IN_THE_LOOP = {
  automationMay: [
    "Surface milestone changes",
    "Summarize risk",
    "Refresh demo dashboards",
    "Detect thresholds",
    "Prepare evidence",
  ],
  humanRequired: [
    "Customer commitments",
    "Timeline rebaseline",
    "Risk acceptance",
    "Executive communication",
    "ROI interpretation",
    "Root-cause conclusion",
    "Go / no-go",
  ],
};

export const SUCCESS_DEFINITION = [
  {
    label: "Delivery",
    text: "The SAP-dependent production launch passes acceptance without surprise escalation.",
  },
  {
    label: "Value",
    text: "The customer can demonstrate whether resolution cycle time is moving toward the Year-1 50% goal.",
  },
  {
    label: "System",
    text: "The next implementation starts with verified integrations, explicit dependencies and measurable ROI rather than rediscovering them after contract signature.",
  },
];

/* ------------------------------------------------------------------ */
/* Customer #1 — official case customer                                */
/* ------------------------------------------------------------------ */

const C1 = "cust-meridian";

export const CUSTOMER_ONE: CustomerWorkspace = {
  customer: {
    id: C1,
    name: "Healthcare Device Manufacturer (Customer #1)",
    industry: "Healthcare device manufacturing",
    isOfficialCase: true,
    health: "at-risk",
    stage: "discovery",
    targetOutcome: "Improve resolution cycle time by 50% by end of Year 1",
    users: "500+ field technicians, plus call-center / technical support agents",
    nextMilestone: "W2 — Engineering estimate validation and customer rebaseline decision",
    nextExecutiveTouch: "Week 2 sponsor review (recovery decision)",
    headline:
      "Week 1. Kickoff and discovery complete. SAP manual dependency discovered with no available connector.",
    createdAt: "Week 1",
    provenance: "case-fact",
  },
  stakeholders: [
    {
      id: "sh-1",
      customerId: C1,
      name: "Service Operations Executive Sponsor",
      role: "Executive sponsor (customer)",
      side: "customer",
      interest: "Year-1 50% resolution cycle-time improvement; predictable launch.",
      provenance: "working-assumption",
    },
    {
      id: "sh-2",
      customerId: C1,
      name: "Field Service Leader",
      role: "Owner of 500+ field technicians",
      side: "customer",
      interest: "Technicians get correct instructions without calling support.",
      provenance: "case-fact",
    },
    {
      id: "sh-3",
      customerId: C1,
      name: "Salesforce Platform Owner",
      role: "Service Cloud + Field Service admin",
      side: "customer",
      interest: "Content model, permissions, work order workflow integrity.",
      provenance: "case-fact",
    },
    {
      id: "sh-4",
      customerId: C1,
      name: "SAP Content Owner",
      role: "Product manual system of record",
      side: "customer",
      interest: "Manual versioning, access, extraction approach.",
      provenance: "case-fact",
    },
    {
      id: "sh-5",
      customerId: C1,
      name: "Identity / Security Lead",
      role: "SSO and RBAC",
      side: "customer",
      interest: "Permission-aware search, identity inputs.",
      provenance: "case-fact",
    },
    {
      id: "sh-6",
      customerId: C1,
      name: "Engineering Lead",
      role: "Connector architecture and build",
      side: "internal",
      interest: "Validated architecture, estimate confidence, test scope.",
      provenance: "working-assumption",
    },
    {
      id: "sh-7",
      customerId: C1,
      name: "CSM / Implementation Lead",
      role: "Integrated plan, RAID, decisions, customer communication",
      side: "internal",
      interest: "Outcome delivery and evidence-backed rebaseline.",
      provenance: "working-assumption",
    },
  ],
  outcomes: [
    {
      id: "out-1",
      customerId: C1,
      statement: "Improve resolution cycle time by 50%",
      horizon: "By end of Year 1",
      valueHypothesis:
        "Technicians get correct instructions directly and require fewer calls to support.",
      provenance: "case-fact",
    },
  ],
  kpis: [
    {
      id: "kpi-cycle",
      customerId: C1,
      name: "Resolution cycle time (median / P50)",
      kind: "lagging",
      unit: "minutes",
      baseline: "Pending customer-approved baseline",
      target: "50% reduction by end of Year 1",
      current: "Not yet measured (Week 1)",
      trend: "flat",
      goodDirection: "down",
      contract: {
        metricName: "Resolution cycle time (median)",
        businessDefinition:
          "Elapsed working time from issue intake to verified resolution for eligible field service issues.",
        numerator: "Sum of eligible case durations",
        denominator: "Count of eligible cases (median taken over the set)",
        cohort: "Field technicians in the agreed launch cohort",
        startTimestamp: "Work order / case created timestamp (customer-agreed field)",
        stopTimestamp: "Verified resolution timestamp (customer-agreed field)",
        baselineWindow: "Agreed pre-launch window, customer approved",
        comparisonWindow: "Rolling post-launch window of equal length",
        exclusions: "Parts-delay holds, customer-caused waits, duplicate/cancelled work orders",
        sourceSystem: "Salesforce Field Service / Service Cloud",
        sourceOwner: "Customer Salesforce platform owner",
        refreshCadence: "Weekly",
        confidenceNote:
          "Baseline method must be approved before launch; confidence is unestablished at Week 1.",
      },
      provenance: "case-fact",
    },
    {
      id: "kpi-p75",
      customerId: C1,
      name: "Resolution cycle time (P75 tail)",
      kind: "lagging",
      unit: "minutes",
      baseline: "Pending",
      target: "Directional improvement; no hidden hard cases",
      current: "Not yet measured",
      trend: "flat",
      goodDirection: "down",
      contract: {
        metricName: "Resolution cycle time (P75)",
        businessDefinition: "Tail metric ensuring difficult cases are not masked by the median.",
        numerator: "75th percentile of eligible case durations",
        denominator: "Eligible case set",
        cohort: "Same launch cohort as median metric",
        startTimestamp: "Same as median contract",
        stopTimestamp: "Same as median contract",
        baselineWindow: "Same as median contract",
        comparisonWindow: "Same as median contract",
        exclusions: "Same as median contract",
        sourceSystem: "Salesforce Field Service",
        sourceOwner: "Customer Salesforce platform owner",
        refreshCadence: "Weekly",
        confidenceNote: "Reported alongside median in every value review.",
      },
      provenance: "working-assumption",
    },
    {
      id: "kpi-wau",
      customerId: C1,
      name: "Weekly active field technicians",
      kind: "leading",
      unit: "technicians",
      baseline: "0 (pre-launch)",
      target: "Agreed cohort coverage at hypercare exit",
      current: "Illustrative demo series",
      trend: "up",
      goodDirection: "up",
      contract: {
        metricName: "Weekly active field technicians",
        businessDefinition: "Distinct technicians running at least one search in the week.",
        numerator: "Distinct active technician IDs",
        denominator: "Licensed technicians in cohort",
        cohort: "Launch cohort",
        startTimestamp: "Week start (customer timezone)",
        stopTimestamp: "Week end",
        baselineWindow: "N/A (new capability)",
        comparisonWindow: "Week over week",
        exclusions: "Admin and test accounts",
        sourceSystem: "Product usage telemetry",
        sourceOwner: "Implementation lead",
        refreshCadence: "Weekly",
        confidenceNote: "Adoption is a leading signal. It is not ROI.",
      },
      provenance: "illustrative",
    },
    {
      id: "kpi-deflect",
      customerId: C1,
      name: "Support-call deflection rate",
      kind: "leading",
      unit: "%",
      baseline: "Pending baseline workshop",
      target: "Agreed with customer before launch",
      current: "Illustrative demo series",
      trend: "up",
      goodDirection: "up",
      contract: {
        metricName: "Support-call deflection rate",
        businessDefinition:
          "Eligible issues resolved without escalation to the call center after a search session.",
        numerator: "Eligible issues resolved without call-center escalation",
        denominator: "Eligible issues in the cohort",
        cohort: "Launch cohort, eligible issue types only",
        startTimestamp: "Search session start",
        stopTimestamp: "Work order resolution",
        baselineWindow: "Agreed pre-launch window",
        comparisonWindow: "Rolling post-launch window",
        exclusions: "Issue types out of content scope; safety-mandated escalations",
        sourceSystem: "Salesforce + product telemetry join",
        sourceOwner: "Customer Salesforce owner + implementation lead",
        refreshCadence: "Weekly",
        confidenceNote: "Join logic must be reviewed with the customer before it is reported.",
      },
      provenance: "illustrative",
    },
    {
      id: "kpi-success",
      customerId: C1,
      name: "Successful session rate",
      kind: "leading",
      unit: "%",
      baseline: "N/A",
      target: "Agreed quality acceptance threshold",
      current: "Illustrative demo series",
      trend: "up",
      goodDirection: "up",
      contract: {
        metricName: "Successful session rate",
        businessDefinition:
          "Sessions where the technician opened a result and took a workflow action or marked it useful.",
        numerator: "Successful sessions",
        denominator: "All sessions",
        cohort: "Launch cohort",
        startTimestamp: "Session start",
        stopTimestamp: "Session end",
        baselineWindow: "N/A",
        comparisonWindow: "Week over week",
        exclusions: "Sessions under 3 seconds; admin accounts",
        sourceSystem: "Product usage telemetry",
        sourceOwner: "Implementation lead",
        refreshCadence: "Weekly",
        confidenceNote: "Definition of 'successful' is agreed with the customer, not assumed.",
      },
      provenance: "illustrative",
    },
    {
      id: "kpi-fresh",
      customerId: C1,
      name: "Source freshness",
      kind: "leading",
      unit: "% current",
      baseline: "Unknown at Week 1",
      target: "Agreed freshness SLA per source",
      current: "Illustrative demo series",
      trend: "flat",
      goodDirection: "up",
      contract: {
        metricName: "Source freshness",
        businessDefinition: "Share of indexed documents within the agreed freshness window.",
        numerator: "Documents within freshness window",
        denominator: "Indexed documents",
        cohort: "All in-scope content",
        startTimestamp: "Document last-modified",
        stopTimestamp: "Index timestamp",
        baselineWindow: "N/A",
        comparisonWindow: "Weekly",
        exclusions: "Archived/retired manuals",
        sourceSystem: "Ingestion pipeline",
        sourceOwner: "Engineering",
        refreshCadence: "Weekly",
        confidenceNote: "Freshness is the first thing to check in an accuracy complaint.",
      },
      provenance: "illustrative",
    },
  ],
  milestones: [
    {
      id: "ms-w1-scope",
      customerId: C1,
      week: "W1",
      title: "Confirm scope, stakeholders, decision rights",
      detail: "Named owners for every dependency; decision rights agreed in writing.",
      track: "governance",
      owner: "CS / Implementation",
      status: "in-progress",
      provenance: "case-fact",
    },
    {
      id: "ms-w1-roi",
      customerId: C1,
      week: "W1",
      title: "ROI baseline workshop",
      detail: "Agree metric definitions, cohort, timestamps, exclusions and data owners.",
      track: "parallel",
      owner: "CS / Implementation + Customer",
      status: "in-progress",
      provenance: "case-fact",
    },
    {
      id: "ms-w1-inv",
      customerId: C1,
      week: "W1",
      title: "Integration inventory",
      detail: "Salesforce Service Cloud, Salesforce Field Service, SAP manuals, SSO.",
      track: "parallel",
      owner: "CS / Implementation",
      status: "in-progress",
      provenance: "case-fact",
    },
    {
      id: "ms-w1-sso",
      customerId: C1,
      week: "W1",
      title: "SSO / RBAC / security inputs",
      detail: "Identity inputs collected; permission-aware search requirements captured.",
      track: "parallel",
      owner: "Customer Identity Lead",
      status: "planned",
      provenance: "case-fact",
    },
    {
      id: "ms-w1-owners",
      customerId: C1,
      week: "W1",
      title: "Identify data owners",
      detail: "Named owner per content source and per metric.",
      track: "governance",
      owner: "CS / Implementation",
      status: "in-progress",
      provenance: "case-fact",
    },
    {
      id: "ms-w12-spike",
      customerId: C1,
      week: "W1–W2",
      title: "Engineering SAP design spike / estimate validation",
      detail:
        "Architecture, assumptions, milestone schedule, test scope, dependencies and confidence documented.",
      track: "critical-path",
      owner: "Engineering",
      status: "in-progress",
      provenance: "case-fact",
    },
    {
      id: "ms-w12-accel",
      customerId: C1,
      week: "W1–W2",
      title: "Acceleration opportunities and external dependencies",
      detail: "Safe parallelism and compression identified; customer dependencies listed.",
      track: "critical-path",
      owner: "Engineering + CS",
      status: "planned",
      provenance: "case-fact",
    },
    {
      id: "ms-w2-reset",
      customerId: C1,
      week: "W2",
      title: "Customer recovery decision / rebaseline",
      detail: "One evidence-backed plan plus tradeoffs. Reset once, not repeatedly.",
      track: "governance",
      owner: "CS / Implementation + Leadership",
      status: "planned",
      provenance: "case-fact",
    },
    {
      id: "ms-sfdc",
      customerId: C1,
      week: "W2–W5",
      title: "Configure Salesforce connector and validate content quality",
      detail: "KB articles, technical bulletins, job aids; content currency and permissions.",
      track: "parallel",
      owner: "Implementation + Customer SFDC owner",
      status: "planned",
      provenance: "case-fact",
    },
    {
      id: "ms-uat-pack",
      customerId: C1,
      week: "W3–W6",
      title: "Representative query / UAT pack",
      detail: "Versioned golden queries per product family and source system.",
      track: "parallel",
      owner: "Implementation + Customer SMEs",
      status: "planned",
      provenance: "working-assumption",
    },
    {
      id: "ms-training",
      customerId: C1,
      week: "W4–W9",
      title: "Training and change management",
      detail: "Technician enablement, field champions, job-aid updates.",
      track: "parallel",
      owner: "CS / Implementation",
      status: "planned",
      provenance: "working-assumption",
    },
    {
      id: "ms-telemetry",
      customerId: C1,
      week: "W3–W7",
      title: "Telemetry / dashboard source lineage",
      detail: "Instrument adoption, quality and ROI before production.",
      track: "parallel",
      owner: "Implementation",
      status: "planned",
      provenance: "working-assumption",
    },
    {
      id: "ms-sap-design",
      customerId: C1,
      week: "W2–W4",
      title: "SAP connector design",
      detail: "Architecture validated in the spike; extraction, auth and versioning approach.",
      track: "critical-path",
      owner: "Engineering",
      status: "planned",
      provenance: "case-fact",
    },
    {
      id: "ms-sap-dev",
      customerId: C1,
      week: "W4–W8",
      title: "SAP connector development",
      detail: "Build against validated design; milestone state owned by Engineering.",
      track: "critical-path",
      owner: "Engineering",
      status: "planned",
      provenance: "case-fact",
    },
    {
      id: "ms-sap-test",
      customerId: C1,
      week: "W8",
      title: "Integration / resilience testing",
      detail: "W8 trigger: can testing still support W10 full UAT?",
      track: "critical-path",
      owner: "Engineering",
      status: "planned",
      provenance: "case-fact",
    },
    {
      id: "ms-sap-ingest",
      customerId: C1,
      week: "W8–W9",
      title: "Manual ingestion and content validation",
      detail: "Freshness, versions, metadata, parsing and permissions validated with SMEs.",
      track: "critical-path",
      owner: "Engineering + Customer SAP owner",
      status: "planned",
      provenance: "case-fact",
    },
    {
      id: "ms-uat",
      customerId: C1,
      week: "W9–W10",
      title: "Full-scope UAT",
      detail: "SAP + Salesforce scope. Partial UAT is not acceptance.",
      track: "critical-path",
      owner: "Customer + Implementation",
      status: "planned",
      provenance: "case-fact",
    },
    {
      id: "ms-gono",
      customerId: C1,
      week: "W10",
      title: "Go / no-go and production launch",
      detail: "Acceptance gates pass, or an explicit documented decision. No silent slip.",
      track: "critical-path",
      owner: "Leadership + Customer",
      status: "planned",
      provenance: "case-fact",
    },
    {
      id: "ms-hyper",
      customerId: C1,
      week: "W11–W12",
      title: "Hypercare",
      detail:
        "Issue triage, adoption tracking, cycle-time measurement, quality/drift watch, BAU transition.",
      track: "hypercare",
      owner: "CS / Implementation",
      status: "planned",
      provenance: "case-fact",
    },
  ],
  dependencies: [
    {
      id: "dep-sap",
      customerId: C1,
      name: "SAP product manuals available in search",
      owner: "Engineering + Customer SAP owner",
      type: "engineering",
      status: "blocked",
      blocksGoLive: true,
      note: "No SAP connector available in this case. Engineering initial estimate 8–10 weeks.",
      provenance: "case-fact",
    },
    {
      id: "dep-sfdc",
      customerId: C1,
      name: "Salesforce connector configuration",
      owner: "Implementation + Customer SFDC owner",
      type: "internal",
      status: "ready",
      blocksGoLive: true,
      note: "Existing connector ready; configuration and content validation proceed in parallel.",
      provenance: "case-fact",
    },
    {
      id: "dep-sso",
      customerId: C1,
      name: "SSO / RBAC inputs",
      owner: "Customer Identity Lead",
      type: "customer",
      status: "in-progress",
      blocksGoLive: true,
      note: "SSO included in scope. Permission-aware results required for UAT.",
      provenance: "case-fact",
    },
    {
      id: "dep-baseline",
      customerId: C1,
      name: "Approved cycle-time baseline",
      owner: "Customer Ops + Finance",
      type: "customer",
      status: "in-progress",
      blocksGoLive: false,
      note: "Blocks the value claim, not the launch. Must be agreed before production.",
      provenance: "working-assumption",
    },
    {
      id: "dep-sme",
      customerId: C1,
      name: "SAP and Salesforce SMEs for content validation",
      owner: "Customer",
      type: "customer",
      status: "not-started",
      blocksGoLive: true,
      note: "Needed for golden query validation and UAT sign-off.",
      provenance: "working-assumption",
    },
  ],
  risks: [
    {
      id: "risk-sap",
      customerId: C1,
      title: "SAP connector estimate (8–10 wks) exceeds commercial expectation (6–8 wks)",
      category: "schedule",
      impact: "high",
      likelihood: "high",
      mitigation:
        "Design spike to validate estimate; parallelize all non-SAP work; single evidence-backed rebaseline by W2.",
      owner: "CS / Implementation",
      trigger: "W2 gate: Engineering validation not complete or confidence low.",
      status: "open",
      provenance: "case-fact",
    },
    {
      id: "risk-trust",
      customerId: C1,
      title: "Customer trust erosion from a late or repeated date change",
      category: "commercial",
      impact: "high",
      likelihood: "medium",
      mitigation:
        "Reset once with evidence and tradeoffs; weekly milestone visibility against the validated path.",
      owner: "CS / Implementation",
      trigger: "Any second date change request.",
      status: "open",
      provenance: "working-assumption",
    },
    {
      id: "risk-baseline",
      customerId: C1,
      title: "No defensible baseline for the 50% outcome",
      category: "quality",
      impact: "high",
      likelihood: "medium",
      mitigation:
        "Baseline workshop in W1; documented cohort, timestamps and exclusions; Finance-approved rate for any monetary claim.",
      owner: "CS / Implementation + Customer Finance",
      trigger: "Baseline method not approved by W3.",
      status: "open",
      provenance: "working-assumption",
    },
    {
      id: "risk-content",
      customerId: C1,
      title: "SAP manual content quality (versions, parsing, metadata) degrades answers",
      category: "technical",
      impact: "high",
      likelihood: "medium",
      mitigation:
        "Content validation workstream with SMEs; versioned golden queries; freshness monitoring before launch.",
      owner: "Engineering + Customer SAP owner",
      trigger: "Golden query pass rate below agreed threshold in ingestion validation.",
      status: "open",
      provenance: "working-assumption",
    },
    {
      id: "risk-adopt",
      customerId: C1,
      title: "Adoption without measurable cycle-time change",
      category: "adoption",
      impact: "medium",
      likelihood: "medium",
      mitigation:
        "Coverage mapping of high-frequency failure modes to content; segmented cycle-time reporting.",
      owner: "CS / Implementation",
      trigger: "Two consecutive weeks of rising usage with flat median cycle time.",
      status: "monitoring",
      provenance: "working-assumption",
    },
    {
      id: "risk-sso",
      customerId: C1,
      title: "SSO / RBAC inputs slip and block permission-aware UAT",
      category: "technical",
      impact: "medium",
      likelihood: "medium",
      mitigation: "Named customer owner with a dated commitment; tracked as a go-live gate.",
      owner: "Customer Identity Lead",
      trigger: "No identity inputs by W4.",
      status: "open",
      provenance: "working-assumption",
    },
  ],
  decisions: [
    {
      id: "dec-1",
      customerId: C1,
      date: "W1",
      title: "Surface the SAP dependency immediately",
      decision:
        "Disclose the SAP connector gap to the customer in Week 1 with a plan, not after it becomes a missed date.",
      rationale:
        "Preserving trust requires early disclosure. Concealment repeats the root cause of the original commitment.",
      decidedBy: "CS / Implementation Lead",
      type: "human-decision",
      alternatives: "Wait for the spike result before telling the customer (rejected).",
      provenance: "human-decision",
    },
    {
      id: "dec-2",
      customerId: C1,
      date: "W1",
      title: "Run the Engineering design spike before any date reset",
      decision:
        "No new customer date is offered until architecture, assumptions, milestones, test scope, dependencies and confidence are documented.",
      rationale: "An 8–10 week initial estimate is feedback, not a plan.",
      decidedBy: "CS / Implementation + Engineering",
      type: "human-decision",
      alternatives: "Immediately commit to W10 (rejected — unvalidated).",
      provenance: "human-decision",
    },
    {
      id: "dec-3",
      customerId: C1,
      date: "W1",
      title: "Parallelize every safe non-SAP workstream",
      decision:
        "Salesforce configuration, content validation, SSO/RBAC, ROI baseline, UAT pack, training and telemetry proceed now.",
      rationale: "Reduces post-SAP tail; keeps momentum visible to the customer.",
      decidedBy: "CS / Implementation Lead",
      type: "human-decision",
      alternatives: "Sequential plan after SAP (rejected — wastes 8 weeks).",
      provenance: "human-decision",
    },
    {
      id: "dec-4",
      customerId: C1,
      date: "W2 (pending)",
      title: "Recovery option selection",
      decision:
        "Pending: Option A accelerated, Option B rebaseline to the W10 planning boundary, or Option C approved temporary/pilot path.",
      rationale: "Requires validated Engineering output and customer tradeoff conversation.",
      decidedBy: "Leadership + Customer sponsor",
      type: "pending",
      alternatives: "See SAP Recovery Options.",
      provenance: "human-decision",
    },
  ],
  raci: [
    {
      id: "raci-1",
      customerId: C1,
      activity: "SAP connector architecture and build",
      responsible: "Engineering",
      accountable: "Engineering Lead",
      consulted: "CS / Implementation, Customer SAP owner",
      informed: "Leadership, Customer sponsor",
      provenance: "working-assumption",
    },
    {
      id: "raci-2",
      customerId: C1,
      activity: "Integrated customer plan and RAID",
      responsible: "CS / Implementation",
      accountable: "CSM / Implementation Lead",
      consulted: "Engineering, Customer PM",
      informed: "Leadership",
      provenance: "working-assumption",
    },
    {
      id: "raci-3",
      customerId: C1,
      activity: "Customer communication and rebaseline",
      responsible: "CS / Implementation",
      accountable: "CSM / Implementation Lead",
      consulted: "Leadership, Engineering",
      informed: "Sales / Account team",
      provenance: "working-assumption",
    },
    {
      id: "raci-4",
      customerId: C1,
      activity: "SSO / RBAC inputs",
      responsible: "Customer Identity Lead",
      accountable: "Customer sponsor",
      consulted: "Engineering, Security",
      informed: "CS / Implementation",
      provenance: "working-assumption",
    },
    {
      id: "raci-5",
      customerId: C1,
      activity: "Content validation (SAP + Salesforce)",
      responsible: "Customer SMEs",
      accountable: "Customer Field Service Leader",
      consulted: "Implementation",
      informed: "Engineering",
      provenance: "working-assumption",
    },
    {
      id: "raci-6",
      customerId: C1,
      activity: "UAT coordination and acceptance",
      responsible: "CS / Implementation",
      accountable: "Customer sponsor",
      consulted: "Engineering, SMEs",
      informed: "Leadership",
      provenance: "working-assumption",
    },
    {
      id: "raci-7",
      customerId: C1,
      activity: "Go / no-go decision",
      responsible: "CS / Implementation (evidence)",
      accountable: "Leadership + Customer sponsor",
      consulted: "Engineering, Security",
      informed: "All",
      provenance: "working-assumption",
    },
    {
      id: "raci-8",
      customerId: C1,
      activity: "ROI interpretation and value review",
      responsible: "CS / Implementation",
      accountable: "Customer sponsor + Finance",
      consulted: "Customer Ops",
      informed: "Leadership",
      provenance: "working-assumption",
    },
  ],
  nodes: [
    {
      id: "n-tech",
      customerId: C1,
      label: "Field Technicians (500+)",
      kind: "endpoint",
      x: 80,
      y: 60,
      detail: "Mobile technicians executing work orders in the field.",
      provenance: "case-fact",
    },
    {
      id: "n-agents",
      customerId: C1,
      label: "Call-center / Support Agents",
      kind: "endpoint",
      x: 80,
      y: 220,
      detail: "Technical support agents handling escalations from technicians.",
      provenance: "case-fact",
    },
    {
      id: "n-sso",
      customerId: C1,
      label: "SSO / Identity Provider",
      kind: "identity",
      x: 340,
      y: 380,
      detail: "SSO included in scope. Drives permission-aware search.",
      provenance: "case-fact",
    },
    {
      id: "n-n7",
      customerId: C1,
      label: "Neuron7 Intelligent Search",
      kind: "saas",
      x: 360,
      y: 140,
      detail: "Unifies searchable content across platforms (case scope).",
      provenance: "case-fact",
    },
    {
      id: "n-sfdc-sc",
      customerId: C1,
      label: "Salesforce Service Cloud",
      kind: "saas",
      x: 640,
      y: 40,
      detail: "KB articles, technical bulletins, job aids.",
      provenance: "case-fact",
    },
    {
      id: "n-sfdc-fs",
      customerId: C1,
      label: "Salesforce Field Service",
      kind: "saas",
      x: 640,
      y: 160,
      detail: "Work orders and field workflow. Also the cycle-time source system.",
      provenance: "case-fact",
    },
    {
      id: "n-sap",
      customerId: C1,
      label: "SAP (Product Manuals)",
      kind: "saas",
      x: 640,
      y: 290,
      detail: "Must-have content for formal production go-live. No connector available in this case.",
      provenance: "case-fact",
    },
    {
      id: "n-conn-sfdc",
      customerId: C1,
      label: "Salesforce Connector (ready)",
      kind: "integration",
      x: 500,
      y: 100,
      detail: "Existing prebuilt connector, ready in this case.",
      provenance: "case-fact",
    },
    {
      id: "n-conn-sap",
      customerId: C1,
      label: "SAP Connector (not available)",
      kind: "integration",
      x: 500,
      y: 290,
      detail: "Custom build. Engineering initial estimate 8–10 weeks. Critical path.",
      provenance: "case-fact",
    },
  ],
  edges: [
    {
      id: "e-1",
      customerId: C1,
      from: "n-tech",
      to: "n-n7",
      label: "search for guidance",
      flow: "data",
      provenance: "case-fact",
    },
    {
      id: "e-2",
      customerId: C1,
      from: "n-agents",
      to: "n-n7",
      label: "agent search",
      flow: "data",
      provenance: "case-fact",
    },
    {
      id: "e-3",
      customerId: C1,
      from: "n-sso",
      to: "n-n7",
      label: "SSO / entitlements",
      flow: "auth",
      provenance: "case-fact",
    },
    {
      id: "e-4",
      customerId: C1,
      from: "n-n7",
      to: "n-conn-sfdc",
      label: "content sync",
      flow: "data",
      provenance: "case-fact",
    },
    {
      id: "e-5",
      customerId: C1,
      from: "n-conn-sfdc",
      to: "n-sfdc-sc",
      label: "KB / bulletins / job aids",
      flow: "data",
      provenance: "case-fact",
    },
    {
      id: "e-6",
      customerId: C1,
      from: "n-conn-sfdc",
      to: "n-sfdc-fs",
      label: "work order context",
      flow: "data",
      provenance: "case-fact",
    },
    {
      id: "e-7",
      customerId: C1,
      from: "n-n7",
      to: "n-conn-sap",
      label: "blocked dependency",
      flow: "data",
      provenance: "case-fact",
    },
    {
      id: "e-8",
      customerId: C1,
      from: "n-conn-sap",
      to: "n-sap",
      label: "product manuals (to be built)",
      flow: "data",
      provenance: "case-fact",
    },
  ],
  integrations: [
    {
      id: "int-sc",
      customerId: C1,
      system: "Salesforce Service Cloud",
      purpose: "KB articles, technical bulletins, job aids",
      connectorStatus: "prebuilt",
      authModel: "SSO / platform auth (customer confirmed inputs pending)",
      owner: "Customer Salesforce platform owner",
      blocksGoLive: true,
      provenance: "case-fact",
    },
    {
      id: "int-fs",
      customerId: C1,
      system: "Salesforce Field Service",
      purpose: "Work orders and field workflow; cycle-time source",
      connectorStatus: "prebuilt",
      authModel: "SSO / platform auth",
      owner: "Customer Salesforce platform owner",
      blocksGoLive: true,
      provenance: "case-fact",
    },
    {
      id: "int-sap",
      customerId: C1,
      system: "SAP",
      purpose: "Product manuals — must-have for formal production go-live",
      connectorStatus: "not-available",
      authModel: "To be defined in design spike",
      owner: "Engineering + Customer SAP owner",
      blocksGoLive: true,
      provenance: "case-fact",
    },
    {
      id: "int-sso",
      customerId: C1,
      system: "SSO",
      purpose: "Identity and permission-aware search",
      connectorStatus: "prebuilt",
      authModel: "SSO included in scope",
      owner: "Customer Identity Lead",
      blocksGoLive: true,
      provenance: "case-fact",
    },
  ],
  adoption: [
    {
      id: "ad-1",
      customerId: C1,
      week: "W11",
      activeTechnicians: 96,
      searches: 1840,
      successfulSessionRate: 61,
      deflectionRate: 12,
      medianCycleTimeMin: 148,
      p75CycleTimeMin: 236,
    },
    {
      id: "ad-2",
      customerId: C1,
      week: "W12",
      activeTechnicians: 174,
      searches: 3620,
      successfulSessionRate: 66,
      deflectionRate: 18,
      medianCycleTimeMin: 139,
      p75CycleTimeMin: 228,
    },
    {
      id: "ad-3",
      customerId: C1,
      week: "W13",
      activeTechnicians: 248,
      searches: 5410,
      successfulSessionRate: 70,
      deflectionRate: 24,
      medianCycleTimeMin: 128,
      p75CycleTimeMin: 215,
    },
    {
      id: "ad-4",
      customerId: C1,
      week: "W14",
      activeTechnicians: 311,
      searches: 7180,
      successfulSessionRate: 73,
      deflectionRate: 29,
      medianCycleTimeMin: 118,
      p75CycleTimeMin: 206,
    },
    {
      id: "ad-5",
      customerId: C1,
      week: "W15",
      activeTechnicians: 366,
      searches: 8640,
      successfulSessionRate: 72,
      deflectionRate: 31,
      medianCycleTimeMin: 112,
      p75CycleTimeMin: 201,
    },
    {
      id: "ad-6",
      customerId: C1,
      week: "W16",
      activeTechnicians: 402,
      searches: 9720,
      successfulSessionRate: 68,
      deflectionRate: 30,
      medianCycleTimeMin: 114,
      p75CycleTimeMin: 212,
    },
  ],
  incidents: [
    {
      id: "inc-1",
      customerId: C1,
      title: "Reported: manual-search accuracy down 20%",
      reportedSymptom:
        "Customer reports manual-search accuracy is down 20% after launch. Treated as a reported symptom, not a proven model failure.",
      status: "triage",
      openedAt: "Post-launch W16 (illustrative)",
      segment: "Reported broadly; segmentation not yet validated",
      provenance: "illustrative",
    },
  ],
  valueEvents: [
    {
      id: "ve-1",
      customerId: C1,
      date: "W1",
      title: "Outcome and value hypothesis confirmed",
      detail:
        "50% resolution cycle-time improvement by end of Year 1; technicians get correct instructions directly and require fewer calls to support.",
      provenance: "case-fact",
    },
    {
      id: "ve-2",
      customerId: C1,
      date: "W1",
      title: "SAP dependency discovered in discovery",
      detail: "SAP product manuals are a must-have for formal production go-live.",
      provenance: "case-fact",
    },
    {
      id: "ve-3",
      customerId: C1,
      date: "W2",
      title: "Planned: evidence-backed rebaseline conversation",
      detail: "One reset, with tradeoffs and a validated critical path.",
      provenance: "working-assumption",
    },
  ],
  documents: [
    {
      id: "doc-1",
      customerId: C1,
      title: "Kickoff & discovery notes",
      kind: "call-note",
      owner: "CS / Implementation",
      freshness: "Week 1",
      approved: true,
      confidence: "high",
      lastSync: "W1",
      relevantSystems: ["Salesforce", "SAP", "SSO"],
      content:
        "500+ field technicians and call-center agents. Salesforce Service Cloud holds KB articles, technical bulletins and job aids. Salesforce Field Service holds work orders. SAP holds product manuals. SSO included. Intelligent Search intended to unify searchable content across platforms.",
      provenance: "case-fact",
    },
    {
      id: "doc-2",
      customerId: C1,
      title: "Integration inventory (W1)",
      kind: "architecture",
      owner: "Implementation",
      freshness: "Week 1",
      approved: true,
      confidence: "high",
      lastSync: "W1",
      relevantSystems: ["Salesforce", "SAP", "SSO"],
      content:
        "Existing Salesforce connector ready. SAP requirement discovered during discovery; SAP connector is not available. Engineering initial estimate 8–10 weeks for design, development and testing.",
      provenance: "case-fact",
    },
    {
      id: "doc-3",
      customerId: C1,
      title: "Technician workflow runbook (illustrative)",
      kind: "runbook",
      owner: "Customer Field Service Leader",
      freshness: "Unverified",
      approved: false,
      confidence: "low",
      lastSync: "—",
      relevantSystems: ["Salesforce Field Service"],
      content:
        "Illustrative demo representation of the field workflow. Not customer-validated; excluded from environment generation and call prep until approved.",
      provenance: "illustrative",
    },
    {
      id: "doc-4",
      customerId: C1,
      title: "ROI baseline workshop input (draft)",
      kind: "crm-note",
      owner: "CS / Implementation",
      freshness: "Week 1",
      approved: true,
      confidence: "medium",
      lastSync: "W1",
      relevantSystems: ["Salesforce Field Service"],
      content:
        "Draft metric definitions for resolution cycle time: cohort, start/stop timestamps, exclusions, source owner. Baseline value not yet approved by the customer.",
      provenance: "working-assumption",
    },
  ],
  goldenQueries: [
    {
      id: "gq-1",
      customerId: C1,
      query: "Replace pressure sensor assembly on infusion pump model line A",
      expected: "SAP product manual section for the current revision, with torque spec table",
      sourceSystem: "SAP",
      productFamily: "Infusion",
      version: "Rev 7 (illustrative)",
      lastResult: "not-run",
    },
    {
      id: "gq-2",
      customerId: C1,
      query: "Error code E-114 troubleshooting steps",
      expected: "Service Cloud technical bulletin, most recent revision",
      sourceSystem: "Salesforce",
      productFamily: "Monitoring",
      version: "Bulletin 2024-11 (illustrative)",
      lastResult: "pass",
    },
    {
      id: "gq-3",
      customerId: C1,
      query: "Calibration interval for imaging subsystem",
      expected: "SAP manual calibration table for the installed configuration",
      sourceSystem: "SAP",
      productFamily: "Imaging",
      version: "Rev 3 (illustrative)",
      lastResult: "not-run",
    },
    {
      id: "gq-4",
      customerId: C1,
      query: "Field replacement job aid for battery module",
      expected: "Service Cloud job aid with parts list",
      sourceSystem: "Salesforce",
      productFamily: "Infusion",
      version: "Job aid v4 (illustrative)",
      lastResult: "pass",
    },
  ],
  readiness: [
    { id: "rg-1", label: "Data sources", group: "Data", value: "Salesforce Service Cloud, Salesforce Field Service, SAP product manuals", blocking: true },
    { id: "rg-2", label: "Source owners", group: "Data", value: "Named per source (Salesforce platform owner, SAP content owner)", blocking: true },
    { id: "rg-3", label: "Connector status (prebuilt / custom / unknown)", group: "Integration", value: "Salesforce: prebuilt. SAP: not available — custom build required.", blocking: true },
    { id: "rg-4", label: "Version / auth", group: "Integration", value: "SAP version and auth model to be defined in the design spike", blocking: true },
    { id: "rg-5", label: "Security / SSO", group: "Security", value: "SSO included; RBAC and entitlement filtering required", blocking: true },
    { id: "rg-6", label: "Content sample", group: "Data", value: "Not yet collected for SAP manuals", blocking: true },
    { id: "rg-7", label: "Data quality", group: "Data", value: "Unknown for SAP; Salesforce content validation in progress", blocking: true },
    { id: "rg-8", label: "Permissions", group: "Security", value: "Permission-aware search required for UAT", blocking: true },
    { id: "rg-9", label: "ROI metric", group: "Value", value: "Resolution cycle time (median + P75)", blocking: false },
    { id: "rg-10", label: "Baseline", group: "Value", value: "Pending customer-approved baseline", blocking: true },
    { id: "rg-11", label: "Cohort", group: "Value", value: "Launch cohort of field technicians, to be defined", blocking: false },
    { id: "rg-12", label: "Source system", group: "Value", value: "Salesforce Field Service", blocking: false },
    { id: "rg-13", label: "Customer dependencies", group: "Governance", value: "SMEs, identity inputs, content validation, workflow acceptance", blocking: true },
    { id: "rg-14", label: "Named owners", group: "Governance", value: "Assigned for every dependency and metric", blocking: true },
    { id: "rg-15", label: "Date confidence", group: "Governance", value: "Low until Engineering validates the estimate", blocking: true },
    { id: "rg-16", label: "Engineering review for custom/unknown integrations", group: "Integration", value: "Required — not completed before the commercial date was set", blocking: true },
  ],
  messages: [
    {
      id: "msg-1",
      customerId: C1,
      title: "Week 1 SAP dependency disclosure",
      audience: "Customer sponsor + Field Service Leader",
      status: "approved-example",
      discovered:
        "During discovery we confirmed that SAP product manuals are essential to the technician workflow.",
      impact:
        "The Salesforce integration is ready, while SAP requires a new connector.",
      actions:
        "Rather than compromise the production design, we are running all remaining implementation work in parallel with Engineering and validating the earliest supportable production date.",
      decisions:
        "We will provide a confirmed critical path after technical validation and maintain weekly milestone visibility against it.",
      checkpoint: "Week 2 recovery review with the validated Engineering plan and tradeoffs.",
      provenance: "case-fact",
    },
  ],
  assumptions: [
    {
      id: "asm-1",
      customerId: C1,
      statement:
        "Engineering's 8–10 week estimate covers design, development and testing but not customer-side content validation time.",
      validationPath: "Confirm scope boundaries in the W1–W2 design spike output.",
      owner: "Engineering",
    },
    {
      id: "asm-2",
      customerId: C1,
      statement: "A defensible cycle-time baseline can be constructed from Field Service timestamps.",
      validationPath: "Baseline workshop with customer ops; sample extract and timestamp review.",
      owner: "CS / Implementation",
    },
    {
      id: "asm-3",
      customerId: C1,
      statement: "Technician cohort can be held stable across baseline and comparison windows.",
      validationPath: "Cohort definition agreed and locked with the customer before launch.",
      owner: "CS / Implementation",
    },
    {
      id: "asm-4",
      customerId: C1,
      statement: "Hypercare of two weeks is sufficient before BAU transition.",
      validationPath: "Reviewed at go/no-go using adoption and quality signals.",
      owner: "CS / Implementation",
    },
  ],
};