[CmdletBinding()]
param([string]$Label="",[string]$Roles="general,build,ai",[int]$MaxWorkers=0,[ValidateSet("true","false")][string]$Gpu="true",[ValidateSet("true","false")][string]$SkipDoctor="false")
$ErrorActionPreference="Stop";$ProgressPreference="SilentlyContinue";$Root=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot "..\.."));$Marker=Join-Path $env:LOCALAPPDATA "Clintware\QuillgeistLite\python3-check.json"
if(-not(Test-Path -LiteralPath $Marker)){throw "QQ Python runtime marker missing. Run ensure-python first."};$Py=[string](Get-Content -LiteralPath $Marker -Raw|ConvertFrom-Json).path
$CloudMist=Join-Path $Root "quillgeist-lite\tools\cloud_mist.py";$Scheduler=Join-Path $Root "quillgeist-lite\tools\resource_scheduler.py";$LocalAI=Join-Path $Root "quillgeist-lite\tools\local_ai.py";$Doctor=Join-Path $Root "quillgeist-lite\tasks\clintware-doctor.ps1";$OutRoot=Join-Path $env:LOCALAPPDATA "Clintware\QuillgeistLite\cloud-mist";New-Item -ItemType Directory -Force -Path $OutRoot|Out-Null
$report=[ordered]@{version=1;started_at=(Get-Date).ToUniversalTime().ToString("o");machine=$env:COMPUTERNAME;label=$(if($Label){$Label}else{$env:COMPUTERNAME});roles=$Roles;doctor=$null;worker_pool=$null;local_ai=$null;enrollment=$null}
if($SkipDoctor-ne"true"-and(Test-Path -LiteralPath $Doctor)){try{$shell=(Get-Command pwsh -ErrorAction SilentlyContinue);if(-not$shell){$shell=(Get-Command powershell -ErrorAction Stop)};$x=& $shell.Source -NoProfile -ExecutionPolicy Bypass -File $Doctor 2>&1;$report.doctor=@{ok=($LASTEXITCODE-eq 0);output=($x-join[Environment]::NewLine)}}catch{$report.doctor=@{ok=$false;error=$_.Exception.Message}}}
$args=@($CloudMist,"--Action","enroll","--Label",$report.label,"--Roles",$Roles,"--Gpu",$Gpu);if($MaxWorkers-gt 0){$args+=@("--MaxWorkers",[string]$MaxWorkers)};$raw=& $Py @args;if($LASTEXITCODE-ne 0){throw "CloudMist enrollment failed."};$report.enrollment=($raw-join[Environment]::NewLine|ConvertFrom-Json)
if(Test-Path -LiteralPath $Scheduler){try{$sa=@($Scheduler);if($MaxWorkers-gt 0){$sa+=@("--MaxWorkers",[string]$MaxWorkers)};$x=& $Py @sa 2>&1;$report.worker_pool=@{ok=($LASTEXITCODE-eq 0);output=($x-join[Environment]::NewLine)}}catch{$report.worker_pool=@{ok=$false;error=$_.Exception.Message}}}
if(Test-Path -LiteralPath $LocalAI){try{$x=& $Py $LocalAI --Action status 2>&1;$report.local_ai=@{ok=($LASTEXITCODE-eq 0);output=($x-join[Environment]::NewLine)}}catch{$report.local_ai=@{ok=$false;error=$_.Exception.Message}}}
$report.finished_at=(Get-Date).ToUniversalTime().ToString("o");$report.ok=$true;$path=Join-Path $OutRoot "onboarding-report.json";$report|ConvertTo-Json -Depth 12|Set-Content -LiteralPath $path -Encoding UTF8;$report|ConvertTo-Json -Depth 12;Write-Host "CLOUDMIST_ONBOARDED report=$path"
