import assert from "node:assert/strict";
import test from "node:test";
import vm from "node:vm";
import { BROWSER_ENGINE } from "../src/browser-engine.js";
import { SAMPLE_CSV } from "../src/browser-app.js";

const context = { globalThis: {}, Date }; vm.createContext(context); vm.runInContext(BROWSER_ENGINE, context); const engine = context.globalThis.BuyerOriginEngine;
test("normalizes buyer signals", () => { assert.equal(engine.normalizeEmail("Alex.Smith+offer@googlemail.com"), "alexsmith@gmail.com"); assert.equal(engine.normalizePhone("+1 (512) 555-0101"), "5125550101"); assert.equal(engine.normalizeAddress("10 Oak Street, Apt 2"), "10oakst"); });
test("default merchant policy finds repeat acquisition offer use", () => { const audit = engine.audit(SAMPLE_CSV, { mode: "monitor" }); assert.equal(audit.totals.orders, 6); assert.equal(audit.totals.ineligible, 2); assert.equal(audit.totals.estimated_leakage, 43); const row = audit.results.find((entry) => entry.order_id === "BO-1003"); assert.equal(row.status, "Ineligible"); assert.deepEqual(Array.from(row.reason_codes), ["EMAIL_ALIAS_MATCH", "PHONE_MATCH"]); });
test("merchant can require all three identity signals", () => { const audit = engine.audit(SAMPLE_CSV, { policy: { min_matching_signals: 3 } }); assert.equal(audit.totals.ineligible, 1); assert.equal(audit.results.find((entry) => entry.order_id === "BO-1003").status, "Eligible"); });
test("merchant can scope eligibility to the same offer code", () => { const csv = SAMPLE_CSV + "\nBO-1007,alexsmith@gmail.com,5125550101,902 Lake Avenue,VIP25,2026-08-30,100,25,true,human,"; const broad = engine.audit(csv, { policy: { offer_scope: "acquisition" } }); const narrow = engine.audit(csv, { policy: { offer_scope: "same_code" } }); assert.equal(broad.results.find((row) => row.order_id === "BO-1007").status, "Ineligible"); assert.equal(narrow.results.find((row) => row.order_id === "BO-1007").status, "Eligible"); });
test("lookback window changes eligibility", () => { const csv = `order_id,email,phone,address,discount_code,order_date,order_total,discount_amount,is_new_customer_offer\nA,a@example.com,5125550101,1 Main Street,WELCOME,2025-01-01,100,20,true\nB,a@example.com,5125550101,2 Other Road,WELCOME,2026-08-01,100,20,true`; const short = engine.audit(csv, { policy: { lookback_days: 30 } }); const long = engine.audit(csv, { policy: { lookback_days: 1000 } }); assert.equal(short.results[1].status, "Eligible"); assert.equal(long.results[1].status, "Ineligible"); });
test("merchant override preserves evidence", () => { const audit = engine.audit(SAMPLE_CSV, { mode: "enforce", allowlist: ["BO-1005"] }); const row = audit.results.find((entry) => entry.order_id === "BO-1005"); assert.equal(row.status, "Merchant override"); assert.equal(row.note, "Merchant allowlist override retained with evidence"); assert.ok(row.reason_codes.length >= 2); });
test("simulation denies only the offer and never checkout", () => { const audit = engine.audit(SAMPLE_CSV, { mode: "enforce" }); assert.equal(audit.results.find((row) => row.order_id === "BO-1003").action, "Deny offer"); assert.ok(audit.results.every((row) => row.action !== "Deny checkout")); });
test("shopping agent metadata does not independently affect eligibility", () => { const row = engine.audit(SAMPLE_CSV).results.find((entry) => entry.order_id === "BO-1006"); assert.equal(row.actor_type, "shopping_agent"); assert.equal(row.status, "Eligible"); });
test("rejects incomplete exports", () => assert.throws(() => engine.audit("order_id,email\n1,a@example.com"), /Missing required columns/));
