import vm from 'node:vm';
import zlib from 'node:zlib';
import { APP_GZ_B64 } from '../src/app.js';
const APP_HTML=zlib.gunzipSync(Buffer.from(APP_GZ_B64,'base64')).toString('utf8');
const must=['Post-Sales Business Operations','Seed Demo Accounts','Clear Accounts','Add your first account','generate-review','localStorage'];
for (const x of must) if (!APP_HTML.includes(x)) throw new Error('missing '+x);
const scriptMatch=APP_HTML.match(/<script>([\s\S]*)<\/script>/);
if(!scriptMatch) throw new Error('inline app script missing');
new vm.Script(scriptMatch[1]);
const names=APP_HTML.match(/const NAMES=\[(.*?)\];/s)?.[1] || '';
const count=(names.match(/'/g)||[]).length/2;
if(count!==20) throw new Error('expected 20 seeded account names, got '+count);
console.log('app smoke checks passed; 20-account seed present; client script parses');
