import crypto from "node:crypto";
import prisma from "../db.server";
import { buildCouponState, keyedToken } from "../../src/compact-state.js";
import { extractCouponUses } from "../../src/order-ingest.js";
import { parseShopifyOrdersCsv } from "../../src/shopify-csv.js";

export function merchantStateKey(shop: string) {
  const master=process.env.BUYERORIGIN_MASTER_KEY;
  if (!master) throw new Error("BUYERORIGIN_MASTER_KEY is required");
  return crypto.createHmac("sha256",master).update(`buyerorigin:${shop.toLowerCase()}`).digest("base64url");
}
export async function ensureMerchant(shop: string) { return prisma.merchant.upsert({where:{shop},update:{uninstalledAt:null},create:{shop}}); }
async function persistUse(merchantId:string,use:any){if(!use.couponKey||!use.orderId)return;await prisma.couponUse.upsert({where:{merchantId_orderId_couponKey:{merchantId,orderId:String(use.orderId),couponKey:String(use.couponKey)}},update:{emailKey:use.emailKey,phoneKey:use.phoneKey,addressKey:use.addressKey,usedAt:new Date(use.usedAt),discountAmount:Number.isFinite(use.discountAmount)?use.discountAmount:null},create:{merchantId,orderId:String(use.orderId),couponKey:String(use.couponKey),emailKey:use.emailKey,phoneKey:use.phoneKey,addressKey:use.addressKey,usedAt:new Date(use.usedAt),discountAmount:Number.isFinite(use.discountAmount)?use.discountAmount:null}});}
export async function ingestOrder(shop: string, payload: any) {const merchant=await ensureMerchant(shop),secret=merchantStateKey(shop),uses=extractCouponUses(payload,secret);for(const use of uses)await persistUse(merchant.id,use);return uses.length;}
export async function seedOrdersCsv(shop:string,text:string){const merchant=await ensureMerchant(shop),secret=merchantStateKey(shop),orders=parseShopifyOrdersCsv(text);let count=0;for(const order of orders){for(const discount of order.discountCodes){const couponKey=keyedToken(secret,"code",discount.code);if(!couponKey)continue;const use={orderId:order.orderId,couponKey,emailKey:keyedToken(secret,"email",order.email),phoneKey:keyedToken(secret,"phone",order.phone),addressKey:keyedToken(secret,"address",order.address),usedAt:order.orderDate,discountAmount:discount.amount==null?null:Number(String(discount.amount).replace(/[$,]/g,""))};await persistUse(merchant.id,use);count++;}}return{orders:orders.length,uses:count};}
export async function couponState(shop: string, policy: any) {const merchant=await ensureMerchant(shop),secret=merchantStateKey(shop),couponKey=keyedToken(secret,"code",policy.couponCode);if(!couponKey)throw new Error("Coupon code is required");const cutoff=new Date(Date.now()-Number(policy.lookbackDays||365)*86400000);const uses=await prisma.couponUse.findMany({where:{merchantId:merchant.id,couponKey,usedAt:{gte:cutoff}},orderBy:{usedAt:"asc"}});return buildCouponState({secret,couponCode:policy.couponCode,enabled:policy.enabled,policy,uses:uses.map((u:any)=>({orderId:u.orderId,emailKey:u.emailKey,phoneKey:u.phoneKey,addressKey:u.addressKey,usedAt:u.usedAt.toISOString()}))});}
export async function redactCustomer(shop:string,payload:any){const merchant=await prisma.merchant.findUnique({where:{shop}});if(!merchant)return 0;const secret=merchantStateKey(shop);const emailKey=keyedToken(secret,"email",payload?.customer?.email||payload?.email||"");const phoneKey=keyedToken(secret,"phone",payload?.customer?.phone||payload?.phone||"");const orders=(payload?.orders_to_redact||[]).map((x:any)=>String(x));const ors:any[]=[];if(emailKey)ors.push({emailKey});if(phoneKey)ors.push({phoneKey});if(orders.length)ors.push({orderId:{in:orders}});if(!ors.length)return 0;const result=await prisma.couponUse.deleteMany({where:{merchantId:merchant.id,OR:ors}});return result.count;}
