const HTML = String.raw`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="Mind to Form turns a rough product idea into an agreed Definition of Done, first engineering draft, and local parametric 3D export package.">
<link rel="canonical" href="https://mindtoform.clintware.com/"><title>Mind to Form | Clintware</title>
<style>
:root{color-scheme:dark;--bg:#070a0e;--panel:#0c1218;--line:#26323e;--text:#edf6fb;--muted:#90a4b5;--cyan:#69dcf5;--green:#73efb2;--amber:#f0c76e;--mono:"Cascadia Code",Consolas,monospace}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:13.5px/1.6 var(--mono)}button,input,textarea,select{font:inherit}a{color:var(--cyan)}.wrap{width:min(1160px,calc(100% - 34px));margin:auto}.top{display:flex;justify-content:space-between;gap:16px;padding:16px 0;border-bottom:1px solid var(--line);font-size:11px}.hero{padding:36px 0 24px;border-bottom:1px solid var(--line)}.kicker{color:var(--green);font-size:10px}.hero h1{font-size:24px;line-height:1.25;max-width:850px;margin:10px 0}.hero p{color:#b4c3ce;max-width:850px}.flow{display:flex;flex-wrap:wrap;gap:5px;margin-top:18px}.flow span{border:1px solid var(--line);padding:6px 8px;font-size:10px;color:#9db0bf}.flow b{color:var(--cyan)}.section{padding:25px 0;border-bottom:1px solid #1e2933}.grid{display:grid;grid-template-columns:1.05fr .95fr;gap:16px}.panel{background:var(--panel);border:1px solid var(--line);padding:18px}.panel h2{font-size:15px;margin:0 0 12px}.panel h3{font-size:12px;color:var(--cyan);margin:20px 0 8px}label{display:block;color:#a8bac7;font-size:11px;margin:11px 0 5px}textarea,input,select{width:100%;border:1px solid #31404d;background:#070b10;color:var(--text);padding:10px}textarea{min-height:105px;resize:vertical}.row2{display:grid;grid-template-columns:1fr 1fr;gap:10px}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.btn{border:1px solid #3a4a57;background:#111a22;color:var(--text);padding:9px 12px;cursor:pointer}.primary{background:#0b2c34;border-color:#2d8398}.approve{background:#0b2e20;border-color:#2f8c63}.btn:disabled{opacity:.35;cursor:not-allowed}.note{font-size:11px;color:var(--muted)}.warn{border-left:3px solid var(--amber);padding:10px 12px;background:#18150d;color:#d9c79a;margin-top:12px}.dod{white-space:pre-wrap;min-height:210px}.approval{display:flex;gap:8px;align-items:flex-start;margin-top:12px}.approval input{width:auto;margin-top:4px}.model{height:350px;background:#05080b;border:1px solid var(--line);position:relative}.model canvas{width:100%;height:100%;display:block}.hint{position:absolute;left:9px;bottom:7px;color:#607383;font-size:10px}.specs{display:grid;grid-template-columns:1fr 1fr;gap:8px}.kv{border:1px solid var(--line);padding:9px;background:#090e13}.kv b{display:block;color:var(--cyan);font-size:10px}.quote{width:100%;border-collapse:collapse}.quote td,.quote th{padding:8px 5px;border-bottom:1px solid var(--line);font-size:11px;text-align:left}.tag{color:var(--green)}[hidden]{display:none!important}@media(max-width:820px){.grid,.row2,.specs{grid-template-columns:1fr}.model{height:300px}}
</style></head><body>
<header class="wrap top"><b>CLINTWARE / MIND TO FORM</b><a href="https://www.clintware.com/startup/">YC venture index ↗</a></header>
<main><section class="hero"><div class="wrap"><div class="kicker">WORKING BROWSER ALPHA · INTENT → PHYSICAL PRODUCT</div><h1>Describe what should exist. Agree on what “done” means. Only then create the first design.</h1><p>Mind to Form is an intent-to-physical-product compiler. The current alpha keeps intake, the requirements contract, model preview, and exports in your browser. It does not present concept geometry as production-certified CAD.</p><div class="flow"><span><b>01</b> DESCRIBE</span><span><b>02</b> VET</span><span><b>03</b> DEFINE DONE</span><span><b>04</b> AGREE</span><span><b>05</b> FORM</span><span>06 VALIDATE</span><span>07 QUOTE</span><span>08 MAKE</span></div></div></section>
<section class="section"><div class="wrap grid"><div class="panel"><h2>1. What do you want to exist?</h2><textarea id="idea" placeholder="Describe it however it exists in your head. You do not need CAD or manufacturing vocabulary."></textarea><div class="actions"><button class="btn" id="sample">Load thermal-device sample</button><button class="btn primary" id="start">Start vetting</button></div><div id="questions" hidden><h3>Only questions that change the result</h3><div id="aiVetting" class="note">Adaptive vetting will analyze only the initial idea text. Other answers and generated geometry stay local in this browser alpha.</div><label>Answers to the adaptive questions</label><textarea id="adaptive" placeholder="The product-specific questions will appear above. Answer them here in your own words."></textarea><label>What must the finished object accomplish?</label><textarea id="outcome"></textarea><div class="row2"><div><label>What must it fit or connect to?</label><input id="interfaces"></div><div><label>Operating environment</label><input id="environment"></div></div><div class="row2"><div><label>Maximum size / envelope</label><input id="size"></div><div><label>Likely production quantity</label><select id="quantity"><option>1 prototype</option><option>10 units</option><option>50 units</option><option>100 units</option><option>300 units</option><option>1,000+ units</option></select></div></div><div class="row2"><div><label>Preferred / required materials</label><input id="materials"></div><div><label>Primary optimization</label><select id="priority"><option>Durability / reliability</option><option>Lowest prototype cost</option><option>Lowest scaled unit cost</option><option>Lowest weight</option><option>Thermal performance</option><option>Ease of manufacturing</option></select></div></div><label>Hard requirements, exclusions, or failure modes</label><textarea id="hard"></textarea><div class="row2"><div><label>Prototype budget target</label><input id="budget"></div><div><label>Scaled unit-cost target</label><input id="unitcost"></div></div><div class="actions"><button class="btn primary" id="define">Build Definition of Done</button></div></div></div>
<div class="panel"><h2>2. Agreement boundary</h2><p class="note">Generation is blocked until you approve the requirements contract. Edit it before agreeing.</p><textarea id="dod" class="dod" placeholder="Your Definition of Done will appear here." disabled></textarea><div id="approvalWrap" hidden><label class="approval"><input type="checkbox" id="approved"><span>I confirm that this Definition of Done represents what I want the first design to accomplish.</span></label><div class="actions"><button class="btn approve" id="create" disabled>Create first draft</button></div><div class="warn">Approval authorizes a first engineering draft only. It does not certify safety, compliance, manufacturability, or vendor pricing.</div></div></div></div></section>
<section class="section" id="design" hidden><div class="wrap grid"><div class="panel"><h2>3. First form</h2><div class="model"><canvas id="canvas"></canvas><div class="hint">drag to rotate · rendered locally</div></div><div class="actions"><button class="btn" id="stl">Export STL</button><button class="btn" id="scad">Export OpenSCAD</button><button class="btn" id="json">Export spec JSON</button></div></div><div class="panel"><h2>Draft engineering package</h2><div id="specs" class="specs"></div><h3>Quantity economics</h3><p class="note">Engineering estimate only. Not a live vendor quote.</p><table class="quote"><thead><tr><th>Qty</th><th>Est. unit</th><th>Likely process</th></tr></thead><tbody id="costs"></tbody></table><h3>Quote adapters</h3><p class="note">Targets: Xometry, Protolabs, JLC3DP, SendCutSend where process-compatible. <span class="tag">NOT CONNECTED YET.</span></p></div></div></section>
<section class="section"><div class="wrap"><h2>What has to be proven next</h2><p>Replace concept geometry with manufacturable parametric B-rep/STEP generation, add DFM and appropriate simulation, connect live RFQs, compare prototype and production quantities, and close the loop by ordering and validating a physical prototype. The approved Definition of Done remains the controlling input through every revision.</p></div></section></main>
<script>
(function(){
var $=function(id){return document.getElementById(id)},mesh=null,spec=null,yaw=.6,pitch=-.25,drag=false,lx=0,ly=0;
function v(id){return $(id).value.trim()}
$("sample").onclick=function(){$("idea").value="I want a compact continuous-duty heated assembly that works with a 25 mm axial PID coil. Use titanium structurally and silicon carbide for the primary thermal surface. Keep heat away from the connection point, make wear surfaces replaceable, and support 14 mm and 18 mm connections. I want one prototype first, but the design should make sense at 50, 100 and 300 units.";$("outcome").value="A durable heated assembly that can remain installed for extended operation, protects the downstream connection from unnecessary heat, and has replaceable wear surfaces.";$("interfaces").value="25 mm axial PID coil; 14 mm and 18 mm connections";$("environment").value="Continuous high-temperature operation";$("size").value="Target under 70 mm overall length";$("materials").value="Grade 2 titanium structure; SiC primary thermal surface; ceramic thermal break where useful";$("hard").value="No polymer, silicone, adhesive, or epoxy in the hot zone. Replaceable thermal/wear component. Avoid concentrating heat into the downstream joint.";$("budget").value="Under $400";$("unitcost").value="Under $50 at 300 units";$("quantity").value="300 units";};
$("start").onclick=async function(){if(!v("idea")){alert("Describe the object first.");return}$("questions").hidden=false;$("aiVetting").textContent="Finding the few unknowns that would materially change the design…";try{var r=await fetch("/api/vet",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({idea:v("idea")})}),d=await r.json();if(d.questions&&d.questions.length){$("aiVetting").innerHTML="<b>Adaptive vetting</b><ol>"+d.questions.map(function(q){return "<li>"+esc(q)+"</li>"}).join("")+"</ol>"+(d.assumptions&&d.assumptions.length?"<div><b>Current assumptions:</b> "+d.assumptions.map(esc).join(" · ")+"</div>":"");}else throw new Error("no questions")}catch(e){$("aiVetting").innerHTML="<b>Adaptive vetting fallback</b><ol><li>What outcome would make you call the object successful?</li><li>What must it fit or interface with?</li><li>What failure would be unacceptable?</li><li>What quantity and cost target matter?</li></ol>"}};
$("define").onclick=function(){var lines=["OBJECTIVE",v("outcome")||v("idea"),"","SOURCE IDEA",v("idea"),"","ADAPTIVE VETTING ANSWERS",v("adaptive")||"Not provided","","SUCCESS / DEFINITION OF DONE","• Compatible with: "+(v("interfaces")||"No interface specified yet"),"• Operating environment: "+(v("environment")||"Not specified"),"• Physical envelope: "+(v("size")||"Not specified"),"• Material direction: "+(v("materials")||"Select by function, cost, and manufacturability"),"• Primary optimization: "+v("priority"),"• Production target: "+v("quantity"),"• Prototype budget target: "+(v("budget")||"Not specified"),"• Scaled unit-cost target: "+(v("unitcost")||"Not specified"),"","HARD REQUIREMENTS / EXCLUSIONS",v("hard")||"None supplied. First draft must surface assumptions.","","AGREEMENT","The first design may explore implementation choices, but it must not silently change the objective, interfaces, hard exclusions, or cost/quantity targets above."];$("dod").disabled=false;$("dod").value=lines.join("\n");$("approvalWrap").hidden=false;$("approved").checked=false;$("create").disabled=true};
$("approved").onchange=function(){$("create").disabled=!this.checked};
function num(text,re,fallback){var m=text.match(re);return m?parseFloat(m[1]):fallback}
function makeSpec(){var text=(v("idea")+" "+v("interfaces")+" "+v("size")+" "+v("materials")+" "+v("hard")).toLowerCase(),coil=num(text,/(\d+(?:\.\d+)?)\s*mm\s*(?:axial|coil)/,25),len=num(v("size").toLowerCase(),/(\d+(?:\.\d+)?)\s*mm/,62);if(len<35)len=62;var dia=Math.max(18,Math.min(55,coil+8)),mats=[];if(text.indexOf("titanium")>=0)mats.push("Grade 2 titanium");if(text.indexOf("silicon carbide")>=0||text.indexOf("sic")>=0)mats.push("SiC");if(text.indexOf("ceramic")>=0)mats.push("technical ceramic");if(!mats.length)mats.push("material selection pending");return {revision:"R0-FIRST-DRAFT",objective:v("outcome")||v("idea"),interface:v("interfaces")||"Unspecified",environment:v("environment")||"Unspecified",overall_length_mm:len,body_diameter_mm:dia,primary_interface_mm:coil,materials:mats,priority:v("priority"),quantity:v("quantity"),prototype_budget:v("budget")||"not set",unit_cost_target:v("unitcost")||"not set",hard_requirements:v("hard")||"none supplied",confidence:"concept geometry only — engineering validation required before manufacture"}}
function lathe(d,l){var r=d/2,profile=[[r*.72,0],[r*.92,3],[r,8],[r,l*.25],[r*.76,l*.34],[r*.68,l*.70],[r*.86,l*.79],[r*.86,l-4],[r*.70,l]],seg=36,verts=[],faces=[];for(var i=0;i<profile.length;i++){for(var s=0;s<seg;s++){var a=s*Math.PI*2/seg;verts.push([profile[i][0]*Math.cos(a),profile[i][0]*Math.sin(a),profile[i][1]-l/2])}}for(var p=0;p<profile.length-1;p++){for(var q=0;q<seg;q++){var n=(q+1)%seg,a=p*seg+q,b=p*seg+n,c=(p+1)*seg+n,d2=(p+1)*seg+q;faces.push([a,b,c],[a,c,d2])}}return {verts:verts,faces:faces,profile:profile}}
function rot(p){var x=p[0],y=p[1],z=p[2],cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch),x1=x*cy+z*sy,z1=-x*sy+z*cy,y1=y*cp-z1*sp,z2=y*sp+z1*cp;return [x1,y1,z2]}
function draw(){if(!mesh)return;var c=$("canvas"),dpr=window.devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;var ctx=c.getContext("2d");ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);var pts=mesh.verts.map(function(p){var r=rot(p),f=160/(160-r[2]);return {x:w/2+r[0]*f*3,y:h/2-r[1]*f*3,z:r[2]}}),fs=mesh.faces.map(function(f){return {f:f,z:(pts[f[0]].z+pts[f[1]].z+pts[f[2]].z)/3}}).sort(function(a,b){return a.z-b.z});fs.forEach(function(o){var a=pts[o.f[0]],b=pts[o.f[1]],d=pts[o.f[2]],shade=Math.max(.15,Math.min(.7,.38+o.z/170));ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.lineTo(d.x,d.y);ctx.closePath();ctx.fillStyle="rgba(63,188,211,"+shade+")";ctx.fill();ctx.strokeStyle="rgba(144,230,245,.12)";ctx.stroke()})}
function esc(s){return String(s).replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]})}
$("create").onclick=function(){spec=makeSpec();mesh=lathe(spec.body_diameter_mm,spec.overall_length_mm);$("design").hidden=false;var items=[["Revision",spec.revision],["Objective",spec.objective],["Envelope",spec.overall_length_mm+" mm L × "+spec.body_diameter_mm+" mm Ø"],["Primary interface",spec.primary_interface_mm+" mm"],["Materials",spec.materials.join(" + ")],["Priority",spec.priority],["Quantity",spec.quantity],["Prototype budget",spec.prototype_budget],["Scaled target",spec.unit_cost_target],["Validation",spec.confidence]];$("specs").innerHTML=items.map(function(x){return '<div class="kv"><b>'+esc(x[0])+'</b>'+esc(x[1])+'</div>'}).join("");var mult=spec.materials.indexOf("SiC")>=0?1.28:1,rows=[[1,145,"CNC / additive prototype"],[10,68,"CNC small batch"],[50,42,"CNC + fixture optimization"],[100,34,"Production CNC / mixed process"],[300,27,"Design-for-scale review"]];$("costs").innerHTML=rows.map(function(r){return "<tr><td>"+r[0]+"</td><td>$"+Math.round(r[1]*mult)+"</td><td>"+r[2]+"</td></tr>"}).join("");draw();$("design").scrollIntoView({behavior:"smooth"})};
var c=$("canvas");c.addEventListener("pointerdown",function(e){drag=true;lx=e.clientX;ly=e.clientY;c.setPointerCapture(e.pointerId)});c.addEventListener("pointermove",function(e){if(!drag)return;yaw+=(e.clientX-lx)*.012;pitch+=(e.clientY-ly)*.012;lx=e.clientX;ly=e.clientY;draw()});c.addEventListener("pointerup",function(){drag=false});window.addEventListener("resize",draw);
function dl(name,text,type){var a=document.createElement("a"),blob=new Blob([text],{type:type||"text/plain"});a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},1000)}
function normal(a,b,c){var u=[b[0]-a[0],b[1]-a[1],b[2]-a[2]],v=[c[0]-a[0],c[1]-a[1],c[2]-a[2]],n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],m=Math.hypot(n[0],n[1],n[2])||1;return [n[0]/m,n[1]/m,n[2]/m]}
$("stl").onclick=function(){if(!mesh)return;var out=["solid mind_to_form"];mesh.faces.forEach(function(f){var a=mesh.verts[f[0]],b=mesh.verts[f[1]],c=mesh.verts[f[2]],n=normal(a,b,c);out.push(" facet normal "+n.join(" "),"  outer loop","   vertex "+a.join(" "),"   vertex "+b.join(" "),"   vertex "+c.join(" "),"  endloop"," endfacet")});out.push("endsolid mind_to_form");dl("mindtoform-"+spec.revision+".stl",out.join("\n"),"model/stl")};
$("scad").onclick=function(){if(!mesh)return;var pts=mesh.profile.map(function(p){return "["+p[0].toFixed(3)+","+(p[1]-spec.overall_length_mm/2).toFixed(3)+"]"}).join(","),scad="// Mind to Form "+spec.revision+"\n// Concept geometry only. Validate before manufacture.\nrotate_extrude($fn=96) polygon(points=["+pts+"]);\n";dl("mindtoform-"+spec.revision+".scad",scad)};
$("json").onclick=function(){if(!spec)return;dl("mindtoform-"+spec.revision+".json",JSON.stringify({definition_of_done:$("dod").value,spec:spec},null,2),"application/json")};
})();
</script></body></html>`;

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (url.pathname === "/healthz") return Response.json({ok:true,service:"mindtoform",version:"2026-09-19-alpha2",mode:"adaptive-vet-dod-gated-local-form"});
    if (url.pathname === "/api/vet" && request.method === "POST") {
      try {
        const body=await request.json();
        const idea=String(body.idea||"").trim().slice(0,5000);
        if(!idea) return Response.json({ok:false,error:"idea_required"},{status:400});
        const schema={type:"object",properties:{questions:{type:"array",items:{type:"string"},minItems:3,maxItems:7},assumptions:{type:"array",items:{type:"string"},maxItems:6}},required:["questions","assumptions"]};
        const result=await env.AI.run("@cf/meta/llama-3.3-70b-instruct-fp8-fast",{
          messages:[
            {role:"system",content:"You are the requirements-vetting layer for a physical-product design system. Ask only questions whose answers could materially change geometry, interfaces, materials, safety constraints, manufacturability, quantity economics, or the user's definition of success. Do not design the object yet. Avoid questions already answered in the idea. Return 3-7 concise questions and a short list of assumptions you are currently making."},
            {role:"user",content:idea}
          ],
          response_format:{type:"json_schema",json_schema:schema},
          max_tokens:900,
          temperature:0.2
        });
        let data=result&&result.response!==undefined?result.response:result;
        if(typeof data==="string") data=JSON.parse(data);
        return Response.json({ok:true,questions:Array.isArray(data.questions)?data.questions:[],assumptions:Array.isArray(data.assumptions)?data.assumptions:[]});
      } catch(error) {
        return Response.json({ok:false,questions:["What outcome would make you call the object successful?","What must it fit or interface with?","What failure would be unacceptable?","What quantity and cost target matter?"],assumptions:["AI vetting unavailable; using deterministic fallback."]});
      }
    }
    if (request.method !== "GET" && request.method !== "HEAD") return new Response("Method not allowed",{status:405,headers:{Allow:"GET, HEAD"}});
    if (url.pathname !== "/" && url.pathname !== "/index.html") return Response.redirect("https://mindtoform.clintware.com/",302);
    const headers={"content-type":"text/html; charset=utf-8","cache-control":"public, max-age=300","content-security-policy":"default-src 'self'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'","referrer-policy":"strict-origin-when-cross-origin","x-content-type-options":"nosniff","x-frame-options":"DENY"};
    return new Response(request.method === "HEAD" ? null : HTML,{status:200,headers});
  }
};
