/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as PresentCustomerIdRouteImport } from './routes/present/$customerId'
import { Route as CustomersCustomerIdIndexRouteImport } from './routes/customers/$customerId/index'
import { Route as CustomersCustomerIdSectionRouteImport } from './routes/customers/$customerId/$section'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentCustomerIdRoute = PresentCustomerIdRouteImport.update({
  id: '/present/$customerId',
  path: '/present/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdIndexRoute =
  CustomersCustomerIdIndexRouteImport.update({
    id: '/customers/$customerId/',
    path: '/customers/$customerId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomersCustomerIdSectionRoute =
  CustomersCustomerIdSectionRouteImport.update({
    id: '/customers/$customerId/$section',
    path: '/customers/$customerId/$section',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/present/$customerId': typeof PresentCustomerIdRoute
  '/customers/$customerId/$section': typeof CustomersCustomerIdSectionRoute
  '/customers/$customerId/': typeof CustomersCustomerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/present/$customerId': typeof PresentCustomerIdRoute
  '/customers/$customerId/$section': typeof CustomersCustomerIdSectionRoute
  '/customers/$customerId': typeof CustomersCustomerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/present/$customerId': typeof PresentCustomerIdRoute
  '/customers/$customerId/$section': typeof CustomersCustomerIdSectionRoute
  '/customers/$customerId/': typeof CustomersCustomerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/present/$customerId'
    | '/customers/$customerId/$section'
    | '/customers/$customerId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/present/$customerId'
    | '/customers/$customerId/$section'
    | '/customers/$customerId'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/present/$customerId'
    | '/customers/$customerId/$section'
    | '/customers/$customerId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  PresentCustomerIdRoute: typeof PresentCustomerIdRoute
  CustomersCustomerIdSectionRoute: typeof CustomersCustomerIdSectionRoute
  CustomersCustomerIdIndexRoute: typeof CustomersCustomerIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present/$customerId': {
      id: '/present/$customerId'
      path: '/present/$customerId'
      fullPath: '/present/$customerId'
      preLoaderRoute: typeof PresentCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId/': {
      id: '/customers/$customerId/'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId/'
      preLoaderRoute: typeof CustomersCustomerIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId/$section': {
      id: '/customers/$customerId/$section'
      path: '/customers/$customerId/$section'
      fullPath: '/customers/$customerId/$section'
      preLoaderRoute: typeof CustomersCustomerIdSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  PresentCustomerIdRoute: PresentCustomerIdRoute,
  CustomersCustomerIdSectionRoute: CustomersCustomerIdSectionRoute,
  CustomersCustomerIdIndexRoute: CustomersCustomerIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}