export const anthDataBlock=String.raw`
const CUSTOMER={id:"apex-gsi-synthetic",name:"Apex Systems Integrator (Synthetic)",nameStatus:"Golden example account · synthetic",industry:"Global systems integration",stage:"Scale adoption",week:8,provenance:"synthetic_sample",isGoldenExample:true,protected:true,defaultSample:true,sourceFile:"Synthetic Anthropic GSI Customer Success scenario",facts:{users:"AI platform team, delivery engineers, developers, transformation leaders, executive sponsors",product:"Claude API; Claude for Enterprise; Claude Code",committedTimeline:"Synthetic two-quarter success plan",roiTarget:"Prove measurable delivery and developer-productivity value while increasing healthy utilization across consumption- and seat-based products",kickoff:"Executive objectives aligned; product mix active; enablement and value-measurement work in progress",unvalidatedDependencies:"Final usage definitions, business-value baselines, and expansion-priority owners remain open",successMetrics:"Synthetic targets: API commitment utilization 80%+; Enterprise seat activation 85%+; Claude Code WAU 70%+; three approved value stories; two expansion use cases validated",currentSystems:"Enterprise identity; internal AI gateway; cloud platforms; developer toolchain; knowledge systems; analytics"}};
const SEED=[
["handoff","synthetic_sample",{title:"Business objective",value:"Scale Claude across high-value delivery and developer workflows while keeping adoption, value evidence, and expansion priorities explicit.",validation:"Synthetic golden example",note:"Candidate operating model derived from public role responsibilities."}],
["handoff","synthetic_sample",{title:"Product mix",value:"Claude API + Claude for Enterprise + Claude Code",validation:"Synthetic golden example",note:"Map each use case to the product pattern that best supports it; do not force one product across every workflow."}],
["integration","synthetic_sample",{name:"Claude API",purpose:"Consumption-based production and workflow use cases",connectorStatus:"Active / synthetic",technicalValidation:"Synthetic usage telemetry available for planning; no real Anthropic customer data is present."}],
["integration","synthetic_sample",{name:"Claude for Enterprise",purpose:"Seat-based knowledge and business workflows",connectorStatus:"Active / synthetic",technicalValidation:"Synthetic seat activation and weekly active usage metrics available."}],
["integration","synthetic_sample",{name:"Claude Code",purpose:"Seat-based developer workflows and engineering enablement",connectorStatus:"Active / synthetic",technicalValidation:"Synthetic weekly-active developer usage and champion data available."}],
["kpi","synthetic_sample",{name:"API commitment utilization",hypothesis:"Healthy consumption planning should align committed capacity with production use cases and future demand.",baseline:"58% synthetic trailing-period utilization",target:"80%+ sustainable utilization",metricDefinition:"Synthetic consumed API value divided by synthetic contracted commitment for the agreed period",sourceSystem:"Synthetic usage ledger",owner:"Customer Success + customer AI platform owner",cadence:"Weekly",calculation:"Consumed / committed",currentValue:"74%",realizedValue:"Not applicable",approval:"Synthetic sample"}],
["kpi","synthetic_sample",{name:"Enterprise seat activation",hypothesis:"Activated seats are an early prerequisite for value but do not by themselves prove adoption.",baseline:"62% synthetic activation",target:"85%+",metricDefinition:"Activated Claude for Enterprise seats divided by contracted seats",sourceSystem:"Synthetic seat ledger",owner:"Customer Success + enablement lead",cadence:"Weekly",calculation:"Activated / contracted",currentValue:"81%",realizedValue:"Not yet approved",approval:"Synthetic sample"}],
["kpi","synthetic_sample",{name:"Claude Code weekly active adoption",hypothesis:"Consistent weekly developer usage across priority teams is a stronger adoption signal than one-time activation.",baseline:"41% synthetic WAU",target:"70%+",metricDefinition:"Weekly active Claude Code users divided by provisioned target cohort",sourceSystem:"Synthetic developer-adoption ledger",owner:"Customer Success + developer enablement",cadence:"Weekly",calculation:"WAU / target cohort",currentValue:"63%",realizedValue:"Not yet approved",approval:"Synthetic sample"}],
["kpi","synthetic_sample",{name:"Approved value stories",hypothesis:"Expansion and continued investment are easier to justify when usage is connected to reviewed business outcomes.",baseline:"0 approved stories",target:"3 approved stories",metricDefinition:"Customer-approved outcome narratives with baseline, method, owner, and evidence source",sourceSystem:"Success plan",owner:"Customer Success + business value owners",cadence:"Monthly",calculation:"Count of approved stories",currentValue:"1 approved; 2 in validation",realizedValue:"One synthetic example approved",approval:"Synthetic sample"}],
["adoption","synthetic_sample",{name:"API utilization",value:"74% of synthetic commitment",period:"Current synthetic period",source:"Synthetic usage ledger",owner:"AI platform owner"}],
["adoption","synthetic_sample",{name:"Enterprise seat activation",value:"81%",period:"Current synthetic period",source:"Synthetic seat ledger",owner:"Enablement lead"}],
["adoption","synthetic_sample",{name:"Claude Code weekly active adoption",value:"63%",period:"Current synthetic period",source:"Synthetic developer-adoption ledger",owner:"Developer enablement"}],
["risk","synthetic_sample",{title:"Seat activation is outpacing repeat usage in two delivery practices",impact:"Contracted seats may not convert into durable adoption or value.",owner:"Customer Success + practice champions",mitigation:"Segment cohorts, run role-based enablement, identify workflow friction, and track weekly active usage after intervention.",escalationStatus:"Open",nextDecision:"Choose two practices for targeted Train-the-Trainer intervention."}],
["risk","synthetic_sample",{title:"Value evidence is fragmented across teams",impact:"Executive sponsors cannot yet connect aggregate usage to a concise business case.",owner:"Customer Success + business value owners",mitigation:"Define a measurement contract for three priority outcomes and require owner/source/baseline before claiming realized value.",escalationStatus:"Open",nextDecision:"Approve value-story owners and evidence sources."}],
["risk","synthetic_sample",{title:"Expansion ideas exceed current enablement capacity",impact:"New lines of business could create shallow pilots instead of scaled adoption.",owner:"Customer Success + Sales + customer AI CoE",mitigation:"Score expansion ideas by strategic value, readiness, adoption leverage, and evidence quality before onboarding.",escalationStatus:"Open",nextDecision:"Select the next two expansion use cases."}],
["stakeholder","synthetic_sample",{name:"Jordan Lee (Synthetic)",role:"Chief Technology Officer",organization:"Apex Systems Integrator (Synthetic)",email:"",phone:"",decisionRole:"Executive sponsor and investment narrative",status:"Active",notes:"Owns strategic AI direction and executive value review."}],
["stakeholder","synthetic_sample",{name:"Maya Chen (Synthetic)",role:"VP, AI Platform",organization:"Apex Systems Integrator (Synthetic)",email:"",phone:"",decisionRole:"Technical platform and consumption owner",status:"Active",notes:"Primary owner for API demand planning and platform standards."}],
["stakeholder","synthetic_sample",{name:"Rafael Ortiz (Synthetic)",role:"Director, Developer Enablement",organization:"Apex Systems Integrator (Synthetic)",email:"",phone:"",decisionRole:"Claude Code adoption and engineering enablement",status:"Active",notes:"Owns developer champion network and role-based enablement."}],
["stakeholder","synthetic_sample",{name:"Avery Morgan (Synthetic)",role:"AI Center of Excellence Lead",organization:"Apex Systems Integrator (Synthetic)",email:"",phone:"",decisionRole:"Change management, champions, and scalable adoption",status:"Active",notes:"Coordinates Train-the-Trainer and cross-practice adoption."}],
["action","synthetic_sample",{title:"Segment Enterprise and Claude Code cohorts by activation versus repeat usage",owner:"Customer Success + enablement",due:"Week 9",status:"In Progress",audience:"Customer / Internal"}],
["action","synthetic_sample",{title:"Validate baseline and evidence owner for developer cycle-time value story",owner:"Customer Success + Developer Enablement",due:"Week 10",status:"In Progress",audience:"Customer / Internal"}],
["action","synthetic_sample",{title:"Score five candidate expansion use cases and select next two",owner:"Customer Success + Sales + AI CoE",due:"Week 10",status:"Planned",audience:"Customer / Internal"}],
["meeting","synthetic_sample",{title:"Quarterly executive success review",type:"QBR",date:"Week 12",attendees:"CTO; VP AI Platform; Developer Enablement; AI CoE; Sales; Customer Success",objective:"Review adoption and utilization, validate realized value evidence, resolve adoption risks, and approve next-quarter expansion priorities.",notes:"Synthetic candidate-demo meeting."}],
["call_prep","internal_proposal",{title:"Quarterly executive success review",meetingDate:"Week 12",meetingType:"Executive QBR",objective:"Connect product usage to business outcomes, surface underutilization honestly, and leave with explicit decisions on enablement and expansion.",attendees:"CTO; VP AI Platform; Developer Enablement; AI CoE; Sales; Customer Success",opening:"Start with the customer objectives and decisions required, then show usage only in the context of progress toward those outcomes.",currentState:"Synthetic API commitment utilization is 74%. Enterprise seat activation is 81%. Claude Code weekly active adoption is 63%. One value story is approved and two are still in validation.",evidenceReady:"Synthetic usage dashboard; cohort adoption view; value-story measurement contracts; open risk list; expansion scorecard.",questions:"Which adoption gap matters most to the business objective? Which value stories have enough evidence to approve? Which new use cases are ready to scale rather than pilot? What enablement capacity exists next quarter?",decisions:"Approve two targeted enablement interventions; approve or return value stories; select next expansion use cases; confirm owners and dates.",escalationCriteria:"Do not convert a target, correlation, or anecdote into a realized-value claim without an agreed baseline, evidence source, method, and accountable owner.",followUp:"Publish decisions, owners, evidence gaps, adoption interventions, and expansion checkpoints into the success plan.",technologyNotes:"Keep API consumption and seat-based adoption distinct. Activation, weekly active usage, production consumption, quality, and realized value answer different questions.",assistantNotes:"Use only public Anthropic role context plus this synthetic account state. Never imply access to private Anthropic customer data, internal roadmap commitments, or real customer outcomes."}],
["assistant_profile","template",{title:"GSI Customer Success operating playbook",playbook:"GSI CUSTOMER SUCCESS BASELINE\n- Begin with customer business objectives, AI vision, and the operating decision that matters.\n- Treat API consumption and Enterprise / Claude Code seat adoption as different motions with different success metrics.\n- Separate activation from repeat usage and repeat usage from realized value.\n- Surface underutilization early and pair each gap with a specific adoption intervention.\n- Quantify value only when baseline, metric definition, evidence source, method, and owner are explicit.\n- Score expansion ideas by customer value, readiness, adoption capacity, technical fit, and evidence quality.\n- Use Train-the-Trainer, champions, and Center of Excellence patterns to make adoption scalable.\n- Use QBRs to drive decisions, not to recite activity.\n- Capture recurring customer signal for Product, Research, and GTM without promising roadmap outcomes.\n- Balance high-touch strategic work with reusable portfolio playbooks.",participants:"",updatedFrom:"Public Anthropic GSI CSM role + synthetic operating model"}],
["raci","template",{title:"GSI AI adoption RACI",rows:[],roles:["Executive Sponsor","AI Platform","Developer Enablement","AI CoE","Business Value Owner","Customer Success","Sales","Product / PM"],note:"Template. Assign real names and decision rights during account discovery."}],
["jira_config","internal_record",{siteUrl:"",deploymentBoardId:"",issueBoardId:"",projectKey:"",deploymentIssueType:"",issueType:"",connection:"Not connected",mode:"Optional governed work-system bridge"}]
];
const KB_SEED=[
{id:"kb-anth-adoption-value",slug:"adoption-to-value",title:"From AI Activation to Realized Value",summary:"A compact operating model for distinguishing access, repeat use, production consumption, and approved business value.",category:"Customer Success",tags:["adoption","value","roi","enablement"],status:"published",source:"internal_best_practice",authorLabel:"Candidate operating model",body:"ACCESS IS NOT ADOPTION\nSeat activation or API credentials only establish access.\n\nADOPTION IS NOT VALUE\nTrack repeat usage and production consumption separately from realized business outcomes.\n\nVALUE NEEDS A MEASUREMENT CONTRACT\nFor every outcome record the baseline, metric definition, source, method, owner, and review cadence.\n\nUNDERUTILIZATION NEEDS AN INTERVENTION\nSegment the cohort, identify friction, run a bounded enablement action, and remeasure.\n\nEXPANSION SHOULD FOLLOW PROOF\nPrioritize new use cases that have customer value, readiness, adoption capacity, technical fit, and an evidence path."}
];
`;
