#!/usr/bin/env python3
"""Clintware Plugin Forge MVP.

Local-first GIMP 3 Python plug-in scaffolding, legacy GIMP 2 Python-Fu scanning,
limited deterministic migration, validation, and installation.

The MVP deliberately uses only Python's standard library. A local-model adapter can
later produce operation plans that must pass the same validator before installation.
"""
from __future__ import annotations

import argparse
import ast
import json
import os
import re
import shutil
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable

APP_NAME = "Clintware Plugin Forge"
VERSION = "0.1.0"
MENU_ROOT = "<Image>/Clintware"


@dataclass(frozen=True)
class ValidationResult:
    ok: bool
    errors: tuple[str, ...]
    warnings: tuple[str, ...]


@dataclass(frozen=True)
class LegacyFinding:
    code: str
    message: str
    count: int


@dataclass(frozen=True)
class MigrationReport:
    source_name: str
    findings: tuple[LegacyFinding, ...]
    mapped_calls: tuple[str, ...]
    unmapped_pdb_calls: tuple[str, ...]
    generated_slug: str


CALL_PATTERNS = (
    (re.compile(r"(?:pdb\.)?gimp_selection_none\s*\([^\)]*\)"), "Gimp.Selection.none(image)"),
    (re.compile(r"(?:pdb\.)?gimp_selection_invert\s*\([^\)]*\)"), "Gimp.Selection.invert(image)"),
    (re.compile(r"(?:pdb\.)?gimp_displays_flush\s*\(\s*\)"), "Gimp.displays_flush()"),
)


def slugify(value: str) -> str:
    value = value.strip().lower()
    value = re.sub(r"[^a-z0-9]+", "-", value).strip("-")
    if not value:
        value = "clintware-plugin"
    if not value.startswith("clintware-"):
        value = f"clintware-{value}"
    return value[:72].rstrip("-")


def class_name(slug: str) -> str:
    bits = [part for part in slug.split("-") if part]
    return "".join(part.capitalize() for part in bits) + "Plugin"


def human_label(name: str) -> str:
    label = re.sub(r"[_-]+", " ", name).strip()
    label = re.sub(r"\s+", " ", label)
    return label.title() or "Clintware Plugin"


def detect_operation(prompt: str) -> str:
    text = prompt.lower()
    if "invert" in text and "selection" in text:
        return "Gimp.Selection.invert(image)"
    if (("clear" in text and "selection" in text) or any(term in text for term in ("clear selection", "deselect", "select none", "selection none"))):
        return "Gimp.Selection.none(image)"
    if any(term in text for term in ("refresh display", "flush display", "redraw", "refresh gimp")):
        return "Gimp.displays_flush()"
    return "# TODO: Add image operation here. The generated plug-in is a valid no-op scaffold."


def _indent_operations(operations: Iterable[str]) -> str:
    lines = []
    for op in operations:
        for line in op.splitlines() or [""]:
            lines.append("    " + line)
    return "\n".join(lines)


def render_plugin(*, prompt: str, name: str, menu_label: str | None = None,
                  operations: Iterable[str] | None = None) -> tuple[str, str]:
    slug = slugify(name)
    proc = f"plug-in-{slug}"
    cls = class_name(slug)
    label = menu_label.strip() if menu_label and menu_label.strip() else human_label(name)
    doc = prompt.strip() or "Generated by Clintware Plugin Forge."
    ops = tuple(operations) if operations is not None else (detect_operation(prompt),)
    op_block = _indent_operations(ops)

    source = f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generated by Clintware Plugin Forge {VERSION}."""

import gi
gi.require_version("Gimp", "3.0")
from gi.repository import Gimp
import sys

PROCEDURE_NAME = {proc!r}
MENU_LABEL = {label!r}
DESCRIPTION = {doc!r}


def run(procedure, run_mode, image, drawables, config, data):
{op_block}
    return procedure.new_return_values(Gimp.PDBStatusType.SUCCESS, None)


class {cls}(Gimp.PlugIn):
    def do_query_procedures(self):
        return [PROCEDURE_NAME]

    def do_create_procedure(self, name):
        if name != PROCEDURE_NAME:
            return None

        procedure = Gimp.ImageProcedure.new(
            self,
            name,
            Gimp.PDBProcType.PLUGIN,
            run,
            None,
        )
        procedure.set_sensitivity_mask(
            Gimp.ProcedureSensitivityMask.DRAWABLE |
            Gimp.ProcedureSensitivityMask.NO_DRAWABLES
        )
        procedure.set_menu_label(MENU_LABEL)
        procedure.add_menu_path({MENU_ROOT!r})
        procedure.set_documentation(DESCRIPTION, DESCRIPTION, None)
        procedure.set_attribution("Clintware", "Clintware", "2026")
        return procedure


Gimp.main({cls}.__gtype__, sys.argv)
'''
    return slug, source


def validate_plugin_source(source: str, expected_slug: str | None = None) -> ValidationResult:
    errors: list[str] = []
    warnings: list[str] = []
    try:
        tree = ast.parse(source)
    except SyntaxError as exc:
        return ValidationResult(False, (f"Python syntax error: {exc}",), ())

    required_text = {
        'gi.require_version("Gimp", "3.0")': "GIMP 3 GI version declaration missing",
        "Gimp.PlugIn": "Gimp.PlugIn subclass missing",
        "do_query_procedures": "do_query_procedures missing",
        "do_create_procedure": "do_create_procedure missing",
        "Gimp.ImageProcedure.new": "Gimp.ImageProcedure.new missing",
        f"procedure.add_menu_path({MENU_ROOT!r})": "Clintware image menu path missing",
        "Gimp.main(": "Gimp.main entrypoint missing",
        "procedure.new_return_values(Gimp.PDBStatusType.SUCCESS, None)": "success return missing",
    }
    for marker, message in required_text.items():
        if marker not in source:
            errors.append(message)

    if "gimpfu" in source:
        errors.append("legacy gimpfu import remains")
    if re.search(r"\bpdb\.[A-Za-z_]", source):
        warnings.append("legacy-style pdb call remains")

    classes = [node for node in tree.body if isinstance(node, ast.ClassDef)]
    if not classes:
        errors.append("no plug-in class found")

    if expected_slug:
        proc_literal = f"plug-in-{expected_slug}"
        if proc_literal not in source:
            errors.append("procedure name does not match folder/file slug")

    return ValidationResult(not errors, tuple(errors), tuple(warnings))


def write_plugin(output_root: Path, *, prompt: str, name: str,
                 menu_label: str | None = None, operations: Iterable[str] | None = None) -> Path:
    slug, source = render_plugin(prompt=prompt, name=name, menu_label=menu_label, operations=operations)
    validation = validate_plugin_source(source, slug)
    if not validation.ok:
        raise ValueError("Generated plug-in failed validation: " + "; ".join(validation.errors))
    folder = Path(output_root) / slug
    folder.mkdir(parents=True, exist_ok=True)
    plugin_file = folder / f"{slug}.py"
    plugin_file.write_text(source, encoding="utf-8", newline="\n")
    try:
        plugin_file.chmod(plugin_file.stat().st_mode | 0o100)
    except OSError:
        pass
    return plugin_file


def scan_legacy_source(source: str) -> tuple[LegacyFinding, ...]:
    checks = (
        ("gimpfu", r"(?:from\s+gimpfu\s+import|import\s+gimpfu)", "GIMP 2 Python-Fu/gimpfu import"),
        ("register", r"\bregister\s*\(", "legacy register() declaration"),
        ("main", r"\bmain\s*\(\s*\)", "legacy main() bootstrap"),
        ("pdb", r"\bpdb\.[A-Za-z_]", "legacy pdb.* calls"),
        ("py2-print", r"(?m)^\s*print\s+[^\(\n]", "possible Python 2 print statement"),
    )
    findings = []
    for code, pattern, message in checks:
        count = len(re.findall(pattern, source))
        if count:
            findings.append(LegacyFinding(code, message, count))
    return tuple(findings)


def _mapped_calls(source: str) -> tuple[str, ...]:
    calls: list[str] = []
    for pattern, replacement in CALL_PATTERNS:
        count = len(pattern.findall(source))
        calls.extend([replacement] * count)
    return tuple(calls)


def _unmapped_pdb_calls(source: str) -> tuple[str, ...]:
    all_calls = set(re.findall(r"\bpdb\.([A-Za-z_][A-Za-z0-9_]*)\s*\(", source))
    mapped_names = {"gimp_selection_none", "gimp_selection_invert", "gimp_displays_flush"}
    return tuple(sorted(all_calls - mapped_names))


def migrate_legacy_source(source: str, source_name: str = "legacy-plugin.py") -> tuple[MigrationReport, str]:
    findings = scan_legacy_source(source)
    calls = _mapped_calls(source)
    unmapped = _unmapped_pdb_calls(source)
    stem = Path(source_name).stem
    generated_name = f"{stem}-gimp3"
    operations: list[str] = list(calls)
    if unmapped:
        operations.append("# TODO: Unmapped legacy calls: " + ", ".join(unmapped))
    if not operations:
        operations.append("# TODO: No automatically mappable operations were found.")
    prompt = f"Migrated scaffold for {source_name}"
    slug, generated = render_plugin(prompt=prompt, name=generated_name, operations=operations)
    result = validate_plugin_source(generated, slug)
    if not result.ok:
        raise ValueError("Migrated scaffold failed validation: " + "; ".join(result.errors))
    report = MigrationReport(source_name, findings, calls, unmapped, slug)
    return report, generated


def default_plugin_roots() -> tuple[Path, ...]:
    home = Path.home()
    roots: list[Path] = []
    if sys.platform.startswith("win"):
        appdata = os.getenv("APPDATA")
        if appdata:
            roots.append(Path(appdata) / "GIMP" / "3.0" / "plug-ins")
    elif sys.platform == "darwin":
        roots.append(home / "Library" / "Application Support" / "GIMP" / "3.0" / "plug-ins")
    else:
        xdg = os.getenv("XDG_CONFIG_HOME")
        config = Path(xdg) if xdg else home / ".config"
        roots.append(config / "GIMP" / "3.0" / "plug-ins")
    return tuple(roots)


def install_plugin(plugin_file: Path, plugin_root: Path) -> Path:
    plugin_file = Path(plugin_file).resolve()
    folder = plugin_file.parent
    if plugin_file.name != f"{folder.name}.py":
        raise ValueError("GIMP 3 plug-in file and containing folder must share the same base name")
    source = plugin_file.read_text(encoding="utf-8")
    validation = validate_plugin_source(source, folder.name)
    if not validation.ok:
        raise ValueError("Refusing to install invalid plug-in: " + "; ".join(validation.errors))
    plugin_root = Path(plugin_root).expanduser().resolve()
    plugin_root.mkdir(parents=True, exist_ok=True)
    destination = plugin_root / folder.name
    if destination.exists():
        shutil.rmtree(destination)
    shutil.copytree(folder, destination)
    return destination / plugin_file.name


def cli(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="plugin-forge", description=__doc__)
    parser.add_argument("--version", action="version", version=VERSION)
    sub = parser.add_subparsers(dest="command", required=True)

    gen = sub.add_parser("generate", help="Generate a GIMP 3 Python plug-in scaffold")
    gen.add_argument("--prompt", required=True)
    gen.add_argument("--name", required=True)
    gen.add_argument("--menu-label")
    gen.add_argument("--output", default="out")

    scan = sub.add_parser("scan", help="Scan a legacy GIMP 2 Python plug-in")
    scan.add_argument("file")

    mig = sub.add_parser("migrate", help="Generate a GIMP 3 scaffold from mappable legacy calls")
    mig.add_argument("file")
    mig.add_argument("--output", default="out")

    val = sub.add_parser("validate", help="Validate a generated plug-in source file")
    val.add_argument("file")

    ins = sub.add_parser("install", help="Install a validated generated plug-in")
    ins.add_argument("file")
    ins.add_argument("--root", required=True)

    args = parser.parse_args(argv)

    if args.command == "generate":
        path = write_plugin(Path(args.output), prompt=args.prompt, name=args.name, menu_label=args.menu_label)
        print(path)
        return 0
    if args.command == "scan":
        source = Path(args.file).read_text(encoding="utf-8", errors="replace")
        print(json.dumps([asdict(f) for f in scan_legacy_source(source)], indent=2))
        return 0
    if args.command == "migrate":
        src = Path(args.file)
        report, generated = migrate_legacy_source(src.read_text(encoding="utf-8", errors="replace"), src.name)
        folder = Path(args.output) / report.generated_slug
        folder.mkdir(parents=True, exist_ok=True)
        target = folder / f"{report.generated_slug}.py"
        target.write_text(generated, encoding="utf-8", newline="\n")
        (folder / "migration-report.json").write_text(json.dumps(asdict(report), indent=2), encoding="utf-8")
        print(target)
        return 0
    if args.command == "validate":
        src = Path(args.file)
        result = validate_plugin_source(src.read_text(encoding="utf-8"), src.parent.name)
        print(json.dumps(asdict(result), indent=2))
        return 0 if result.ok else 2
    if args.command == "install":
        print(install_plugin(Path(args.file), Path(args.root)))
        return 0
    return 2


if __name__ == "__main__":
    raise SystemExit(cli())
