export const boomDataBlock = String.raw`
const CUSTOMER={id:"pinnacle-residential-group",name:"Pinnacle Residential Group",nameStatus:"Golden example customer · synthetic",industry:"Multifamily property management",stage:"CSM onboarding + support readiness",week:2,provenance:"synthetic_sample",isGoldenExample:true,protected:true,defaultSample:true,sourceFile:"Synthetic Boom CSM + Support dual-track scenario",facts:{users:"Property managers, leasing teams, applicants, residents, finance, and support",product:"BoomScreen + BoomReport",committedTimeline:"30-day synthetic onboarding and support-readiness plan",roiTarget:"Fast time-to-value, durable product adoption, measurable customer value, and low-friction support",kickoff:"Workflow discovery complete; PMS mapping, training, and support readiness in progress",unvalidatedDependencies:"PMS field mapping; property-team enablement; support severity and handoff rules",successMetrics:"Time to go-live; eligible workflow adoption; value evidence; SLA attainment; CSAT; first response; time to resolution",currentSystems:"Property management system; Attio-style CRM; ClickUp; Intercom; Zapier; Jira-style engineering escalation"}};
const SEED=[
["handoff","synthetic_sample",{title:"Customer success handoff",value:"Launch BoomScreen and BoomReport across the customer's property workflow while preserving stakeholder, value, and support context.",validation:"Synthetic golden example",note:"Candidate-built operating model based on public role requirements."}],
["integration","synthetic_sample",{name:"Property management system",purpose:"Applicant/property workflow and launch readiness",connectorStatus:"UAT",technicalValidation:"Core path works; two field mappings still need customer-owner validation."}],
["integration","synthetic_sample",{name:"Intercom-style support",purpose:"Applicant, renter, and property-manager service intake",connectorStatus:"Ready",technicalValidation:"Routing works; severity and escalation tags need final operating rules."}],
["integration","synthetic_sample",{name:"Zapier-style workflow",purpose:"Low-code operational automation",connectorStatus:"Pilot",technicalValidation:"Happy path validated; retry and duplicate handling remain under review."}],
["milestone","synthetic_sample",{title:"Complete property-team workflow UAT",owner:"CSM + customer operations",due:"Week 2",status:"In Progress",dependencies:"PMS field mapping"}],
["milestone","synthetic_sample",{title:"Approve support severity and handoff rules",owner:"Support lead + CSM",due:"Week 2",status:"In Progress",dependencies:"Queue taxonomy and escalation owner map"}],
["milestone","synthetic_sample",{title:"Publish first value and adoption review",owner:"CSM",due:"Week 4",status:"Planned",dependencies:"Metric definitions and usage source"}],
["risk","synthetic_sample",{title:"PMS field mapping is not fully accepted",impact:"Go-live could create applicant workflow confusion or manual correction.",owner:"CSM + customer operations + technical owner",mitigation:"Run end-to-end UAT on representative properties and document source-of-truth fields.",escalationStatus:"Open",nextDecision:"Approve mapping or hold go-live for the affected workflow."}],
["risk","synthetic_sample",{title:"Support severity differs by shift",impact:"The same customer issue may receive inconsistent urgency, ownership, or escalation.",owner:"Support lead",mitigation:"Define severity examples, owner rules, and evidence requirements; coach against QA samples.",escalationStatus:"Open",nextDecision:"Approve one severity rubric for US and offshore coverage."}],
["incident","synthetic_sample",{title:"Applicant screening status appears delayed for one PMS workflow",affected:"Applicants and leasing staff using one synthetic integration path",severity:"High",status:"Investigating",businessImpact:"Leasing teams may manually re-check applications and create repeat support contacts.",owner:"Support lead + CSM",nextAction:"Trace one affected application from submission through source workflow, Boom status, customer notification, and support contact.",jira:"",userBehavior:"Leasing staff refresh status and contact support when expected state is unclear.",contentFreshness:"Current synthetic scenario",sourceSystem:"PMS workflow + BoomScreen",configuration:"One synthetic workflow mapping",connector:"PMS -> BoomScreen",product:"BoomScreen",unknown:"Whether the issue is workflow configuration, timing expectation, customer process, or reproducible product behavior."}],
["engineering_issue","synthetic_sample",{title:"One synthetic integration path does not advance status after a completed screening event",severity:"High",affected:"One synthetic PMS workflow",environment:"Candidate demo",firstObserved:"Week 2",lastObserved:"Week 2",actual:"The downstream workflow remains in the prior status after the source event is complete.",expected:"The supported integration should advance or expose a documented reason it cannot.",reproducible:"Pending evidence gate",reproSteps:"Capture one affected example; confirm source event; compare supported mapping; reproduce with a control property; remove customer-side automation; capture timestamps and IDs.",evidence:"Synthetic IDs and timestamps only.",troubleshooting:"Control workflow identified; mapping reviewed; customer-side automation isolated for the next test.",workaround:"Use supported manual verification for the affected workflow while root cause is isolated.",businessImpact:"Repeat contacts, operational delay, and lower trust in automation.",engineeringAsk:"If reproduced on the supported path, confirm status-transition contract and defect ownership.",jiraKey:"",jiraUrl:"",status:"Evidence gathering"}],
["kpi","synthetic_sample",{name:"Time to value",hypothesis:"A structured implementation and enablement path should shorten time from handoff to reliable customer use.",baseline:"Not yet approved",target:"Customer-approved launch target",metricDefinition:"Elapsed time from approved handoff to agreed go-live/first-value milestone",sourceSystem:"CRM + implementation milestones",owner:"CSM",cadence:"Weekly during onboarding",calculation:"Calendar days between agreed milestone timestamps",currentValue:"Week 2 in progress",realizedValue:"Not yet approved",approval:"Synthetic sample"}],
["kpi","synthetic_sample",{name:"Support SLA attainment",hypothesis:"Clear routing, coverage, and severity rules should improve predictable support delivery.",baseline:"Synthetic baseline to establish",target:">95% within agreed SLA",metricDefinition:"Eligible support conversations/tickets meeting configured SLA target",sourceSystem:"Support reporting",owner:"Support lead",cadence:"Daily / weekly",calculation:"Met SLA / eligible SLA conversations",currentValue:"Synthetic 93%",realizedValue:"Not a real Boom metric",approval:"Synthetic sample"}],
["kpi","synthetic_sample",{name:"Customer satisfaction",hypothesis:"Consistent ownership and faster resolution should protect customer trust.",baseline:"Synthetic baseline to establish",target:">90% CSAT",metricDefinition:"Positive rated support interactions / rated interactions",sourceSystem:"Support reporting",owner:"Support lead",cadence:"Weekly",calculation:"Positive ratings / total ratings",currentValue:"Synthetic 91%",realizedValue:"Not a real Boom metric",approval:"Synthetic sample"}],
["adoption","synthetic_sample",{name:"Eligible workflow adoption",value:"Synthetic 72% in pilot properties",period:"Week 2",source:"Candidate demo usage model",owner:"CSM"}],
["adoption","synthetic_sample",{name:"Repeat support patterns shifted left",value:"Synthetic 25% documented or self-service ready",period:"Current sprint",source:"Support enablement tracker",owner:"Support lead"}],
["stakeholder","synthetic_sample",{name:"Morgan Lee (Synthetic)",role:"VP, Property Operations",organization:"Pinnacle Residential Group",email:"",phone:"",decisionRole:"Executive sponsor and value owner",status:"Active",notes:"Synthetic stakeholder for CSM value and rollout decisions."}],
["stakeholder","synthetic_sample",{name:"Jordan Patel (Synthetic)",role:"Director, Leasing Systems",organization:"Pinnacle Residential Group",email:"",phone:"",decisionRole:"PMS workflow and launch owner",status:"Active",notes:"Synthetic technical/operational champion."}],
["stakeholder","synthetic_sample",{name:"Casey Rivera (Synthetic)",role:"Resident Services Manager",organization:"Pinnacle Residential Group",email:"",phone:"",decisionRole:"Support experience and frontline process owner",status:"Active",notes:"Synthetic service stakeholder."}],
["meeting","synthetic_sample",{title:"Weekly customer operating review",type:"CSM + Support",date:"Week 2",attendees:"Executive sponsor; leasing systems owner; resident services; CSM; Support lead",objective:"Close launch dependencies, review adoption/service signals, and leave with explicit owners and next decisions.",notes:"Synthetic candidate-demo meeting."}],
["action","synthetic_sample",{title:"Finish representative property workflow UAT",owner:"CSM + customer operations",due:"Week 2",status:"In Progress",audience:"Customer / Internal"}],
["action","synthetic_sample",{title:"Publish one severity and escalation rubric across coverage teams",owner:"Support lead",due:"Week 2",status:"In Progress",audience:"Internal"}],
["action","synthetic_sample",{title:"Create help-center article for the highest-repeat screening-status question",owner:"Support enablement",due:"Week 3",status:"Planned",audience:"Customer"}],
["document","synthetic_sample",{name:"Pinnacle_Boom_Dual_Track_Golden_Example.md",classification:"Synthetic golden example",binaryStatus:"Built-in sample",approvedForBriefs:"Yes"}],
["raci","template",{title:"Boom CSM + Support shared RACI",rows:[],roles:["Customer","Customer Success Manager","Support Lead","Frontline Support","Product","Engineering","Operations"],note:"Template. Assign real names and decision rights during discovery."}],
["deployment_card","synthetic_sample",{title:"PMS workflow UAT",column:"In Progress",stageOrder:1,sprint:"Onboarding",owner:"CSM",dependency:"Customer source-of-truth mapping",jiraKey:"",jiraUrl:"",notes:"Representative-property acceptance required."}],
["deployment_card","synthetic_sample",{title:"Support severity contract",column:"In Progress",stageOrder:2,sprint:"Support readiness",owner:"Support lead",dependency:"Queue taxonomy",jiraKey:"",jiraUrl:"",notes:"Use one rubric across coverage shifts."}],
["deployment_card","synthetic_sample",{title:"Adoption + value baseline",column:"Ready",stageOrder:3,sprint:"Value",owner:"CSM",dependency:"Metric source and definition",jiraKey:"",jiraUrl:"",notes:"Do not claim realized ROI before customer approval."}],
["deployment_card","synthetic_sample",{title:"Repeat-contact shift-left playbook",column:"Planned",stageOrder:4,sprint:"Support scale",owner:"Support lead",dependency:"Closed issue pattern",jiraKey:"",jiraUrl:"",notes:"Graduate deterministic work to knowledge/automation."}],
["sprint","synthetic_sample",{name:"Customer launch cycle",weeks:"Weeks 1–4",goal:"Go live with validated workflows, trained users, clear value measures, and a stable support handoff",planned:7,completed:3,notes:"Synthetic CSM track."}],
["sprint","synthetic_sample",{name:"Support scale cycle",weeks:"Current two sprints",goal:"Improve service consistency, escalation quality, and repeat-contact deflection",planned:6,completed:2,notes:"Synthetic Support track."}],
["call_prep","internal_proposal",{title:"Week 2 dual-track customer review prep",meetingDate:"Week 2",meetingType:"Customer operating review",objective:"Close launch dependencies while connecting service health, adoption, and value to one customer plan.",attendees:"Customer sponsor; operations owner; support owner; CSM; Support lead",opening:"Confirm the customer's current objective, what changed, the active service impact, and the decisions needed today.",currentState:"PMS workflow UAT is in progress. Pilot adoption is growing. A synthetic screening-status issue is under investigation. Severity consistency needs one shared rubric.",evidenceReady:"Representative workflow tests; open actions; adoption snapshot; support SLA/CSAT/TTR snapshot; affected example; known-good control; current help content; owner map.",questions:"What blocks first value? Which adoption gap matters most? What is driving repeat contact? Is the active issue configuration, expectation, workflow, or reproducible behavior? Which decision needs Product or Engineering?",decisions:"Go-live readiness; adoption action; severity owner; escalation readiness; help-center/automation candidate; next value-review checkpoint.",escalationCriteria:"Escalate technical behavior only with reproducible evidence, expected vs actual, scope, IDs/timestamps, troubleshooting already completed, workaround, and customer impact.",followUp:"Send decisions, owners, dates, customer-facing commitments, support handoff, and reusable knowledge candidate.",technologyNotes:"Use current Boom product/help documentation and validate customer-specific PMS/integration behavior before changing production workflows.",assistantNotes:"Ground suggestions in the selected account. Separate public role context from synthetic data. Do not invent commitments or private Boom process."}],
["assistant_profile","template",{title:"Boom dual-track operating playbook",playbook:"CSM + SUPPORT BASELINE\n• Keep one customer context across onboarding, adoption, value, support, and escalation.\n• CSM owns relationship continuity, adoption, value, risk, and customer plan.\n• Support owns service execution, queue health, response/resolution quality, escalation evidence, and knowledge.\n• Establish expected vs actual before calling behavior a defect.\n• Never invent a commitment, SLA, product behavior, private process, or realized ROI.\n• Every escalation carries customer impact, evidence, owner, workaround, and a bounded ask.\n• After resolution, decide whether the pattern belongs in enablement, help content, automation, AI-assisted resolution, or Product feedback.",participants:"",updatedFrom:"Public role requirements + synthetic operating model"}],
["jira_config","internal_record",{siteUrl:"",deploymentBoardId:"",issueBoardId:"",projectKey:"",deploymentIssueType:"",issueType:"",connection:"Not connected",mode:"Optional system-of-record bridge"}]
];

const KB_SEED=[
{id:"kb-boom-shared-customer-context",slug:"shared-customer-context",title:"Shared Customer Context: CSM + Support",summary:"One customer story across onboarding, adoption, service, escalation, and value.",category:"Operating Model",tags:["customer-success","support","handoff"],status:"published",source:"internal_best_practice",authorLabel:"Candidate operating model",body:"PURPOSE\nKeep relationship context and service evidence together without blurring role ownership.\n\nCSM VIEW\n• Customer goals, stakeholders, implementation, adoption, value, risk, retention.\n\nSUPPORT VIEW\n• Current issue impact, queue/service health, response and resolution, escalations, repeat-contact patterns, knowledge.\n\nSHARED RULE\nEvery material issue should state customer impact, owner, next action, evidence, and what changes the conclusion. Every recurring solved issue should be considered for help content, automation, AI assistance, or Product feedback."},
{id:"kb-boom-support-scale",slug:"support-scale",title:"Support Scale: Evidence, Handoffs, and Shift Left",summary:"A repeatable path from incoming contact to resolution, escalation, and reuse.",category:"Support Operations",tags:["sla","csat","escalation","knowledge","ai"],status:"published",source:"internal_best_practice",authorLabel:"Candidate operating model",body:"INTAKE\nClassify customer, product, impact, urgency, and ownership.\n\nRESOLVE\nUse the supported path and capture the smallest evidence set that can prove the issue class.\n\nESCALATE\nInclude expected vs actual, scope, IDs/timestamps, troubleshooting, workaround, customer impact, and one bounded ask.\n\nSHIFT LEFT\nWhen a pattern is deterministic, graduate it to frontline guidance, a help-center article, automation, AI-assisted resolution, or proactive in-product support.\n\nMEASURE\nTrack SLA attainment, first response, time to resolution, CSAT, repeat contact, escalation reopen rate, and deflection using explicit definitions."}
];
`;
