const FUNCTIONAL_CARDS_STYLE = String.raw`<style id="cw-functional-cards-style">
.cw-aw-stat{cursor:pointer;text-align:left;color:inherit;width:100%;transition:.16s transform,.16s border-color}.cw-aw-stat:hover,.cw-aw-stat:focus-visible{border-color:#9f648c;transform:translateY(-1px);outline:none}.cw-card-section{margin:18px 0}.cw-custom-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.cw-custom-card{border:1px solid #302a36;background:#0a090e;border-radius:11px;padding:11px}.cw-custom-main{display:block;width:100%;border:0;background:transparent;color:inherit;text-align:left;padding:0;cursor:pointer}.cw-custom-label{font-size:8px;text-transform:uppercase;letter-spacing:.1em;color:#948c9c}.cw-custom-value{font-size:18px;font-weight:850;margin:3px 0}.cw-custom-detail{font-size:10px;color:#a49dab}.cw-custom-actions{display:flex;gap:6px;margin-top:9px}.cw-drill{display:none;margin:12px 0;border:1px solid #6a3b59;background:linear-gradient(135deg,rgba(159,100,140,.12),rgba(242,59,126,.04));border-radius:11px;padding:12px}.cw-drill.cw-open{display:block}.cw-drill-head{display:flex;justify-content:space-between;gap:10px}.cw-drill-title{font-weight:850}.cw-drill-copy{color:#b8b1bd;font-size:11px;margin-top:6px;white-space:pre-wrap}.cw-card-editor{display:none;border:1px solid #302a36;border-radius:11px;padding:12px;margin-top:9px}.cw-card-editor.cw-open{display:block}.cw-pdf-btn{border-color:#9f648c!important;color:#ffd2e3!important}.cw-account[data-account-id]{cursor:pointer}.cw-account[data-account-id]:focus-visible{outline:2px solid #ff8cb6;outline-offset:3px}.cw-overview-dialog{position:fixed;inset:0;z-index:2147483010;background:rgba(0,0,0,.78);display:none;place-items:center;padding:18px}.cw-overview-dialog.cw-open{display:grid}.cw-overview-panel{width:min(520px,100%);border:1px solid #493a49;border-radius:17px;background:#0d0b12;padding:19px;color:#f7f6f8;box-shadow:0 30px 100px #000}.cw-overview-panel h3{font-size:21px;margin:4px 0}.cw-overview-value{font-size:35px;font-weight:850;color:#ff8cb6}.cw-overview-copy{color:#b8b1bd;margin:7px 0 15px}.metrics .metric{cursor:pointer;transition:.16s transform,.16s border-color}.metrics .metric:hover,.metrics .metric:focus-visible{transform:translateY(-2px);border-color:#8d577b;outline:none}
@media(max-width:680px){.cw-custom-grid{grid-template-columns:1fr}}
</style>`;

const FUNCTIONAL_CARDS_SCRIPT = String.raw`<script id="cw-functional-cards-script">
(function(){
  'use strict';
  var KEY='an_demo_workspace_v2',activeId=null,editingCardId=null,installed=false;
  function parse(v){try{return JSON.parse(v)}catch(e){return null}}
  function getState(){var s=parse(localStorage.getItem(KEY));return s&&Array.isArray(s.accounts)?s:null}
  function save(s,eventName){localStorage.setItem(KEY,JSON.stringify(s));track(eventName)}
  function account(s){return s&&s.accounts.find(function(a){return a.id===activeId})}
  function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function track(n){if(!n)return;window.dataLayer=window.dataLayer||[];window.gtag=window.gtag||function(){window.dataLayer.push(arguments)};try{window.gtag('event',n,{demo_name:'abnormal_cs_command_center'})}catch(e){}}
  function seedCards(){var s=getState();if(!s)return;var changed=false;s.accounts.forEach(function(a){if(!Array.isArray(a.customCards)){a.customCards=[{id:'card-outcome',title:'Primary outcome',value:a.lifecycle||'Adopt',detail:a.nextAction||'Confirm the next customer-owned milestone.'},{id:'card-renewal',title:'Renewal motion',value:a.renewal||'Not set',detail:(a.risk||'Unrated')+' risk · '+(a.execEngaged?'Executive engaged':'Executive coverage needed')}];changed=true}});if(changed)save(s,'demo_custom_cards_seeded')}
  function customCard(c){return '<article class="cw-custom-card" data-custom-card-id="'+esc(c.id)+'"><button type="button" class="cw-custom-main" data-fn-action="drill-custom"><span class="cw-custom-label">'+esc(c.title)+'</span><span class="cw-custom-value">'+esc(c.value)+'</span><span class="cw-custom-detail">'+esc(c.detail||'Open for detail')+'</span></button><div class="cw-custom-actions"><button type="button" class="cw-btn" data-fn-action="edit-card">Edit card</button><button type="button" class="cw-btn cw-danger" data-fn-action="remove-card">Remove</button></div></article>'}
  function renderCards(){var a=account(getState()),grid=document.getElementById('cwCustomCards');if(!a||!grid)return;grid.innerHTML=a.customCards.length?a.customCards.map(customCard).join(''):'<div class="cw-aw-empty">No custom cards yet. Add one for the account signal you want visible.</div>'}
  function showDrill(title,copy){var p=document.getElementById('cwAwDrill');document.getElementById('cwAwDrillTitle').textContent=title;document.getElementById('cwAwDrillCopy').textContent=copy;p.classList.add('cw-open');p.scrollIntoView({block:'nearest',behavior:'smooth'});track('demo_overview_drilldown_open')}
  function drillSummary(kind){var a=account(getState());if(!a)return;var content={health:['Health '+(a.health==null?'unrated':a.health), 'Risk: '+(a.risk||'Unrated')+'\nLifecycle: '+(a.lifecycle||'Not set')+'\nRenewal: '+(a.renewal||'Not set')+'\nLast meaningful touch: '+(a.meaningfulTouch==null?'Not set':a.meaningfulTouch+' days')],risk:['Risk: '+(a.risk||'Unrated'), 'Watch list: '+(a.watch?'Yes':'No')+'\nNext action: '+(a.nextAction||'No next action entered')+'\nAccount notes: '+(a.notes||'No notes entered')],adoption:['Adoption '+(a.adoption==null?'unrated':a.adoption+'%'), 'Lifecycle: '+(a.lifecycle||'Not set')+'\nStatus: '+(a.active===false?'Inactive':'Active')+'\nCustomer context: '+(a.customInfo||'No custom context entered')],owner:['Owner: '+(a.owner||'Unassigned'), 'Executive engagement: '+(a.execEngaged?'Engaged':'Needs coverage')+'\nRenewal: '+(a.renewal||'Not set')+'\nNext action: '+(a.nextAction||'No next action entered')]}[kind];if(content)showDrill(content[0],content[1])}
  function openEditor(c){editingCardId=c?c.id:null;var f=document.getElementById('cwCardForm');f.reset();f.elements.title.value=c?c.title:'';f.elements.value.value=c?c.value:'';f.elements.detail.value=c?c.detail:'';document.getElementById('cwCardEditorTitle').textContent=c?'Edit custom overview card':'Add custom overview card';document.getElementById('cwCardEditor').classList.add('cw-open');f.elements.title.focus()}
  function closeEditor(){editingCardId=null;document.getElementById('cwCardEditor').classList.remove('cw-open')}
  function saveCard(e){e.preventDefault();var s=getState(),a=account(s),f=e.currentTarget,v=Object.fromEntries(new FormData(f).entries());if(!a)return;var title=String(v.title||'').trim(),value=String(v.value||'').trim();if(!title||!value)return alert('Card title and value are required.');var c=editingCardId&&a.customCards.find(function(x){return x.id===editingCardId});var edit=!!c;if(!c){c={id:'card-'+Date.now()+'-'+Math.floor(Math.random()*10000)};a.customCards.push(c)}c.title=title;c.value=value;c.detail=String(v.detail||'').trim();a.modified=true;save(s,edit?'demo_custom_card_updated':'demo_custom_card_added');closeEditor();renderCards();showDrill(c.title,c.value+(c.detail?'\n'+c.detail:''))}
  function pdfText(s){return String(s==null?'':s).normalize('NFKD').replace(/[^\x20-\x7E]/g,' ').replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)')}
  function wrap(s,n){var words=String(s||'').replace(/\s+/g,' ').trim().split(' '),out=[],line='';words.forEach(function(w){var next=line?line+' '+w:w;if(next.length>n&&line){out.push(line);line=w}else line=next});if(line)out.push(line);return out.length?out:['-']}
  function buildPdf(a){
    var W=612,H=792,M=42,pages=[],ops=[],y=704;
    function text(x,yy,size,s,bold,color){ops.push('BT /'+(bold?'F2':'F1')+' '+size+' Tf '+(color||'0.16 0.13 0.18')+' rg '+x+' '+yy+' Td ('+pdfText(s)+') Tj ET')}
    function header(){ops=['0.07 0.055 0.085 rg 0 738 '+W+' 54 re f','0.95 0.23 0.49 rg '+M+' 752 94 3 re f'];text(M,765,9,'CLINTWARE / CUSTOMER SUCCESS',true,'1 1 1');var d='Prepared '+new Date().toISOString().slice(0,10);text(Math.max(360,W-M-d.length*5.1),765,8,d,false,'0.78 0.74 0.81');y=704}
    function finish(){pages.push(ops.join('\n'));header()}
    function need(h){if(y-h<68)finish()}
    function title(s){need(40);text(M,y,20,s,true);y-=31}
    function section(h,items){need(34);text(M,y,11,h.toUpperCase(),true,'0.72 0.20 0.43');y-=19;items.forEach(function(item){var lines=wrap(item,88);need(lines.length*14+8);lines.forEach(function(line,i){text(M+(i?10:0),y,9,(i?'': '- ')+line,false);y-=13});y-=4});y-=6}
    header();title(a.name+' - Meeting Brief');text(M,y,9,'Prepared for interview purposes for Clinton Kosh',false,'0.38 0.34 0.41');y-=24;
    section('Account snapshot',['Segment: '+(a.segment||'Not set')+' | Lifecycle: '+(a.lifecycle||'Not set'),'Health: '+(a.health==null?'Unrated':a.health)+' | Risk: '+(a.risk||'Unrated')+' | Adoption: '+(a.adoption==null?'Unrated':a.adoption+'%'),'Renewal: '+(a.renewal||'Not set')+' | Owner: '+(a.owner||'Unassigned'),'Executive engagement: '+(a.execEngaged?'Engaged':'Needs coverage')]);
    section('Call focus',['Next action: '+(a.nextAction||'No next action entered'),'Customer notes: '+(a.notes||'No notes entered'),'Custom context: '+(a.customInfo||'No custom context entered')]);
    section('Custom overview cards',(a.customCards||[]).map(function(c){return c.title+': '+c.value+(c.detail?' - '+c.detail:'')}));
    section('Stakeholders',(a.users||[]).map(function(u){return u.name+' | '+(u.title||'Title not set')+' | '+(u.lane||'Lane not set')+' | '+(u.status||'Status not set')+(u.email?' | '+u.email:'')}));
    section('Proposed agenda',['Confirm desired outcome and current evidence','Review blocker, risk, and accountable decision owner','Agree next milestone, owner, and date','Capture questions and follow-up commitments']);
    finish();text(M,704,18,'Manual call notes',true);y=670;for(var i=0;i<24;i++){ops.push('0.78 0.75 0.80 RG 0.5 w '+M+' '+y+' m '+(W-M)+' '+y+' l S');y-=24}pages.push(ops.join('\n'));
    var total=pages.length;pages=pages.map(function(p,i){var label='Page '+(i+1)+' of '+total,x=Math.max(M,W-M-label.length*4.7);return p+'\n0.08 0.07 0.10 rg 0 0 '+W+' 36 re f\nBT /F1 8 Tf 0.82 0.79 0.84 rg '+M+' 14 Td (Synthetic interview demo - confidential) Tj ET\nBT /F1 8 Tf 0.82 0.79 0.84 rg '+x+' 14 Td ('+label+') Tj ET'});
    var objs=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids ['+pages.map(function(_,i){return (5+i*2)+' 0 R'}).join(' ') +'] /Count '+pages.length+' >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>'];
    pages.forEach(function(p,i){var content=6+i*2;objs.push('<< /Type /Page /Parent 2 0 R /MediaBox [0 0 '+W+' '+H+'] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents '+content+' 0 R >>');objs.push('<< /Length '+p.length+' >>\nstream\n'+p+'\nendstream')});
    var pdf='%PDF-1.4\n',offset=[0];objs.forEach(function(o,i){offset.push(pdf.length);pdf+=(i+1)+' 0 obj\n'+o+'\nendobj\n'});var xref=pdf.length;pdf+='xref\n0 '+(objs.length+1)+'\n0000000000 65535 f \n';for(var j=1;j<=objs.length;j++)pdf+=String(offset[j]).padStart(10,'0')+' 00000 n \n';pdf+='trailer\n<< /Size '+(objs.length+1)+' /Root 1 0 R >>\nstartxref\n'+xref+'\n%%EOF';return new Blob([pdf],{type:'application/pdf'})
  }
  window.cwBuildAbnormalMeetingBrief=buildPdf;
  function downloadFor(a){if(!a)return;var blob=buildPdf(a),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=String(a.name||'account').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-meeting-brief.pdf';document.body.appendChild(link);link.click();link.remove();setTimeout(function(){URL.revokeObjectURL(url)},1000);track('demo_meeting_brief_pdf_download')}
  function downloadPdf(){downloadFor(account(getState()))}
  function baseBriefAccount(){try{var name=(document.querySelector('#accountModal .modal-head h3')||{}).textContent||'',a=typeof DATA!=='undefined'&&DATA.accounts&&DATA.accounts.find(function(x){return x.name===name});if(!a)return null;return {name:a.name,segment:a.segment,lifecycle:a.lifecycle,health:a.health,risk:a.risk,adoption:a.adoption,renewal:a.renewal,owner:a.owner,execEngaged:a.exec==='Strong',nextAction:a.action,notes:a.blocker||'No material blocker entered.',customInfo:'Active modules: '+a.modules.join(', ')+'. Connected systems: '+a.integrations.join(', ')+'.',customCards:[{title:'Success outcome',value:a.outcomes[0]||'Not set',detail:(a.outcomes||[]).slice(1).join('; ')},{title:'Support trend',value:a.support||'Not set',detail:'Last meaningful touch: '+a.touch+' days'}],users:[]}}catch(e){return null}}
  window.cwBaseAbnormalBriefAccount=baseBriefAccount;
  function bindBaseBrief(){var modal=document.getElementById('accountModal'),brief=modal&&modal.querySelector('#brief .card');if(!brief||brief.querySelector('[data-cw-base-pdf]'))return;var b=document.createElement('button');b.type='button';b.className='btn primary';b.dataset.cwBasePdf='1';b.style.marginTop='12px';b.textContent='Download formatted meeting brief PDF';b.addEventListener('click',function(){downloadFor(baseBriefAccount())});brief.appendChild(b)}
  function onAction(e){var b=e.target.closest('[data-fn-action]');if(!b)return;var action=b.dataset.fnAction;if(action==='close-drill')return document.getElementById('cwAwDrill').classList.remove('cw-open');if(action==='add-card')return openEditor(null);if(action==='cancel-card')return closeEditor();if(action==='download-pdf')return downloadPdf();var row=b.closest('[data-custom-card-id]'),a=account(getState()),c=row&&a&&a.customCards.find(function(x){return x.id===row.dataset.customCardId});if(!c)return;if(action==='drill-custom')showDrill(c.title,c.value+(c.detail?'\n'+c.detail:''));if(action==='edit-card')openEditor(c);if(action==='remove-card'){if(!confirm('Remove this custom overview card?'))return;a.customCards=a.customCards.filter(function(x){return x.id!==c.id});a.modified=true;var s=getState(),live=account(s);live.customCards=a.customCards;save(s,'demo_custom_card_removed');renderCards()}}
  function bindWorkspace(){var modal=document.getElementById('cwAccountWorkspaceModal');if(!modal||document.getElementById('cwCustomSection'))return;var summary=modal.querySelector('.cw-aw-summary'),kinds=['health','risk','adoption','owner'];summary.querySelectorAll('.cw-aw-stat').forEach(function(el,i){var b=document.createElement('button');b.type='button';b.className=el.className;b.dataset.drill=kinds[i];b.innerHTML=el.innerHTML;el.replaceWith(b)});summary.addEventListener('click',function(e){var b=e.target.closest('[data-drill]');if(b)drillSummary(b.dataset.drill)});var actions=modal.querySelector('.cw-aw-actions');actions.insertAdjacentHTML('beforeend','<button type="button" class="cw-btn cw-pdf-btn" data-fn-action="download-pdf">Download meeting brief PDF</button>');actions.insertAdjacentHTML('afterend','<div class="cw-drill" id="cwAwDrill"><div class="cw-drill-head"><div class="cw-drill-title" id="cwAwDrillTitle"></div><button type="button" class="cw-btn" data-fn-action="close-drill">Close</button></div><div class="cw-drill-copy" id="cwAwDrillCopy"></div></div><section class="cw-card-section" id="cwCustomSection"><div class="cw-aw-sectionhead"><div><div class="cw-aw-sectiontitle">Custom overview cards</div><div class="cw-aw-sectioncopy">Editable account signals. Select a card to drill down.</div></div><button type="button" class="cw-btn cw-primary" data-fn-action="add-card">+ Add card</button></div><div class="cw-custom-grid" id="cwCustomCards"></div><div class="cw-card-editor" id="cwCardEditor"><div class="cw-aw-sectiontitle" id="cwCardEditorTitle">Add custom overview card</div><form id="cwCardForm"><div class="cw-aw-formgrid"><div class="cw-aw-field"><label>Card title</label><input class="cw-aw-input" name="title" required></div><div class="cw-aw-field"><label>Headline value</label><input class="cw-aw-input" name="value" required></div><div class="cw-aw-field cw-aw-wide"><label>Drill-down detail</label><textarea class="cw-aw-input" name="detail" rows="3"></textarea></div></div><div class="cw-aw-formactions"><button type="button" class="cw-btn" data-fn-action="cancel-card">Cancel</button><button type="submit" class="cw-btn cw-primary">Save card</button></div></form></div></section>');modal.addEventListener('click',onAction);document.getElementById('cwCardForm').addEventListener('submit',saveCard);new MutationObserver(function(){if(modal.classList.contains('cw-open')){var title=document.getElementById('cwAwTitle').textContent,s=getState(),a=s&&s.accounts.find(function(x){return x.name===title});if(a){activeId=a.id;seedCards();renderCards();document.getElementById('cwAwDrill').classList.remove('cw-open')}}}).observe(modal,{attributes:true,attributeFilter:['class']})}
  function bindAccountCards(){document.querySelectorAll('#cwList .cw-account[data-account-id]').forEach(function(card){if(card.dataset.fnBound)return;card.dataset.fnBound='1';card.tabIndex=0;function open(e){if(e.target.closest('button,input,select,a,textarea'))return;var b=card.querySelector('[data-user-action="open-account"]');if(b)b.click()}card.addEventListener('click',open);card.addEventListener('keydown',function(e){if((e.key==='Enter'||e.key===' ')&&!e.target.closest('button,input,select,a,textarea')){e.preventDefault();var b=card.querySelector('[data-user-action="open-account"]');if(b)b.click()}})})}
  var overviewMap={'Portfolio':['Accounts','All synthetic customer records and their current lifecycle state.'],'At risk':['Risk & Escalations','Accounts whose stored risk is High or Critical. Open the queue to review evidence, owner, and proposed intervention.'],'Avg health':['Analytics','Portfolio average of the visible explainable account health scores. Open analytics to inspect the underlying distribution.'],'Renewals 30 / 60 / 90':['Renewals','Upcoming renewal decision windows grouped by days remaining. Open the renewal cockpit for account-level context.'],'Exec coverage':['Accounts','Share of accounts with Strong executive engagement in the stored synthetic dataset.'],'Multi-product':['Expansion / App Store','Accounts with three or more active modules. Open readiness signals to review adjacent-solution context.']};
  function bindBaseOverview(){document.querySelectorAll('.metrics .metric').forEach(function(card){if(card.dataset.fnBound)return;card.dataset.fnBound='1';card.tabIndex=0;card.setAttribute('role','button');var run=function(){var label=(card.querySelector('.label')||{}).textContent||'',info=overviewMap[label];if(!info)return;document.getElementById('cwOverviewTitle').textContent=label;document.getElementById('cwOverviewValue').textContent=(card.querySelector('.value')||{}).textContent||'';document.getElementById('cwOverviewCopy').textContent=info[1];document.getElementById('cwOverviewOpen').dataset.target=info[0];document.getElementById('cwOverviewDialog').classList.add('cw-open');track('demo_portfolio_card_drilldown')};card.addEventListener('click',run);card.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();run()}})})}
  function install(){if(installed)return;installed=true;seedCards();bindWorkspace();var d=document.createElement('div');d.innerHTML='<div class="cw-overview-dialog" id="cwOverviewDialog" role="dialog" aria-modal="true"><section class="cw-overview-panel"><div class="cw-aw-kicker">Portfolio drill-down</div><h3 id="cwOverviewTitle"></h3><div class="cw-overview-value" id="cwOverviewValue"></div><div class="cw-overview-copy" id="cwOverviewCopy"></div><div class="cw-aw-actions"><button type="button" class="cw-btn cw-primary" id="cwOverviewOpen">Open detailed view</button><button type="button" class="cw-btn" id="cwOverviewClose">Close</button></div></section></div>';document.body.appendChild(d);document.getElementById('cwOverviewClose').onclick=function(){document.getElementById('cwOverviewDialog').classList.remove('cw-open')};document.getElementById('cwOverviewDialog').addEventListener('click',function(e){if(e.target===this)this.classList.remove('cw-open')});document.getElementById('cwOverviewOpen').onclick=function(){var target=this.dataset.target,btn=[].slice.call(document.querySelectorAll('.nav button,.mobile-nav button')).find(function(x){return x.textContent.trim()===target});document.getElementById('cwOverviewDialog').classList.remove('cw-open');if(btn)btn.click()};var root=document.getElementById('cwList')||document.body;new MutationObserver(function(){bindAccountCards();bindBaseOverview()}).observe(root,{childList:true,subtree:true});new MutationObserver(function(){bindBaseOverview();bindBaseBrief()}).observe(document.getElementById('view')||document.body,{childList:true,subtree:true});var baseModal=document.getElementById('accountModal');if(baseModal)new MutationObserver(bindBaseBrief).observe(baseModal,{attributes:true,childList:true,subtree:true});bindAccountCards();bindBaseOverview();bindBaseBrief();track('demo_functional_cards_ready')}
  function boot(){var n=0,t=setInterval(function(){if(document.getElementById('cwAccountWorkspaceModal')){clearInterval(t);install()}else if(++n>100)clearInterval(t)},50)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot()
})();
</script>`;

export function enhanceFunctionalCards(html) {
  if (!html || html.includes('id="cw-functional-cards-script"')) return html;
  const injection = FUNCTIONAL_CARDS_STYLE + FUNCTIONAL_CARDS_SCRIPT;
  return html.includes('</body>') ? html.replace('</body>', injection + '</body>') : html + injection;
}
