from pathlib import Path

p=Path('public/summertime-crmdemo/index.html')
s=p.read_text()
if 'id="dtex-p1-edit-parity"' in s:
    print('DTEX edit parity already present')
    raise SystemExit(0)

script=r'''<script id="dtex-p1-edit-parity">
(function(){
'use strict';
noteBlock=function(a){const list=notes[a.id]||[];return`<div class="record-list">${list.length?list.map((n,i)=>`<div class="record"><div class="record-head"><b>Account note</b><small>${esc(n.when)}</small></div><p>${esc(n.text)}</p><div class="dtex-editor-actions"><button class="btn record-delete" data-edit-note="${a.id}:${i}">Edit</button><button class="btn record-delete" data-del-note="${a.id}:${i}">Delete</button></div></div>`).join(''):'<div class="field"><span>Notes</span><b>No local account notes yet.</b></div>'}</div><div class="form-grid"><textarea id="account-note-text" class="wide" placeholder="Add factual account note, decision, follow-up, commitment, or observation"></textarea><button class="btn primary wide" data-add-note="${a.id}">Add account note</button></div>`};
meetingBlock=function(a){const base=a.meetings.map(m=>`<div class="record"><div class="record-head"><b>${esc(m.type)}</b><small>${fmtDate(m.date)}</small></div><p><b>Attendees:</b> ${esc(m.attendees)}<br>${esc(m.notes)}</p><div style="font-size:7px;color:var(--muted);margin-top:5px">Seeded meeting record</div></div>`).join(''),added=(meetingAdds[a.id]||[]).map((m,i)=>`<div class="record"><div class="record-head"><b>${esc(m.type)}</b><small>${fmtDate(m.date)}</small></div><p><b>Attendees:</b> ${esc(m.attendees)}<br>${esc(m.notes)}</p><div class="dtex-editor-actions"><button class="btn record-delete" data-edit-meeting="${a.id}:${i}">Edit</button><button class="btn record-delete" data-del-meeting="${a.id}:${i}">Delete</button></div></div>`).join('');return`<div class="record-list">${base+added}</div><div class="form-grid"><input id="meeting-date" type="date" value="${daysFromNow(0)}"><input id="meeting-type" placeholder="Meeting type / title"><input id="meeting-attendees" class="wide" placeholder="Attendees"><textarea id="meeting-notes" class="wide" placeholder="Factual meeting notes, decisions, measurements, and commitments"></textarea><button class="btn primary wide" data-add-meeting="${a.id}">Add meeting log</button></div>`};
peopleBlock=function(a){const combined=allPeople(a);return`<div class="stakeholders">${combined.map((p,i)=>`<div class="person"><div class="person-head"><div><b>${esc(p.name)}</b><br><span>${esc(p.role)}</span></div><span class="pill">${esc(p.status)}</span></div><p>${esc(p.lane)}</p>${i>=a.people.length?`<div class="dtex-editor-actions"><button class="btn record-delete" data-edit-person="${a.id}:${i-a.people.length}">Edit</button><button class="btn record-delete" data-del-person="${a.id}:${i-a.people.length}">Delete</button></div>`:'<div style="font-size:7px;color:var(--muted);margin-top:5px">Seeded stakeholder record</div>'}</div>`).join('')}</div><div class="form-grid"><input id="person-name" placeholder="Employee / stakeholder name"><input id="person-role" placeholder="Role / title"><select id="person-status"><option>Active</option><option>New</option><option>Transitioning</option><option>Inactive</option></select><input id="person-lane" placeholder="Responsibility / relationship lane"><button class="btn primary wide" data-add-person="${a.id}">Add employee / stakeholder</button></div>`};
function restoreButton(btn,attr,id,label){for(const a of [...btn.attributes])if(a.name.startsWith('data-update-'))btn.removeAttribute(a.name);btn.setAttribute(attr,id);btn.textContent=label}
document.addEventListener('click',e=>{
  const en=e.target.closest?.('[data-edit-note]');if(en){const[id,i]=en.dataset.editNote.split(':'),n=(notes[id]||[])[+i],ta=document.getElementById('account-note-text'),b=document.querySelector(`[data-add-note="${id}"]`);if(!n||!ta||!b)return;ta.value=n.text;b.removeAttribute('data-add-note');b.dataset.updateNote=`${id}:${i}`;b.textContent='Save note changes';ta.focus();return}
  const un=e.target.closest?.('[data-update-note]');if(un){const[id,i]=un.dataset.updateNote.split(':'),t=document.getElementById('account-note-text').value.trim();if(!t)return;notes[id][+i]={...notes[id][+i],text:t,when:new Date().toLocaleString()};store(NOTES_KEY,notes);renderDrawer(accounts.find(a=>a.id===id));sendEvent('crm_account_note_edit',{account_segment:accounts.find(a=>a.id===id).segment});return}
  const em=e.target.closest?.('[data-edit-meeting]');if(em){const[id,i]=em.dataset.editMeeting.split(':'),m=(meetingAdds[id]||[])[+i],b=document.querySelector(`[data-add-meeting="${id}"]`);if(!m||!b)return;document.getElementById('meeting-date').value=m.date;document.getElementById('meeting-type').value=m.type;document.getElementById('meeting-attendees').value=m.attendees;document.getElementById('meeting-notes').value=m.notes;b.removeAttribute('data-add-meeting');b.dataset.updateMeeting=`${id}:${i}`;b.textContent='Save meeting changes';return}
  const um=e.target.closest?.('[data-update-meeting]');if(um){const[id,i]=um.dataset.updateMeeting.split(':'),date=document.getElementById('meeting-date').value,type=document.getElementById('meeting-type').value.trim(),attendees=document.getElementById('meeting-attendees').value.trim(),mnotes=document.getElementById('meeting-notes').value.trim();if(!date||!type||!mnotes)return;meetingAdds[id][+i]={date,type,attendees,notes:mnotes};store(MEETINGS_KEY,meetingAdds);renderDrawer(accounts.find(a=>a.id===id));renderMeetings();sendEvent('crm_meeting_log_edit',{account_segment:accounts.find(a=>a.id===id).segment});return}
  const ep=e.target.closest?.('[data-edit-person]');if(ep){const[id,i]=ep.dataset.editPerson.split(':'),x=(peopleAdds[id]||[])[+i],b=document.querySelector(`[data-add-person="${id}"]`);if(!x||!b)return;document.getElementById('person-name').value=x.name;document.getElementById('person-role').value=x.role;document.getElementById('person-status').value=x.status;document.getElementById('person-lane').value=x.lane;b.removeAttribute('data-add-person');b.dataset.updatePerson=`${id}:${i}`;b.textContent='Save stakeholder changes';return}
  const up=e.target.closest?.('[data-update-person]');if(up){const[id,i]=up.dataset.updatePerson.split(':'),name=document.getElementById('person-name').value.trim(),role=document.getElementById('person-role').value.trim(),status=document.getElementById('person-status').value,lane=document.getElementById('person-lane').value.trim();if(!name||!role)return;peopleAdds[id][+i]={name,role,status,lane};store(PEOPLE_KEY,peopleAdds);renderDrawer(accounts.find(a=>a.id===id));renderMeetings();sendEvent('crm_stakeholder_edit',{account_segment:accounts.find(a=>a.id===id).segment});return}
},false);
})();
</script>'''

s=s.replace('</body>',script+'\n</body>',1)
p.write_text(s)
print('added DTEX edit parity for local notes, meetings and stakeholders')
