export const smspcDataBlock = String.raw`
const CUSTOMER={id:"aegis-national-bank",name:"Aegis National Bank",nameStatus:"Golden example opportunity · synthetic",industry:"Financial services",stage:"Evaluation design · technical proof plan",week:2,provenance:"synthetic_sample",isGoldenExample:true,protected:true,defaultSample:true,sourceFile:"Synthetic SimSpace Senior Solution Engineer scenario",facts:{users:"CISO staff, SOC leadership, detection engineering, AI security, platform engineering, procurement",product:"AI Proving Grounds + realistic cyber range evaluation",committedTimeline:"5-week synthetic technical evaluation",roiTarget:"Prove measurable improvement in agent + human readiness before production use",kickoff:"Outcome discovery complete; evaluation architecture and success criteria in progress",unvalidatedDependencies:"Security-tool integrations; identity boundaries; representative telemetry; agent escalation gates; customer test-data approval",successMetrics:"Environment fidelity; integration readiness; scenario coverage; agent trajectory evidence; MTTD/MTTR improvement; technical acceptance",currentSystems:"Microsoft Sentinel; CrowdStrike; ServiceNow; Azure; Kubernetes; custom AI agents; CI/CD"}};
const SEED=[
["handoff","synthetic_sample",{title:"Outcome discovery",value:"Prove whether AI agents and human analysts can operate together safely under realistic attack pressure before agent rollout.",validation:"Synthetic golden example",note:"Candidate-built operating model derived from the public Senior Solution Engineer role and SimSpace public platform language."}],
["handoff","synthetic_sample",{title:"Decision criteria",value:"Replica fidelity, measurable detection/response improvement, auditable agent trajectories, safe escalation to humans, repeatable execution.",validation:"Synthetic golden example",note:"Criteria must be confirmed with the real buying team."}],
["integration","synthetic_sample",{name:"Microsoft Sentinel",purpose:"SIEM telemetry, detections, incidents, and evidence export",connectorStatus:"Design",technicalValidation:"Define event schema, authentication, rate limits, and bidirectional workflow boundaries."}],
["integration","synthetic_sample",{name:"CrowdStrike",purpose:"Endpoint telemetry and validation of defensive behavior",connectorStatus:"Design",technicalValidation:"Confirm supported API surface, event timing, tenant constraints, and test-account scope."}],
["integration","synthetic_sample",{name:"ServiceNow",purpose:"Incident / change workflow and evidence handoff",connectorStatus:"Ready for mapping",technicalValidation:"Map scenario evidence to customer ticket taxonomy without making the range the system of record."}],
["integration","synthetic_sample",{name:"Customer AI agents",purpose:"Evaluate tool calls, escalation gates, recovery behavior, and mission outcomes",connectorStatus:"Pilot",technicalValidation:"Use synthetic or approved data only; capture trajectories and decision points, not just final outcomes."}],
["milestone","synthetic_sample",{title:"Approve evaluation success criteria",owner:"Solution Engineer + customer security sponsor",due:"Week 2",status:"In Progress",dependencies:"Business outcome and technical evidence definitions"}],
["milestone","synthetic_sample",{title:"Complete representative range blueprint",owner:"Solution Engineer + customer platform owner",due:"Week 2",status:"In Progress",dependencies:"Network, cloud, identity, tool, and data constraints"}],
["milestone","synthetic_sample",{title:"Run first integrated attack / agent scenario",owner:"Solution Engineer + customer operators",due:"Week 3",status:"Planned",dependencies:"Sentinel, endpoint, agent, and telemetry readiness"}],
["milestone","synthetic_sample",{title:"Deliver technical proof + executive readout",owner:"Solution Engineer + Sales",due:"Week 5",status:"Planned",dependencies:"Accepted metrics and reproducible evidence"}],
["risk","synthetic_sample",{title:"Success criteria are outcome words, not measurable thresholds",impact:"A technically successful pilot may still fail to support a buying decision.",owner:"Solution Engineer",mitigation:"Convert each desired outcome into a measure, source, threshold, owner, and decision rule before pilot execution.",escalationStatus:"Open",nextDecision:"Customer sponsor approves the evaluation scorecard."}],
["risk","synthetic_sample",{title:"Customer AI agent has uncontrolled production dependencies",impact:"The evaluation could either expose production data or fail to reproduce real behavior.",owner:"Customer AI owner + Solution Engineer",mitigation:"Create a bounded tool/data contract and a synthetic or approved-data path before agent integration.",escalationStatus:"Open",nextDecision:"Approve allowed tool calls, datasets, and human-escalation boundaries."}],
["risk","synthetic_sample",{title:"OT / hybrid segment cannot be represented with sufficient fidelity",impact:"The customer may reject conclusions as non-representative.",owner:"Solution Engineer + Professional Services",mitigation:"Document which production relationships must be exact, which can be emulated, and what conclusion each fidelity level supports.",escalationStatus:"Open",nextDecision:"Accept or redesign the representative terrain."}],
["incident","synthetic_sample",{title:"Agent blocks one attack but takes an unsafe tool-call path",affected:"Synthetic AI-agent evaluation",severity:"High",status:"Investigating",businessImpact:"A positive final outcome may hide behavior that would be unsafe in production.",owner:"Solution Engineer",nextAction:"Compare expected and actual trajectory, tool calls, permissions, escalation point, and recovery behavior.",jira:"",userBehavior:"Operator observes correct final containment but unexpected privileged action during the run.",contentFreshness:"Current synthetic evaluation",sourceSystem:"AI Proving Grounds + customer agent logs",configuration:"Synthetic pilot",connector:"Agent tool integration",product:"AI Proving Grounds",unknown:"Whether the unsafe step is agent policy, integration contract, tool permission, or scenario design."}],
["engineering_issue","synthetic_sample",{title:"Synthetic agent tool integration returns inconsistent state during replay",severity:"Medium",affected:"One synthetic replay path",environment:"Candidate demo",firstObserved:"Week 3",lastObserved:"Week 3",actual:"Replayed tool state differs after an otherwise identical scenario reset.",expected:"A controlled replay should preserve the documented evaluation boundary or explain the variance.",reproducible:"Intermittent",reproSteps:"Reset scenario; pin integration configuration; replay same attack; compare tool calls, timestamps, and range state; remove customer-side transform; repeat three times.",evidence:"Synthetic IDs, replay timestamps, configuration hash, and trajectory diff.",troubleshooting:"Range reset confirmed; one downstream stateful dependency remains under review.",workaround:"Use a clean integration sandbox for the customer decision run.",businessImpact:"Could weaken confidence in repeatability and technical proof.",engineeringAsk:"Confirm expected replay semantics and whether the stateful dependency is supported behavior.",jiraKey:"",jiraUrl:"",status:"Evidence gathering"}],
["kpi","synthetic_sample",{name:"Evaluation success criteria approved",hypothesis:"A decision-ready pilot begins with measurable acceptance rules.",baseline:"0/6 approved",target:"6/6 approved before execution",metricDefinition:"Count of defined success criteria with owner, source, threshold, and decision rule",sourceSystem:"Evaluation scorecard",owner:"Solution Engineer + customer sponsor",cadence:"Pre-pilot / weekly",calculation:"Approved criteria / required criteria",currentValue:"4/6 synthetic",realizedValue:"Not a real SimSpace or customer metric",approval:"Synthetic sample"}],
["kpi","synthetic_sample",{name:"Integrated scenario pass rate",hypothesis:"Representative tooling should survive repeatable live-fire scenarios without hidden workflow gaps.",baseline:"Synthetic baseline pending",target:">=90% of agreed critical scenarios produce accepted evidence",metricDefinition:"Accepted critical scenarios / executed critical scenarios",sourceSystem:"Range execution evidence",owner:"Solution Engineer",cadence:"Per pilot run",calculation:"Accepted / executed",currentValue:"Synthetic 7/9",realizedValue:"Not a real SimSpace or customer metric",approval:"Synthetic sample"}],
["kpi","synthetic_sample",{name:"Mean time to detect + respond",hypothesis:"The proposed operating model should compress detection and response under realistic conditions.",baseline:"Synthetic 74 minutes",target:"Synthetic <30 minutes for agreed scenarios",metricDefinition:"Elapsed time from first observable malicious event to accepted containment action",sourceSystem:"Range telemetry + SIEM evidence",owner:"Customer SOC lead",cadence:"Per scenario / executive readout",calculation:"Scenario-level elapsed time with explicit start/end events",currentValue:"Synthetic 41 minutes",realizedValue:"Not a real customer outcome",approval:"Synthetic sample"}],
["kpi","synthetic_sample",{name:"Agent escalation correctness",hypothesis:"The agent should know when to stop and involve a human.",baseline:"Synthetic 62%",target:"Synthetic >=95% on agreed escalation cases",metricDefinition:"Correct escalation decisions / required escalation decisions",sourceSystem:"Agent trajectory evaluation",owner:"Customer AI security lead",cadence:"Per scenario set",calculation:"Correct / required",currentValue:"Synthetic 83%",realizedValue:"Not a real customer outcome",approval:"Synthetic sample"}],
["adoption","synthetic_sample",{name:"Partner / operator readiness",value:"Synthetic: 8 of 12 participants completed the technical enablement path",period:"Week 2",source:"Candidate demo enablement tracker",owner:"Solution Engineer"}],
["adoption","synthetic_sample",{name:"Reusable integration assets",value:"Synthetic: 3 validated patterns, 2 still bespoke",period:"Current evaluation",source:"Candidate demo field-engineering tracker",owner:"Solution Engineer"}],
["stakeholder","synthetic_sample",{name:"Morgan Chen (Synthetic)",role:"CISO",organization:"Aegis National Bank",email:"",phone:"",decisionRole:"Executive sponsor and business decision owner",status:"Active",notes:"Synthetic stakeholder for business outcome, risk, and executive acceptance."}],
["stakeholder","synthetic_sample",{name:"Jordan Reyes (Synthetic)",role:"Director, Security Operations",organization:"Aegis National Bank",email:"",phone:"",decisionRole:"Operational champion and technical acceptance owner",status:"Active",notes:"Synthetic operator for scenario relevance and SOC workflow."}],
["stakeholder","synthetic_sample",{name:"Priya Shah (Synthetic)",role:"Head of AI Security",organization:"Aegis National Bank",email:"",phone:"",decisionRole:"Agent validation and safety owner",status:"Active",notes:"Synthetic owner for model/agent behavior, permissions, and escalation gates."}],
["stakeholder","synthetic_sample",{name:"Alex Thompson (Synthetic)",role:"Principal Platform Architect",organization:"Aegis National Bank",email:"",phone:"",decisionRole:"Integration and environment owner",status:"Active",notes:"Synthetic owner for cloud, identity, data, and tooling dependencies."}],
["meeting","synthetic_sample",{title:"Technical evaluation checkpoint",type:"Solution engineering / pilot",date:"Week 2",attendees:"CISO; SOC Director; AI Security; Platform Architect; Sales; Solution Engineer",objective:"Approve the technical proof plan, close environment gaps, and confirm what evidence is sufficient for a buying decision.",notes:"Synthetic candidate-demo meeting."}],
["action","synthetic_sample",{title:"Convert remaining two outcomes into measurable acceptance thresholds",owner:"Solution Engineer + customer sponsor",due:"Week 2",status:"In Progress",audience:"Customer / Internal"}],
["action","synthetic_sample",{title:"Validate agent tool-permission boundary in isolated integration environment",owner:"Solution Engineer + AI Security",due:"Week 2",status:"In Progress",audience:"Customer / Internal"}],
["action","synthetic_sample",{title:"Prepare executive proof narrative linking scenario evidence to decision criteria",owner:"Solution Engineer + Sales",due:"Week 4",status:"Planned",audience:"Internal"}],
["document","synthetic_sample",{name:"Aegis_SimSpace_Evaluation_Blueprint.md",classification:"Synthetic evaluation artifact",binaryStatus:"Built-in sample",approvedForBriefs:"Yes"}],
["document","synthetic_sample",{name:"Aegis_RFI_Technical_Response_Working_Draft.md",classification:"Synthetic RFI/RFP working artifact",binaryStatus:"Built-in sample",approvedForBriefs:"Yes"}],
["raci","template",{title:"Technical evaluation RACI",rows:[],roles:["Customer Executive Sponsor","Customer SOC","Customer AI Security","Customer Platform","Sales","Solution Engineer","Customer Success","Professional Services","Product"],note:"Template. Assign real names and decision rights during discovery."}],
["deployment_card","synthetic_sample",{title:"Range environment blueprint",column:"In Progress",stageOrder:1,sprint:"Evaluation design",owner:"Solution Engineer",dependency:"Customer topology + tool inventory",jiraKey:"",jiraUrl:"",notes:"Define which relationships require exact replica fidelity."}],
["deployment_card","synthetic_sample",{title:"Sentinel + endpoint integration",column:"Ready",stageOrder:2,sprint:"Field engineering",owner:"Solution Engineer",dependency:"API credentials + sandbox tenant",jiraKey:"",jiraUrl:"",notes:"Validate auth, schema, freshness, retries, and evidence export."}],
["deployment_card","synthetic_sample",{title:"AI agent trajectory capture",column:"Ready",stageOrder:3,sprint:"AI Proving Grounds",owner:"Solution Engineer + customer AI lead",dependency:"Allowed tools + synthetic data contract",jiraKey:"",jiraUrl:"",notes:"Evaluate path, not only final outcome."}],
["deployment_card","synthetic_sample",{title:"Decision run + executive readout",column:"Planned",stageOrder:4,sprint:"Technical close",owner:"Solution Engineer + Sales",dependency:"Accepted scorecard + stable environment",jiraKey:"",jiraUrl:"",notes:"Use reproducible evidence tied directly to customer decision criteria."}],
["sprint","synthetic_sample",{name:"Technical evaluation cycle",weeks:"Weeks 1-5",goal:"Move from outcome discovery to a decision-ready proof with representative terrain, integrated tooling, measurable criteria, and auditable evidence.",planned:9,completed:3,notes:"Synthetic Senior Solution Engineer operating cycle."}],
["call_prep","internal_proposal",{title:"Week 2 technical evaluation checkpoint",meetingDate:"Week 2",meetingType:"Evaluation design review",objective:"Secure agreement on proof criteria, range fidelity, integration boundaries, pilot sequence, and the evidence required to reach technical close.",attendees:"Customer sponsor; SOC; AI Security; Platform; Sales; Solution Engineer",opening:"Reconfirm what the customer is trying to prove and which technical result changes the buying decision.",currentState:"Discovery is complete. Four of six synthetic success criteria are accepted. Core tooling is identified. Two integration and fidelity questions remain open.",evidenceReady:"Outcome map; range blueprint; tool inventory; success scorecard; synthetic scenario catalog; integration assumptions; owner map.",questions:"Which production relationships must be exact? Which outcomes are board/mission critical? What evidence is decision-grade? Which agent actions require human escalation? Which partner or PS capability is required?",decisions:"Evaluation scorecard; range fidelity boundary; integration owners; pilot sequence; decision run date; technical close criteria.",escalationCriteria:"Escalate product behavior only when the issue is reproducible in the supported path with configuration, logs, trajectory evidence, scope, workaround, and a bounded technical ask.",followUp:"Publish decisions, architecture deltas, owners, dates, customer commitments, and the updated technical proof plan.",technologyNotes:"Use public SimSpace platform capabilities as context only. Validate customer-specific deployment, integration, security, and architecture directly.",assistantNotes:"Separate public SimSpace context from synthetic opportunity data. Never invent a customer commitment, supported integration, private SimSpace process, or realized outcome."}],
["assistant_profile","template",{title:"SimSpace Senior Solution Engineer operating playbook",playbook:"SOLUTION ENGINEERING BASELINE\n- Start with the customer outcome and buying decision, not the product feature list.\n- Map the terrain: enterprise, cloud, IT, OT, hybrid, identity, tools, data, operators, agents.\n- Define measurable success criteria before the evaluation.\n- Build only the integrations required to prove the decision.\n- Treat demo and pilot evidence as reproducible technical proof.\n- Evaluate AI-agent trajectory, tool calls, escalation gates, and recovery, not only final outcomes.\n- Translate technical evidence into an executive narrative without overstating results.\n- Preserve a clean handoff to Customer Success / Professional Services after close.\n- Convert recurring field-engineering patterns into reusable Product / partner assets.",participants:"",updatedFrom:"Public SimSpace role + public platform context + synthetic operating model"}],
["jira_config","internal_record",{siteUrl:"",deploymentBoardId:"",issueBoardId:"",projectKey:"",deploymentIssueType:"",issueType:"",connection:"Not connected",mode:"Optional internal work-system bridge"}]
];

const KB_SEED=[
{id:"kb-smspc-evaluation-design",slug:"evaluation-design",title:"Decision-Grade Evaluation Design",summary:"Convert desired outcomes into a measurable proof plan before a pilot begins.",category:"Solution Engineering",tags:["discovery","success-criteria","pilot","technical-close"],status:"published",source:"internal_best_practice",authorLabel:"Candidate operating model",body:"START WITH THE DECISION\nWhat must the customer be able to conclude after the evaluation?\n\nDEFINE THE TERRAIN\nDocument enterprise, cloud, IT, OT, hybrid, identity, data, tools, operators, agents, and partner boundaries.\n\nDEFINE SUCCESS\nEach criterion needs a metric, source, threshold, owner, and decision rule.\n\nDESIGN THE PROOF\nUse the smallest representative scenario set that can validate the decision.\n\nPRESERVE EVIDENCE\nCapture reproducible scenario configuration, integrations, timestamps, telemetry, tool calls, trajectories, outcomes, and exceptions.\n\nCLOSE THE LOOP\nTranslate accepted evidence into technical close, handoff, expansion hypothesis, or a bounded product question."},
{id:"kb-smspc-field-engineering",slug:"field-engineering",title:"Field Engineering Without Losing the Commercial Thread",summary:"Treat bespoke integration work as a proof enabler, not an open-ended implementation project.",category:"Field Engineering",tags:["api","protocols","integration","demo"],status:"published",source:"internal_best_practice",authorLabel:"Candidate operating model",body:"BOUND THE ASK\nName the customer decision the integration enables.\n\nDEFINE THE CONTRACT\nAuthentication, schema, timing, retries, permissions, failure behavior, observability, and rollback.\n\nBUILD THE MINIMUM\nImplement the smallest credible path to prove the evaluation.\n\nVERIFY\nUse a known-good control and preserve evidence.\n\nHAND OFF\nDocument what is reusable, what is bespoke, what belongs to Product, and what belongs to Professional Services after close."}
];
`;
