import vm from 'node:vm';
import zlib from 'node:zlib';
import { APP_GZ_B64 } from '../src/app.js';
const APP_HTML=zlib.gunzipSync(Buffer.from(APP_GZ_B64,'base64')).toString('utf8');
const must=['Command Center','Seed Demo Accounts','Clear Accounts','Add your first account','Renewal & Growth','Playbook library','Generate meeting brief','Print / Save PDF','ABNORMAL // CUSTOMER SUCCESS','kpi-card','trackPageView','localStorage'];
for (const x of must) if (!APP_HTML.includes(x)) throw new Error('missing '+x);
if (APP_HTML.includes('Post-Sales Business Operations')) throw new Error('legacy ZS business-operations brand remains');
const scriptMatch=APP_HTML.match(/<script>([\s\S]*)<\/script>/);
if(!scriptMatch) throw new Error('inline app script missing');
new vm.Script(scriptMatch[1]);
const names=APP_HTML.match(/const names=\[(.*?)\];/s)?.[1] || '';
const count=(names.match(/'/g)||[]).length/2;
if(count!==20) throw new Error('expected 20 seeded account names, got '+count);
console.log('ABC app smoke checks passed: 20-account seed, Abnormal-style shell, clickable KPI cards, PDF brief, analytics, and client script parse');
