import type { ActionFunctionArgs, LoaderFunctionArgs } from "react-router";
import { Form, useActionData, useLoaderData } from "react-router";
import { authenticate } from "../shopify.server";
import prisma from "../db.server";
import { ensureMerchant, merchantStateKey, seedOrdersCsv } from "../lib/state.server";
import { keyedToken } from "../../src/compact-state.js";
import { createGuard, refreshGuard } from "../lib/discount.server";

export const loader=async({request}:LoaderFunctionArgs)=>{const{session}=await authenticate.admin(request);const merchant=await ensureMerchant(session.shop);const policies=await prisma.couponPolicy.findMany({where:{merchantId:merchant.id},orderBy:{createdAt:"asc"}});const uses=await prisma.couponUse.count({where:{merchantId:merchant.id}});return{shop:session.shop,policies,uses};};
export const action=async({request}:ActionFunctionArgs)=>{const{admin,session}=await authenticate.admin(request);const merchant=await ensureMerchant(session.shop);const form=await request.formData();const intent=String(form.get("intent")||"");try{
 if(intent==="seed"){const file=form.get("historyCsv");if(!(file instanceof File)||file.size===0)throw new Error("Choose a Shopify Orders CSV export");if(file.size>20*1024*1024)throw new Error("CSV must be 20 MB or smaller for the pilot seed");const result=await seedOrdersCsv(session.shop,await file.text());const policies=await prisma.couponPolicy.findMany({where:{merchantId:merchant.id,enabled:true}});for(const policy of policies)await refreshGuard(admin,session.shop,policy);return{ok:true,message:`Seeded ${result.orders} orders and ${result.uses} coupon uses.  Raw CSV rows were not retained.`};}
 if(intent==="protect"){const couponCode=String(form.get("couponCode")||"").trim();if(!couponCode)throw new Error("Coupon code is required");const secret=merchantStateKey(session.shop);const couponKey=keyedToken(secret,"code",couponCode);let policy=await prisma.couponPolicy.upsert({where:{merchantId_couponKey:{merchantId:merchant.id,couponKey}},update:{couponCode,enabled:true},create:{merchantId:merchant.id,couponCode,couponKey,enabled:true}});const discountId=policy.discountId?await refreshGuard(admin,session.shop,policy):await createGuard(admin,session.shop,policy);policy=await prisma.couponPolicy.update({where:{id:policy.id},data:{discountId}});return{ok:true,message:`Protection enabled for ${couponCode}`,policy};}
 if(intent==="refresh"){const id=String(form.get("id")||"");const policy=await prisma.couponPolicy.findFirstOrThrow({where:{id,merchantId:merchant.id}});await refreshGuard(admin,session.shop,policy);return{ok:true,message:"Compact checkout state refreshed"};}
 return{ok:false,message:"Unknown action"};
 }catch(error:any){return{ok:false,message:error?.message||"Action failed"};}};
export default function Index(){const data=useLoaderData<typeof loader>();const result=useActionData<typeof action>();return <s-page heading="BuyerOrigin"><s-section heading="Stop the same buyer from using the same coupon again"><p>BuyerOrigin stores compact pseudonymous coupon-use state and rejects only eligible entered coupon codes.  Checkout itself remains available.</p>{result?.message?<s-banner tone={result.ok?"success":"critical"} heading={result.message}></s-banner>:null}<Form method="post" encType="multipart/form-data"><input type="hidden" name="intent" value="seed"/><label>Seed historical Shopify Orders CSV<br/><input name="historyCsv" type="file" accept=".csv,text/csv" required/></label><br/><s-button type="submit">Seed history without retaining raw rows</s-button></Form></s-section><s-section heading="Protect a coupon"><Form method="post"><input type="hidden" name="intent" value="protect"/><s-text-field name="couponCode" label="Coupon code to protect" details="Exact code, case-insensitive"></s-text-field><s-button type="submit" variant="primary">Enable coupon protection</s-button></Form></s-section><s-section heading="Protected coupons"><p>{data.uses} pseudonymous historical coupon-use records are stored for this shop.</p>{data.policies.length===0?<p>No live coupon guards are configured.</p>:data.policies.map((p:any)=><div key={p.id} style={{marginBottom:16}}><strong>{p.couponCode}</strong> · {p.enabled?"enabled":"disabled"} · {p.minSignals}/3 signals · {p.lookbackDays} days<Form method="post"><input type="hidden" name="intent" value="refresh"/><input type="hidden" name="id" value={p.id}/><s-button type="submit">Refresh checkout state</s-button></Form></div>)}</s-section></s-page>;}
